# 测试环境配置文件
zap:
  level: 'info'
  format: 'console'
  prefix: '[dehaze-go-test]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
    env: local # 修改为public可以关闭路由日志输出
    addr: 8989
    oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
    use-redis: false # 使用redis
    use-mongo: false     # 使用mongo
    use-multipoint: false
    # IP限制次数 一个小时15000次
    iplimit-count: 15000
    #  IP限制一个小时
    iplimit-time: 3600
    #  路由全局前缀
    router-prefix: ""
    #  严格角色模式 打开后权限将会存在上下级关系
    use-strict-auth: false

captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0 # 0代表一直开启，大于0代表限制次数
    open-captcha-timeout: 3600 # open-captcha大于0时才生效

db:
  type: mysql
  path: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  name: dehaze_test
  username: root
  password: 123456
  max-idle-conns: 10
  max-open-conns: 100
  singular: true
  log-mode: info
  log-zap: false

jwt:
  key: SecretKey012345678901234567890123456789012345678901234567890123456789
  ttl: 7200

redis:
  #是否使用redis集群模式
  useCluster: false
  addr: 127.0.0.1:6379
  password: "123456"
  db: 4