SYSTEM_USER_ID = 0

TASK_CACHE_PREFIX = "task:"
TASK_PROGRESS_PREFIX = "task:progress:"
TASK_CANCEL_PREFIX = "task:cancel:"
IDEMPOTENCY_KEY_PREFIX = "idempotency:task:"

TASK_EXPIRE_HOURS = 24
CANCEL_FLAG_TTL_SECONDS = 5 * 60
RESULT_FILE_EXPIRE_DAYS = 7

MAX_ROWS = 100_000
MAX_IMPORT_FILE_SIZE = 20 * 1024 * 1024
SYNC_THRESHOLD = 1000
BATCH_SIZE = 1000
IMPORT_BATCH_TX_SIZE = 500
MAX_CONCURRENT_PER_USER = 5

PROGRESS_MIN_INTERVAL_SECONDS = 2.0
PROGRESS_MIN_PERCENT_DELTA = 5

CATEGORY_IMPORT = "import"
CATEGORY_EXPORT = "export"
