Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="root"
    password="20230914wpx";
};

KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="root"
    password="20230914wpx"
    user_root="20230914wpx";
};
