// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bo "github.com/earthyzinc/dehaze-go/internal/model/bo"

	mock "github.com/stretchr/testify/mock"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	vo "github.com/earthyzinc/dehaze-go/internal/model/vo"
)

// MockIDictService is an autogenerated mock type for the IDictService type
type MockIDictService struct {
	mock.Mock
}

type MockIDictService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDictService) EXPECT() *MockIDictService_Expecter {
	return &MockIDictService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, form
func (_m *MockIDictService) Create(ctx context.Context, form *bo.DictFormBO) error {
	ret := _m.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bo.DictFormBO) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDictService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - form *bo.DictFormBO
func (_e *MockIDictService_Expecter) Create(ctx interface{}, form interface{}) *MockIDictService_Create_Call {
	return &MockIDictService_Create_Call{Call: _e.mock.On("Create", ctx, form)}
}

func (_c *MockIDictService_Create_Call) Run(run func(ctx context.Context, form *bo.DictFormBO)) *MockIDictService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bo.DictFormBO))
	})
	return _c
}

func (_c *MockIDictService_Create_Call) Return(_a0 error) *MockIDictService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictService_Create_Call) RunAndReturn(run func(context.Context, *bo.DictFormBO) error) *MockIDictService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDictService) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDictService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDictService_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDictService_Delete_Call {
	return &MockIDictService_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDictService_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDictService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDictService_Delete_Call) Return(_a0 error) *MockIDictService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictService_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDictService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTypeCode provides a mock function with given fields: ctx, typeCode
func (_m *MockIDictService) GetByTypeCode(ctx context.Context, typeCode string) ([]vo.Option, error) {
	ret := _m.Called(ctx, typeCode)

	if len(ret) == 0 {
		panic("no return value specified for GetByTypeCode")
	}

	var r0 []vo.Option
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]vo.Option, error)); ok {
		return rf(ctx, typeCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []vo.Option); ok {
		r0 = rf(ctx, typeCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vo.Option)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, typeCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictService_GetByTypeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTypeCode'
type MockIDictService_GetByTypeCode_Call struct {
	*mock.Call
}

// GetByTypeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - typeCode string
func (_e *MockIDictService_Expecter) GetByTypeCode(ctx interface{}, typeCode interface{}) *MockIDictService_GetByTypeCode_Call {
	return &MockIDictService_GetByTypeCode_Call{Call: _e.mock.On("GetByTypeCode", ctx, typeCode)}
}

func (_c *MockIDictService_GetByTypeCode_Call) Run(run func(ctx context.Context, typeCode string)) *MockIDictService_GetByTypeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIDictService_GetByTypeCode_Call) Return(_a0 []vo.Option, _a1 error) *MockIDictService_GetByTypeCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictService_GetByTypeCode_Call) RunAndReturn(run func(context.Context, string) ([]vo.Option, error)) *MockIDictService_GetByTypeCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, id
func (_m *MockIDictService) GetFormData(ctx context.Context, id int64) (*bo.DictFormBO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *bo.DictFormBO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*bo.DictFormBO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *bo.DictFormBO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.DictFormBO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictService_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIDictService_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDictService_Expecter) GetFormData(ctx interface{}, id interface{}) *MockIDictService_GetFormData_Call {
	return &MockIDictService_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, id)}
}

func (_c *MockIDictService_GetFormData_Call) Run(run func(ctx context.Context, id int64)) *MockIDictService_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDictService_GetFormData_Call) Return(_a0 *bo.DictFormBO, _a1 error) *MockIDictService_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictService_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*bo.DictFormBO, error)) *MockIDictService_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// GetPage provides a mock function with given fields: ctx, q
func (_m *MockIDictService) GetPage(ctx context.Context, q *query.DictPageQuery) (*vo.PageResult[vo.DictPageVO], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 *vo.PageResult[vo.DictPageVO]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictPageQuery) (*vo.PageResult[vo.DictPageVO], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictPageQuery) *vo.PageResult[vo.DictPageVO]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.PageResult[vo.DictPageVO])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DictPageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictService_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type MockIDictService_GetPage_Call struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DictPageQuery
func (_e *MockIDictService_Expecter) GetPage(ctx interface{}, q interface{}) *MockIDictService_GetPage_Call {
	return &MockIDictService_GetPage_Call{Call: _e.mock.On("GetPage", ctx, q)}
}

func (_c *MockIDictService_GetPage_Call) Run(run func(ctx context.Context, q *query.DictPageQuery)) *MockIDictService_GetPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DictPageQuery))
	})
	return _c
}

func (_c *MockIDictService_GetPage_Call) Return(_a0 *vo.PageResult[vo.DictPageVO], _a1 error) *MockIDictService_GetPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictService_GetPage_Call) RunAndReturn(run func(context.Context, *query.DictPageQuery) (*vo.PageResult[vo.DictPageVO], error)) *MockIDictService_GetPage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, form
func (_m *MockIDictService) Update(ctx context.Context, id int64, form *bo.DictFormBO) error {
	ret := _m.Called(ctx, id, form)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *bo.DictFormBO) error); ok {
		r0 = rf(ctx, id, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDictService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - form *bo.DictFormBO
func (_e *MockIDictService_Expecter) Update(ctx interface{}, id interface{}, form interface{}) *MockIDictService_Update_Call {
	return &MockIDictService_Update_Call{Call: _e.mock.On("Update", ctx, id, form)}
}

func (_c *MockIDictService_Update_Call) Run(run func(ctx context.Context, id int64, form *bo.DictFormBO)) *MockIDictService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*bo.DictFormBO))
	})
	return _c
}

func (_c *MockIDictService_Update_Call) Return(_a0 error) *MockIDictService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictService_Update_Call) RunAndReturn(run func(context.Context, int64, *bo.DictFormBO) error) *MockIDictService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDictService creates a new instance of MockIDictService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDictService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDictService {
	mock := &MockIDictService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
