// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bo "github.com/earthyzinc/dehaze-go/internal/model/bo"

	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	vo "github.com/earthyzinc/dehaze-go/internal/model/vo"
)

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, form
func (_m *MockIUserService) Create(ctx context.Context, form *bo.UserFormBO) error {
	ret := _m.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bo.UserFormBO) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - form *bo.UserFormBO
func (_e *MockIUserService_Expecter) Create(ctx interface{}, form interface{}) *MockIUserService_Create_Call {
	return &MockIUserService_Create_Call{Call: _e.mock.On("Create", ctx, form)}
}

func (_c *MockIUserService_Create_Call) Run(run func(ctx context.Context, form *bo.UserFormBO)) *MockIUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bo.UserFormBO))
	})
	return _c
}

func (_c *MockIUserService_Create_Call) Return(_a0 error) *MockIUserService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_Create_Call) RunAndReturn(run func(context.Context, *bo.UserFormBO) error) *MockIUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIUserService) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIUserService_Expecter) Delete(ctx interface{}, ids interface{}) *MockIUserService_Delete_Call {
	return &MockIUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIUserService_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIUserService_Delete_Call) Return(_a0 error) *MockIUserService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadImportTemplate provides a mock function with given fields: ctx
func (_m *MockIUserService) DownloadImportTemplate(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DownloadImportTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_DownloadImportTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadImportTemplate'
type MockIUserService_DownloadImportTemplate_Call struct {
	*mock.Call
}

// DownloadImportTemplate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUserService_Expecter) DownloadImportTemplate(ctx interface{}) *MockIUserService_DownloadImportTemplate_Call {
	return &MockIUserService_DownloadImportTemplate_Call{Call: _e.mock.On("DownloadImportTemplate", ctx)}
}

func (_c *MockIUserService_DownloadImportTemplate_Call) Run(run func(ctx context.Context)) *MockIUserService_DownloadImportTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIUserService_DownloadImportTemplate_Call) Return(_a0 string, _a1 error) *MockIUserService_DownloadImportTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_DownloadImportTemplate_Call) RunAndReturn(run func(context.Context) (string, error)) *MockIUserService_DownloadImportTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUsers provides a mock function with given fields: ctx, q
func (_m *MockIUserService) ExportUsers(ctx context.Context, q *query.UserPageQuery) (string, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for ExportUsers")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) (string, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) string); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.UserPageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_ExportUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUsers'
type MockIUserService_ExportUsers_Call struct {
	*mock.Call
}

// ExportUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.UserPageQuery
func (_e *MockIUserService_Expecter) ExportUsers(ctx interface{}, q interface{}) *MockIUserService_ExportUsers_Call {
	return &MockIUserService_ExportUsers_Call{Call: _e.mock.On("ExportUsers", ctx, q)}
}

func (_c *MockIUserService_ExportUsers_Call) Run(run func(ctx context.Context, q *query.UserPageQuery)) *MockIUserService_ExportUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.UserPageQuery))
	})
	return _c
}

func (_c *MockIUserService_ExportUsers_Call) Return(_a0 string, _a1 error) *MockIUserService_ExportUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_ExportUsers_Call) RunAndReturn(run func(context.Context, *query.UserPageQuery) (string, error)) *MockIUserService_ExportUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIUserService) GetByID(ctx context.Context, id int64) (*vo.UserPageVO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *vo.UserPageVO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*vo.UserPageVO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *vo.UserPageVO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.UserPageVO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserService_Expecter) GetByID(ctx interface{}, id interface{}) *MockIUserService_GetByID_Call {
	return &MockIUserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIUserService_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockIUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserService_GetByID_Call) Return(_a0 *vo.UserPageVO, _a1 error) *MockIUserService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*vo.UserPageVO, error)) *MockIUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUserInfo provides a mock function with given fields: ctx, userID
func (_m *MockIUserService) GetCurrentUserInfo(ctx context.Context, userID int64) (*vo.UserInfoVO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUserInfo")
	}

	var r0 *vo.UserInfoVO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*vo.UserInfoVO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *vo.UserInfoVO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.UserInfoVO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetCurrentUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUserInfo'
type MockIUserService_GetCurrentUserInfo_Call struct {
	*mock.Call
}

// GetCurrentUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIUserService_Expecter) GetCurrentUserInfo(ctx interface{}, userID interface{}) *MockIUserService_GetCurrentUserInfo_Call {
	return &MockIUserService_GetCurrentUserInfo_Call{Call: _e.mock.On("GetCurrentUserInfo", ctx, userID)}
}

func (_c *MockIUserService_GetCurrentUserInfo_Call) Run(run func(ctx context.Context, userID int64)) *MockIUserService_GetCurrentUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserService_GetCurrentUserInfo_Call) Return(_a0 *vo.UserInfoVO, _a1 error) *MockIUserService_GetCurrentUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetCurrentUserInfo_Call) RunAndReturn(run func(context.Context, int64) (*vo.UserInfoVO, error)) *MockIUserService_GetCurrentUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, id
func (_m *MockIUserService) GetFormData(ctx context.Context, id int64) (*bo.UserFormBO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *bo.UserFormBO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*bo.UserFormBO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *bo.UserFormBO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.UserFormBO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIUserService_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserService_Expecter) GetFormData(ctx interface{}, id interface{}) *MockIUserService_GetFormData_Call {
	return &MockIUserService_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, id)}
}

func (_c *MockIUserService_GetFormData_Call) Run(run func(ctx context.Context, id int64)) *MockIUserService_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserService_GetFormData_Call) Return(_a0 *bo.UserFormBO, _a1 error) *MockIUserService_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*bo.UserFormBO, error)) *MockIUserService_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// GetPage provides a mock function with given fields: ctx, q
func (_m *MockIUserService) GetPage(ctx context.Context, q *query.UserPageQuery) (*vo.PageResult[vo.UserPageVO], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 *vo.PageResult[vo.UserPageVO]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) (*vo.PageResult[vo.UserPageVO], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) *vo.PageResult[vo.UserPageVO]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.PageResult[vo.UserPageVO])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.UserPageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type MockIUserService_GetPage_Call struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.UserPageQuery
func (_e *MockIUserService_Expecter) GetPage(ctx interface{}, q interface{}) *MockIUserService_GetPage_Call {
	return &MockIUserService_GetPage_Call{Call: _e.mock.On("GetPage", ctx, q)}
}

func (_c *MockIUserService_GetPage_Call) Run(run func(ctx context.Context, q *query.UserPageQuery)) *MockIUserService_GetPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.UserPageQuery))
	})
	return _c
}

func (_c *MockIUserService_GetPage_Call) Return(_a0 *vo.PageResult[vo.UserPageVO], _a1 error) *MockIUserService_GetPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetPage_Call) RunAndReturn(run func(context.Context, *query.UserPageQuery) (*vo.PageResult[vo.UserPageVO], error)) *MockIUserService_GetPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAuthInfo provides a mock function with given fields: ctx, username
func (_m *MockIUserService) GetUserAuthInfo(ctx context.Context, username string) (*model.UserAuthInfo, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAuthInfo")
	}

	var r0 *model.UserAuthInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserAuthInfo, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserAuthInfo); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAuthInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_GetUserAuthInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAuthInfo'
type MockIUserService_GetUserAuthInfo_Call struct {
	*mock.Call
}

// GetUserAuthInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserService_Expecter) GetUserAuthInfo(ctx interface{}, username interface{}) *MockIUserService_GetUserAuthInfo_Call {
	return &MockIUserService_GetUserAuthInfo_Call{Call: _e.mock.On("GetUserAuthInfo", ctx, username)}
}

func (_c *MockIUserService_GetUserAuthInfo_Call) Run(run func(ctx context.Context, username string)) *MockIUserService_GetUserAuthInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserService_GetUserAuthInfo_Call) Return(_a0 *model.UserAuthInfo, _a1 error) *MockIUserService_GetUserAuthInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_GetUserAuthInfo_Call) RunAndReturn(run func(context.Context, string) (*model.UserAuthInfo, error)) *MockIUserService_GetUserAuthInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ImportUsers provides a mock function with given fields: ctx, data
func (_m *MockIUserService) ImportUsers(ctx context.Context, data []vo.UserImportVO) (*vo.ImportResultVO, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ImportUsers")
	}

	var r0 *vo.ImportResultVO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []vo.UserImportVO) (*vo.ImportResultVO, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []vo.UserImportVO) *vo.ImportResultVO); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.ImportResultVO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []vo.UserImportVO) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_ImportUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportUsers'
type MockIUserService_ImportUsers_Call struct {
	*mock.Call
}

// ImportUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - data []vo.UserImportVO
func (_e *MockIUserService_Expecter) ImportUsers(ctx interface{}, data interface{}) *MockIUserService_ImportUsers_Call {
	return &MockIUserService_ImportUsers_Call{Call: _e.mock.On("ImportUsers", ctx, data)}
}

func (_c *MockIUserService_ImportUsers_Call) Run(run func(ctx context.Context, data []vo.UserImportVO)) *MockIUserService_ImportUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]vo.UserImportVO))
	})
	return _c
}

func (_c *MockIUserService_ImportUsers_Call) Return(_a0 *vo.ImportResultVO, _a1 error) *MockIUserService_ImportUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_ImportUsers_Call) RunAndReturn(run func(context.Context, []vo.UserImportVO) (*vo.ImportResultVO, error)) *MockIUserService_ImportUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ImportUsersFromFile provides a mock function with given fields: ctx, file
func (_m *MockIUserService) ImportUsersFromFile(ctx context.Context, file io.Reader) (*vo.ImportResultVO, error) {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for ImportUsersFromFile")
	}

	var r0 *vo.ImportResultVO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (*vo.ImportResultVO, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) *vo.ImportResultVO); ok {
		r0 = rf(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.ImportResultVO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_ImportUsersFromFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportUsersFromFile'
type MockIUserService_ImportUsersFromFile_Call struct {
	*mock.Call
}

// ImportUsersFromFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
func (_e *MockIUserService_Expecter) ImportUsersFromFile(ctx interface{}, file interface{}) *MockIUserService_ImportUsersFromFile_Call {
	return &MockIUserService_ImportUsersFromFile_Call{Call: _e.mock.On("ImportUsersFromFile", ctx, file)}
}

func (_c *MockIUserService_ImportUsersFromFile_Call) Run(run func(ctx context.Context, file io.Reader)) *MockIUserService_ImportUsersFromFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockIUserService_ImportUsersFromFile_Call) Return(_a0 *vo.ImportResultVO, _a1 error) *MockIUserService_ImportUsersFromFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_ImportUsersFromFile_Call) RunAndReturn(run func(context.Context, io.Reader) (*vo.ImportResultVO, error)) *MockIUserService_ImportUsersFromFile_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, u
func (_m *MockIUserService) Login(ctx context.Context, u *model.SysUser) (*model.UserAuthInfo, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.UserAuthInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser) (*model.UserAuthInfo, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser) *model.UserAuthInfo); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAuthInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.SysUser) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - u *model.SysUser
func (_e *MockIUserService_Expecter) Login(ctx interface{}, u interface{}) *MockIUserService_Login_Call {
	return &MockIUserService_Login_Call{Call: _e.mock.On("Login", ctx, u)}
}

func (_c *MockIUserService_Login_Call) Run(run func(ctx context.Context, u *model.SysUser)) *MockIUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysUser))
	})
	return _c
}

func (_c *MockIUserService_Login_Call) Return(_a0 *model.UserAuthInfo, _a1 error) *MockIUserService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_Login_Call) RunAndReturn(run func(context.Context, *model.SysUser) (*model.UserAuthInfo, error)) *MockIUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, id
func (_m *MockIUserService) ResetPassword(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockIUserService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserService_Expecter) ResetPassword(ctx interface{}, id interface{}) *MockIUserService_ResetPassword_Call {
	return &MockIUserService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, id)}
}

func (_c *MockIUserService_ResetPassword_Call) Run(run func(ctx context.Context, id int64)) *MockIUserService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserService_ResetPassword_Call) Return(_a0 error) *MockIUserService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_ResetPassword_Call) RunAndReturn(run func(context.Context, int64) error) *MockIUserService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, form
func (_m *MockIUserService) Update(ctx context.Context, id int64, form *bo.UserFormBO) error {
	ret := _m.Called(ctx, id, form)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *bo.UserFormBO) error); ok {
		r0 = rf(ctx, id, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - form *bo.UserFormBO
func (_e *MockIUserService_Expecter) Update(ctx interface{}, id interface{}, form interface{}) *MockIUserService_Update_Call {
	return &MockIUserService_Update_Call{Call: _e.mock.On("Update", ctx, id, form)}
}

func (_c *MockIUserService_Update_Call) Run(run func(ctx context.Context, id int64, form *bo.UserFormBO)) *MockIUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*bo.UserFormBO))
	})
	return _c
}

func (_c *MockIUserService_Update_Call) Return(_a0 error) *MockIUserService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_Update_Call) RunAndReturn(run func(context.Context, int64, *bo.UserFormBO) error) *MockIUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, password
func (_m *MockIUserService) UpdatePassword(ctx context.Context, id int64, password string) error {
	ret := _m.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockIUserService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - password string
func (_e *MockIUserService_Expecter) UpdatePassword(ctx interface{}, id interface{}, password interface{}) *MockIUserService_UpdatePassword_Call {
	return &MockIUserService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, password)}
}

func (_c *MockIUserService_UpdatePassword_Call) Run(run func(ctx context.Context, id int64, password string)) *MockIUserService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockIUserService_UpdatePassword_Call) Return(_a0 error) *MockIUserService_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_UpdatePassword_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockIUserService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockIUserService) UpdateStatus(ctx context.Context, id int64, status int8) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int8) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIUserService_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status int8
func (_e *MockIUserService_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockIUserService_UpdateStatus_Call {
	return &MockIUserService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockIUserService_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status int8)) *MockIUserService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int8))
	})
	return _c
}

func (_c *MockIUserService_UpdateStatus_Call) Return(_a0 error) *MockIUserService_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserService_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, int8) error) *MockIUserService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
