// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bo "github.com/earthyzinc/dehaze-go/internal/model/bo"

	mock "github.com/stretchr/testify/mock"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	vo "github.com/earthyzinc/dehaze-go/internal/model/vo"
)

// MockIDictTypeService is an autogenerated mock type for the IDictTypeService type
type MockIDictTypeService struct {
	mock.Mock
}

type MockIDictTypeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDictTypeService) EXPECT() *MockIDictTypeService_Expecter {
	return &MockIDictTypeService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, form
func (_m *MockIDictTypeService) Create(ctx context.Context, form *bo.DictTypeFormBO) error {
	ret := _m.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bo.DictTypeFormBO) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDictTypeService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - form *bo.DictTypeFormBO
func (_e *MockIDictTypeService_Expecter) Create(ctx interface{}, form interface{}) *MockIDictTypeService_Create_Call {
	return &MockIDictTypeService_Create_Call{Call: _e.mock.On("Create", ctx, form)}
}

func (_c *MockIDictTypeService_Create_Call) Run(run func(ctx context.Context, form *bo.DictTypeFormBO)) *MockIDictTypeService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bo.DictTypeFormBO))
	})
	return _c
}

func (_c *MockIDictTypeService_Create_Call) Return(_a0 error) *MockIDictTypeService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeService_Create_Call) RunAndReturn(run func(context.Context, *bo.DictTypeFormBO) error) *MockIDictTypeService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDictTypeService) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDictTypeService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDictTypeService_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDictTypeService_Delete_Call {
	return &MockIDictTypeService_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDictTypeService_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDictTypeService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDictTypeService_Delete_Call) Return(_a0 error) *MockIDictTypeService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeService_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDictTypeService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, id
func (_m *MockIDictTypeService) GetFormData(ctx context.Context, id int64) (*bo.DictTypeFormBO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *bo.DictTypeFormBO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*bo.DictTypeFormBO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *bo.DictTypeFormBO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.DictTypeFormBO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeService_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIDictTypeService_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDictTypeService_Expecter) GetFormData(ctx interface{}, id interface{}) *MockIDictTypeService_GetFormData_Call {
	return &MockIDictTypeService_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, id)}
}

func (_c *MockIDictTypeService_GetFormData_Call) Run(run func(ctx context.Context, id int64)) *MockIDictTypeService_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDictTypeService_GetFormData_Call) Return(_a0 *bo.DictTypeFormBO, _a1 error) *MockIDictTypeService_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeService_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*bo.DictTypeFormBO, error)) *MockIDictTypeService_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// GetPage provides a mock function with given fields: ctx, q
func (_m *MockIDictTypeService) GetPage(ctx context.Context, q *query.DictTypePageQuery) (*vo.PageResult[vo.DictTypePageVO], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 *vo.PageResult[vo.DictTypePageVO]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictTypePageQuery) (*vo.PageResult[vo.DictTypePageVO], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictTypePageQuery) *vo.PageResult[vo.DictTypePageVO]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vo.PageResult[vo.DictTypePageVO])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DictTypePageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeService_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type MockIDictTypeService_GetPage_Call struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DictTypePageQuery
func (_e *MockIDictTypeService_Expecter) GetPage(ctx interface{}, q interface{}) *MockIDictTypeService_GetPage_Call {
	return &MockIDictTypeService_GetPage_Call{Call: _e.mock.On("GetPage", ctx, q)}
}

func (_c *MockIDictTypeService_GetPage_Call) Run(run func(ctx context.Context, q *query.DictTypePageQuery)) *MockIDictTypeService_GetPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DictTypePageQuery))
	})
	return _c
}

func (_c *MockIDictTypeService_GetPage_Call) Return(_a0 *vo.PageResult[vo.DictTypePageVO], _a1 error) *MockIDictTypeService_GetPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeService_GetPage_Call) RunAndReturn(run func(context.Context, *query.DictTypePageQuery) (*vo.PageResult[vo.DictTypePageVO], error)) *MockIDictTypeService_GetPage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, form
func (_m *MockIDictTypeService) Update(ctx context.Context, id int64, form *bo.DictTypeFormBO) error {
	ret := _m.Called(ctx, id, form)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *bo.DictTypeFormBO) error); ok {
		r0 = rf(ctx, id, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDictTypeService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - form *bo.DictTypeFormBO
func (_e *MockIDictTypeService_Expecter) Update(ctx interface{}, id interface{}, form interface{}) *MockIDictTypeService_Update_Call {
	return &MockIDictTypeService_Update_Call{Call: _e.mock.On("Update", ctx, id, form)}
}

func (_c *MockIDictTypeService_Update_Call) Run(run func(ctx context.Context, id int64, form *bo.DictTypeFormBO)) *MockIDictTypeService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*bo.DictTypeFormBO))
	})
	return _c
}

func (_c *MockIDictTypeService_Update_Call) Return(_a0 error) *MockIDictTypeService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeService_Update_Call) RunAndReturn(run func(context.Context, int64, *bo.DictTypeFormBO) error) *MockIDictTypeService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDictTypeService creates a new instance of MockIDictTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDictTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDictTypeService {
	mock := &MockIDictTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
