// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	time "time"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, taskType, params, userID, idempotencyKey
func (_m *MockTaskService) CreateTask(ctx context.Context, taskType string, params interface{}, userID int64, idempotencyKey string) (*model.SysTask, error) {
	ret := _m.Called(ctx, taskType, params, userID, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *model.SysTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, int64, string) (*model.SysTask, error)); ok {
		return rf(ctx, taskType, params, userID, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, int64, string) *model.SysTask); ok {
		r0 = rf(ctx, taskType, params, userID, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, int64, string) error); ok {
		r1 = rf(ctx, taskType, params, userID, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskType string
//   - params interface{}
//   - userID int64
//   - idempotencyKey string
func (_e *MockTaskService_Expecter) CreateTask(ctx interface{}, taskType interface{}, params interface{}, userID interface{}, idempotencyKey interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, taskType, params, userID, idempotencyKey)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(ctx context.Context, taskType string, params interface{}, userID int64, idempotencyKey string)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(_a0 *model.SysTask, _a1 error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(context.Context, string, interface{}, int64, string) (*model.SysTask, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskStatus provides a mock function with given fields: ctx, taskID
func (_m *MockTaskService) GetTaskStatus(ctx context.Context, taskID string) (*model.SysTask, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatus")
	}

	var r0 *model.SysTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysTask, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysTask); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskStatus'
type MockTaskService_GetTaskStatus_Call struct {
	*mock.Call
}

// GetTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskService_Expecter) GetTaskStatus(ctx interface{}, taskID interface{}) *MockTaskService_GetTaskStatus_Call {
	return &MockTaskService_GetTaskStatus_Call{Call: _e.mock.On("GetTaskStatus", ctx, taskID)}
}

func (_c *MockTaskService_GetTaskStatus_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskService_GetTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_GetTaskStatus_Call) Return(_a0 *model.SysTask, _a1 error) *MockTaskService_GetTaskStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTaskStatus_Call) RunAndReturn(run func(context.Context, string) (*model.SysTask, error)) *MockTaskService_GetTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsCancelled provides a mock function with given fields: ctx, taskID
func (_m *MockTaskService) IsCancelled(ctx context.Context, taskID string) bool {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for IsCancelled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTaskService_IsCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCancelled'
type MockTaskService_IsCancelled_Call struct {
	*mock.Call
}

// IsCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTaskService_Expecter) IsCancelled(ctx interface{}, taskID interface{}) *MockTaskService_IsCancelled_Call {
	return &MockTaskService_IsCancelled_Call{Call: _e.mock.On("IsCancelled", ctx, taskID)}
}

func (_c *MockTaskService_IsCancelled_Call) Run(run func(ctx context.Context, taskID string)) *MockTaskService_IsCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_IsCancelled_Call) Return(_a0 bool) *MockTaskService_IsCancelled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_IsCancelled_Call) RunAndReturn(run func(context.Context, string) bool) *MockTaskService_IsCancelled_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskProgress provides a mock function with given fields: ctx, taskID, progress, current, total
func (_m *MockTaskService) UpdateTaskProgress(ctx context.Context, taskID string, progress int, current int, total int) error {
	ret := _m.Called(ctx, taskID, progress, current, total)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskProgress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int) error); ok {
		r0 = rf(ctx, taskID, progress, current, total)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_UpdateTaskProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskProgress'
type MockTaskService_UpdateTaskProgress_Call struct {
	*mock.Call
}

// UpdateTaskProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - progress int
//   - current int
//   - total int
func (_e *MockTaskService_Expecter) UpdateTaskProgress(ctx interface{}, taskID interface{}, progress interface{}, current interface{}, total interface{}) *MockTaskService_UpdateTaskProgress_Call {
	return &MockTaskService_UpdateTaskProgress_Call{Call: _e.mock.On("UpdateTaskProgress", ctx, taskID, progress, current, total)}
}

func (_c *MockTaskService_UpdateTaskProgress_Call) Run(run func(ctx context.Context, taskID string, progress int, current int, total int)) *MockTaskService_UpdateTaskProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockTaskService_UpdateTaskProgress_Call) Return(_a0 error) *MockTaskService_UpdateTaskProgress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_UpdateTaskProgress_Call) RunAndReturn(run func(context.Context, string, int, int, int) error) *MockTaskService_UpdateTaskProgress_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskResult provides a mock function with given fields: ctx, taskID, result, expiresAt
func (_m *MockTaskService) UpdateTaskResult(ctx context.Context, taskID string, result string, expiresAt time.Time) error {
	ret := _m.Called(ctx, taskID, result, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, taskID, result, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_UpdateTaskResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskResult'
type MockTaskService_UpdateTaskResult_Call struct {
	*mock.Call
}

// UpdateTaskResult is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - result string
//   - expiresAt time.Time
func (_e *MockTaskService_Expecter) UpdateTaskResult(ctx interface{}, taskID interface{}, result interface{}, expiresAt interface{}) *MockTaskService_UpdateTaskResult_Call {
	return &MockTaskService_UpdateTaskResult_Call{Call: _e.mock.On("UpdateTaskResult", ctx, taskID, result, expiresAt)}
}

func (_c *MockTaskService_UpdateTaskResult_Call) Run(run func(ctx context.Context, taskID string, result string, expiresAt time.Time)) *MockTaskService_UpdateTaskResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockTaskService_UpdateTaskResult_Call) Return(_a0 error) *MockTaskService_UpdateTaskResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_UpdateTaskResult_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockTaskService_UpdateTaskResult_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskStatus provides a mock function with given fields: ctx, taskID, status, errorMessage
func (_m *MockTaskService) UpdateTaskStatus(ctx context.Context, taskID string, status model.TaskStatus, errorMessage string) error {
	ret := _m.Called(ctx, taskID, status, errorMessage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TaskStatus, string) error); ok {
		r0 = rf(ctx, taskID, status, errorMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_UpdateTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskStatus'
type MockTaskService_UpdateTaskStatus_Call struct {
	*mock.Call
}

// UpdateTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - status model.TaskStatus
//   - errorMessage string
func (_e *MockTaskService_Expecter) UpdateTaskStatus(ctx interface{}, taskID interface{}, status interface{}, errorMessage interface{}) *MockTaskService_UpdateTaskStatus_Call {
	return &MockTaskService_UpdateTaskStatus_Call{Call: _e.mock.On("UpdateTaskStatus", ctx, taskID, status, errorMessage)}
}

func (_c *MockTaskService_UpdateTaskStatus_Call) Run(run func(ctx context.Context, taskID string, status model.TaskStatus, errorMessage string)) *MockTaskService_UpdateTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.TaskStatus), args[3].(string))
	})
	return _c
}

func (_c *MockTaskService_UpdateTaskStatus_Call) Return(_a0 error) *MockTaskService_UpdateTaskStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_UpdateTaskStatus_Call) RunAndReturn(run func(context.Context, string, model.TaskStatus, string) error) *MockTaskService_UpdateTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
