[project]
name = "dehaze-python"
version = "0.1.0"
description = "Add your description here"
requires-python = "===3.11.12"
dependencies = []

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"
