"""
Schema 模型包 - Pydantic 模型定义，用于自动生成 OpenAPI 文档
"""
from app.models.schema.common import (
    BasePageQuery,
    PageResult,
    Option,
    Result,
    IdsPath,
)
from app.models.schema.role import (
    RolePageQuery,
    StatusQuery,
    RoleIdPath,
    RoleIdsPath,
    RoleForm,
    MenuIdsBody,
    RolePageVO,
)
from app.models.schema.user import (
    UserPageQuery,
    UserStatusQuery,
    UserPasswordQuery,
    UserIdPath,
    UserIdsPath,
    LoginForm,
    RegisterForm,
    UserForm,
    PasswordForm,
    LoginVO,
    UserInfoVO,
    UserPageVO,
    UserFormVO,
)
from app.models.schema.menu import (
    MenuQuery,
    MenuVisibleQuery,
    MenuIdPath,
    MenuForm,
    MenuVO,
    RouteVO,
    MenuOptionVO,
)
from app.models.schema.dept import (
    DeptQuery,
    DeptIdPath,
    DeptIdsPath,
    DeptForm,
    DeptVO,
)
from app.models.schema.dict import (
    DictPageQuery,
    DictTypePageQuery,
    DictIdPath,
    DictIdsPath,
    DictTypeIdPath,
    DictTypeIdsPath,
    DictTypeCodePath,
    DictForm,
    DictTypeForm,
    DictPageVO,
    DictTypePageVO,
)
from app.models.schema.dataset import (
    DatasetQuery,
    DatasetImagePageQuery,
    DatasetItemPageQuery,
    DatasetIdPath,
    DatasetIdsQuery,
    DatasetItemIdPath,
    DatasetAddForm,
    DatasetUpdateForm,
    DatasetItemCreateForm,
    DatasetItemUpdateForm,
    DatasetItemDeleteForm,
    DatasetVO,
    DatasetItemVO,
    DatasetOptionVO,
)
from app.models.schema.algorithm import (
    AlgorithmQuery,
    AlgorithmIdPath,
    AlgorithmIdsQuery,
    AlgorithmForm,
    AlgorithmVO,
    AlgorithmOptionVO,
)
from app.models.schema.file import (
    FileIdQuery,
    FileCheckQuery,
    FileUploadForm,
    FileUploadResultVO,
    FileVO,
)
from app.models.schema.task import (
    TaskIdPath,
    ExportOptions,
    ExportTaskCreateForm,
    TaskVO,
)

__all__ = [
    # common
    "BasePageQuery",
    "PageResult",
    "Option",
    "Result",
    "IdsPath",
    # role
    "RolePageQuery",
    "StatusQuery",
    "RoleIdPath",
    "RoleIdsPath",
    "RoleForm",
    "MenuIdsBody",
    "RolePageVO",
    # user
    "UserPageQuery",
    "UserStatusQuery",
    "UserPasswordQuery",
    "UserIdPath",
    "UserIdsPath",
    "LoginForm",
    "RegisterForm",
    "UserForm",
    "PasswordForm",
    "LoginVO",
    "UserInfoVO",
    "UserPageVO",
    "UserFormVO",
    # menu
    "MenuQuery",
    "MenuVisibleQuery",
    "MenuIdPath",
    "MenuForm",
    "MenuVO",
    "RouteVO",
    "MenuOptionVO",
    # dept
    "DeptQuery",
    "DeptIdPath",
    "DeptIdsPath",
    "DeptForm",
    "DeptVO",
    # dict
    "DictPageQuery",
    "DictTypePageQuery",
    "DictIdPath",
    "DictIdsPath",
    "DictTypeIdPath",
    "DictTypeIdsPath",
    "DictTypeCodePath",
    "DictForm",
    "DictTypeForm",
    "DictPageVO",
    "DictTypePageVO",
    # dataset
    "DatasetQuery",
    "DatasetImagePageQuery",
    "DatasetItemPageQuery",
    "DatasetIdPath",
    "DatasetIdsQuery",
    "DatasetItemIdPath",
    "DatasetAddForm",
    "DatasetUpdateForm",
    "DatasetItemCreateForm",
    "DatasetItemUpdateForm",
    "DatasetItemDeleteForm",
    "DatasetVO",
    "DatasetItemVO",
    "DatasetOptionVO",
    # algorithm
    "AlgorithmQuery",
    "AlgorithmIdPath",
    "AlgorithmIdsQuery",
    "AlgorithmForm",
    "AlgorithmVO",
    "AlgorithmOptionVO",
    # file
    "FileIdQuery",
    "FileCheckQuery",
    "FileUploadForm",
    "FileUploadResultVO",
    "FileVO",
    # task
    "TaskIdPath",
    "ExportOptions",
    "ExportTaskCreateForm",
    "TaskVO",
]
