"""
Schema 模型包 - Pydantic 模型定义，用于自动生成 OpenAPI 文档
"""
from app.models.schema.algorithm import (AlgorithmForm, AlgorithmIdPath,
                                         AlgorithmIdsQuery, AlgorithmMonitorVO,
                                         AlgorithmOptionVO, AlgorithmQuery,
                                         AlgorithmVO)
from app.models.schema.common import BasePageQuery, IdsPath, Option, PageResult
from app.models.schema.dataset import (DatasetAddForm, DatasetDeleteResultItemVO,
                                       DatasetDeleteResultVO, DatasetIdVO,
                                       DatasetItemCreateForm,
                                       DatasetItemIdVO,
                                       DatasetItemPageVO,
                                       DatasetItemUpdateForm, DatasetItemVO,
                                       DatasetOptionVO, DatasetQuery,
                                       DatasetUpdateForm, DatasetVO)
from app.models.schema.dept import (DeptForm, DeptFormVO, DeptIdPath,
                                    DeptIdsPath, DeptOptionVO, DeptQuery,
                                    DeptVO)
from app.models.schema.dict import (DictForm, DictFormVO, DictIdPath,
                                    DictIdsPath, DictOptionVO, DictPageQuery,
                                    DictPageVO, DictTypeCodePath, DictTypeForm,
                                    DictTypeFormVO, DictTypeIdPath,
                                    DictTypeIdsPath, DictTypePageQuery,
                                    DictTypePageVO)
from app.models.schema.file import (FileCheckQuery, FileIdQuery,
                                    FileUploadForm, FileUploadResultVO, FileVO)
from app.models.schema.menu import (MenuForm, MenuFormVO, MenuIdPath,
                                    MenuOptionVO, MenuQuery,
                                    MenuVO, RouteVO)
from app.models.schema.role import (MenuIdsBody, RoleForm, RoleFormVO,
                                    RoleIdPath, RoleIdsPath, RoleOptionVO,
                                    RolePageQuery, RolePageVO, StatusQuery)
from app.models.schema.task import (ExportOptions, ExportTaskCreateForm,
                                    TaskIdPath, TaskVO)
from app.models.schema.user import (CaptchaData, CurrentUserVO, LoginData,
                                    LoginForm, PasswordForm,
                                    RegisterForm, UserCreateVO, UserDeleteVO,
                                    UserForm, UserFormVO, UserIdPath,
                                    UserIdsPath, UserImportVO, UserInfoVO,
                                    UserPageQuery, UserPageVO,
                                    UserStatusQuery)

__all__ = [
    # common
    "BasePageQuery",
    "PageResult",
    "Option",
    "IdsPath",
    # role
    "RolePageQuery",
    "StatusQuery",
    "RoleIdPath",
    "RoleIdsPath",
    "RoleForm",
    "MenuIdsBody",
    "RolePageVO",
    "RoleOptionVO",
    "RoleFormVO",
    # user
    "UserPageQuery",
    "UserStatusQuery",
    "UserIdPath",
    "UserIdsPath",
    "LoginForm",
    "RegisterForm",
    "UserForm",
    "PasswordForm",
    "UserInfoVO",
    "UserPageVO",
    "UserFormVO",
    "CurrentUserVO",
    "UserCreateVO",
    "UserImportVO",
    "UserDeleteVO",
    # menu
    "MenuQuery",
    "MenuIdPath",
    "MenuForm",
    "MenuVO",
    "RouteVO",
    "MenuOptionVO",
    "MenuFormVO",
    # dept
    "DeptQuery",
    "DeptIdPath",
    "DeptIdsPath",
    "DeptForm",
    "DeptVO",
    "DeptOptionVO",
    "DeptFormVO",
    # dict
    "DictPageQuery",
    "DictTypePageQuery",
    "DictIdPath",
    "DictIdsPath",
    "DictTypeIdPath",
    "DictTypeIdsPath",
    "DictTypeCodePath",
    "DictForm",
    "DictFormVO",
    "DictTypeForm",
    "DictTypeFormVO",
    "DictPageVO",
    "DictTypePageVO",
    "DictOptionVO",
    # dataset
    "DatasetQuery",
    "DatasetAddForm",
    "DatasetUpdateForm",
    "DatasetDeleteResultItemVO",
    "DatasetDeleteResultVO",
    "DatasetIdVO",
    "DatasetItemCreateForm",
    "DatasetItemUpdateForm",
    "DatasetItemIdVO",
    "DatasetItemPageVO",
    "DatasetItemVO",
    "DatasetVO",
    "DatasetOptionVO",
    # algorithm
    "AlgorithmQuery",
    "AlgorithmIdPath",
    "AlgorithmIdsQuery",
    "AlgorithmForm",
    "AlgorithmVO",
    "AlgorithmOptionVO",
    "AlgorithmMonitorVO",
    # file
    "FileIdQuery",
    "FileCheckQuery",
    "FileUploadForm",
    "FileUploadResultVO",
    "FileVO",
    # task
    "TaskIdPath",
    "ExportOptions",
    "ExportTaskCreateForm",
    "TaskVO",
]
