// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dataset "github.com/earthyzinc/dehaze-go/internal/repository/dataset"
	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"
)

// MockIDatasetRepository is an autogenerated mock type for the IDatasetRepository type
type MockIDatasetRepository struct {
	mock.Mock
}

type MockIDatasetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatasetRepository) EXPECT() *MockIDatasetRepository_Expecter {
	return &MockIDatasetRepository_Expecter{mock: &_m.Mock}
}

// CountHasChildren provides a mock function with given fields: ctx, parentIDs
func (_m *MockIDatasetRepository) CountHasChildren(ctx context.Context, parentIDs []int64) (map[int64]bool, error) {
	ret := _m.Called(ctx, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountHasChildren")
	}

	var r0 map[int64]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]bool, error)); ok {
		return rf(ctx, parentIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]bool); ok {
		r0 = rf(ctx, parentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, parentIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_CountHasChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountHasChildren'
type MockIDatasetRepository_CountHasChildren_Call struct {
	*mock.Call
}

// CountHasChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []int64
func (_e *MockIDatasetRepository_Expecter) CountHasChildren(ctx interface{}, parentIDs interface{}) *MockIDatasetRepository_CountHasChildren_Call {
	return &MockIDatasetRepository_CountHasChildren_Call{Call: _e.mock.On("CountHasChildren", ctx, parentIDs)}
}

func (_c *MockIDatasetRepository_CountHasChildren_Call) Run(run func(ctx context.Context, parentIDs []int64)) *MockIDatasetRepository_CountHasChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_CountHasChildren_Call) Return(_a0 map[int64]bool, _a1 error) *MockIDatasetRepository_CountHasChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_CountHasChildren_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]bool, error)) *MockIDatasetRepository_CountHasChildren_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasetRepository) Create(ctx context.Context, _a1 *model.SysDataset) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDataset) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDatasetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDataset
func (_e *MockIDatasetRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIDatasetRepository_Create_Call {
	return &MockIDatasetRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIDatasetRepository_Create_Call) Run(run func(ctx context.Context, _a1 *model.SysDataset)) *MockIDatasetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDataset))
	})
	return _c
}

func (_c *MockIDatasetRepository_Create_Call) Return(_a0 error) *MockIDatasetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysDataset) error) *MockIDatasetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function with given fields: ctx, id
func (_m *MockIDatasetRepository) ExistsByID(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockIDatasetRepository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDatasetRepository_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockIDatasetRepository_ExistsByID_Call {
	return &MockIDatasetRepository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockIDatasetRepository_ExistsByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDatasetRepository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_ExistsByID_Call) Return(_a0 bool, _a1 error) *MockIDatasetRepository_ExistsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_ExistsByID_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *MockIDatasetRepository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByParentIDAndName provides a mock function with given fields: ctx, parentID, name, excludeID
func (_m *MockIDatasetRepository) ExistsByParentIDAndName(ctx context.Context, parentID int64, name string, excludeID int64) (bool, error) {
	ret := _m.Called(ctx, parentID, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByParentIDAndName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (bool, error)); ok {
		return rf(ctx, parentID, name, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) bool); ok {
		r0 = rf(ctx, parentID, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, parentID, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_ExistsByParentIDAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByParentIDAndName'
type MockIDatasetRepository_ExistsByParentIDAndName_Call struct {
	*mock.Call
}

// ExistsByParentIDAndName is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - name string
//   - excludeID int64
func (_e *MockIDatasetRepository_Expecter) ExistsByParentIDAndName(ctx interface{}, parentID interface{}, name interface{}, excludeID interface{}) *MockIDatasetRepository_ExistsByParentIDAndName_Call {
	return &MockIDatasetRepository_ExistsByParentIDAndName_Call{Call: _e.mock.On("ExistsByParentIDAndName", ctx, parentID, name, excludeID)}
}

func (_c *MockIDatasetRepository_ExistsByParentIDAndName_Call) Run(run func(ctx context.Context, parentID int64, name string, excludeID int64)) *MockIDatasetRepository_ExistsByParentIDAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_ExistsByParentIDAndName_Call) Return(_a0 bool, _a1 error) *MockIDatasetRepository_ExistsByParentIDAndName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_ExistsByParentIDAndName_Call) RunAndReturn(run func(context.Context, int64, string, int64) (bool, error)) *MockIDatasetRepository_ExistsByParentIDAndName_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockIDatasetRepository) FindAll(ctx context.Context) ([]model.SysDataset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SysDataset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SysDataset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIDatasetRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDatasetRepository_Expecter) FindAll(ctx interface{}) *MockIDatasetRepository_FindAll_Call {
	return &MockIDatasetRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIDatasetRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindAll_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]model.SysDataset, error)) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function with given fields: ctx
func (_m *MockIDatasetRepository) FindAllActive(ctx context.Context) ([]model.SysDataset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SysDataset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SysDataset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockIDatasetRepository_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDatasetRepository_Expecter) FindAllActive(ctx interface{}) *MockIDatasetRepository_FindAllActive_Call {
	return &MockIDatasetRepository_FindAllActive_Call{Call: _e.mock.On("FindAllActive", ctx)}
}

func (_c *MockIDatasetRepository_FindAllActive_Call) Run(run func(ctx context.Context)) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindAllActive_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindAllActive_Call) RunAndReturn(run func(context.Context) ([]model.SysDataset, error)) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIDatasetRepository) FindByID(ctx context.Context, id int64) (*model.SysDataset, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDataset, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDataset); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIDatasetRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDatasetRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIDatasetRepository_FindByID_Call {
	return &MockIDatasetRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIDatasetRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindByID_Call) Return(_a0 *model.SysDataset, _a1 error) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDataset, error)) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParentID provides a mock function with given fields: ctx, parentID
func (_m *MockIDatasetRepository) FindByParentID(ctx context.Context, parentID int64) ([]model.SysDataset, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParentID")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.SysDataset, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.SysDataset); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindByParentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParentID'
type MockIDatasetRepository_FindByParentID_Call struct {
	*mock.Call
}

// FindByParentID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *MockIDatasetRepository_Expecter) FindByParentID(ctx interface{}, parentID interface{}) *MockIDatasetRepository_FindByParentID_Call {
	return &MockIDatasetRepository_FindByParentID_Call{Call: _e.mock.On("FindByParentID", ctx, parentID)}
}

func (_c *MockIDatasetRepository_FindByParentID_Call) Run(run func(ctx context.Context, parentID int64)) *MockIDatasetRepository_FindByParentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindByParentID_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindByParentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindByParentID_Call) RunAndReturn(run func(context.Context, int64) ([]model.SysDataset, error)) *MockIDatasetRepository_FindByParentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParentIDs provides a mock function with given fields: ctx, parentIDs
func (_m *MockIDatasetRepository) FindByParentIDs(ctx context.Context, parentIDs []int64) ([]model.SysDataset, error) {
	ret := _m.Called(ctx, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByParentIDs")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]model.SysDataset, error)); ok {
		return rf(ctx, parentIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []model.SysDataset); ok {
		r0 = rf(ctx, parentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, parentIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindByParentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParentIDs'
type MockIDatasetRepository_FindByParentIDs_Call struct {
	*mock.Call
}

// FindByParentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []int64
func (_e *MockIDatasetRepository_Expecter) FindByParentIDs(ctx interface{}, parentIDs interface{}) *MockIDatasetRepository_FindByParentIDs_Call {
	return &MockIDatasetRepository_FindByParentIDs_Call{Call: _e.mock.On("FindByParentIDs", ctx, parentIDs)}
}

func (_c *MockIDatasetRepository_FindByParentIDs_Call) Run(run func(ctx context.Context, parentIDs []int64)) *MockIDatasetRepository_FindByParentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindByParentIDs_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindByParentIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindByParentIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]model.SysDataset, error)) *MockIDatasetRepository_FindByParentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindRootPage provides a mock function with given fields: ctx, q
func (_m *MockIDatasetRepository) FindRootPage(ctx context.Context, q *query.DatasetQuery) ([]model.SysDataset, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindRootPage")
	}

	var r0 []model.SysDataset
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DatasetQuery) ([]model.SysDataset, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DatasetQuery) []model.SysDataset); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DatasetQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.DatasetQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIDatasetRepository_FindRootPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRootPage'
type MockIDatasetRepository_FindRootPage_Call struct {
	*mock.Call
}

// FindRootPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DatasetQuery
func (_e *MockIDatasetRepository_Expecter) FindRootPage(ctx interface{}, q interface{}) *MockIDatasetRepository_FindRootPage_Call {
	return &MockIDatasetRepository_FindRootPage_Call{Call: _e.mock.On("FindRootPage", ctx, q)}
}

func (_c *MockIDatasetRepository_FindRootPage_Call) Run(run func(ctx context.Context, q *query.DatasetQuery)) *MockIDatasetRepository_FindRootPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DatasetQuery))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindRootPage_Call) Return(_a0 []model.SysDataset, _a1 int64, _a2 error) *MockIDatasetRepository_FindRootPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIDatasetRepository_FindRootPage_Call) RunAndReturn(run func(context.Context, *query.DatasetQuery) ([]model.SysDataset, int64, error)) *MockIDatasetRepository_FindRootPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, datasetID
func (_m *MockIDatasetRepository) GetFormData(ctx context.Context, datasetID int64) (*model.SysDataset, error) {
	ret := _m.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDataset, error)); ok {
		return rf(ctx, datasetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDataset); ok {
		r0 = rf(ctx, datasetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, datasetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIDatasetRepository_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID int64
func (_e *MockIDatasetRepository_Expecter) GetFormData(ctx interface{}, datasetID interface{}) *MockIDatasetRepository_GetFormData_Call {
	return &MockIDatasetRepository_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, datasetID)}
}

func (_c *MockIDatasetRepository_GetFormData_Call) Run(run func(ctx context.Context, datasetID int64)) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_GetFormData_Call) Return(_a0 *model.SysDataset, _a1 error) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDataset, error)) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByIDs provides a mock function with given fields: ctx, ids, updateBy
func (_m *MockIDatasetRepository) SoftDeleteByIDs(ctx context.Context, ids []int64, updateBy int64) error {
	ret := _m.Called(ctx, ids, updateBy)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, int64) error); ok {
		r0 = rf(ctx, ids, updateBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_SoftDeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByIDs'
type MockIDatasetRepository_SoftDeleteByIDs_Call struct {
	*mock.Call
}

// SoftDeleteByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - updateBy int64
func (_e *MockIDatasetRepository_Expecter) SoftDeleteByIDs(ctx interface{}, ids interface{}, updateBy interface{}) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	return &MockIDatasetRepository_SoftDeleteByIDs_Call{Call: _e.mock.On("SoftDeleteByIDs", ctx, ids, updateBy)}
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) Run(run func(ctx context.Context, ids []int64, updateBy int64)) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) Return(_a0 error) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) RunAndReturn(run func(context.Context, []int64, int64) error) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockIDatasetRepository) Transaction(ctx context.Context, fn func(dataset.IDatasetRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(dataset.IDatasetRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockIDatasetRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(dataset.IDatasetRepository) error
func (_e *MockIDatasetRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockIDatasetRepository_Transaction_Call {
	return &MockIDatasetRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockIDatasetRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(dataset.IDatasetRepository) error)) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(dataset.IDatasetRepository) error))
	})
	return _c
}

func (_c *MockIDatasetRepository_Transaction_Call) Return(_a0 error) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(dataset.IDatasetRepository) error) error) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasetRepository) Update(ctx context.Context, _a1 *model.SysDataset) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDataset) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDatasetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDataset
func (_e *MockIDatasetRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockIDatasetRepository_Update_Call {
	return &MockIDatasetRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockIDatasetRepository_Update_Call) Run(run func(ctx context.Context, _a1 *model.SysDataset)) *MockIDatasetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDataset))
	})
	return _c
}

func (_c *MockIDatasetRepository_Update_Call) Return(_a0 error) *MockIDatasetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysDataset) error) *MockIDatasetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatasetRepository creates a new instance of MockIDatasetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatasetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatasetRepository {
	mock := &MockIDatasetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
