// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/earthyzinc/dehaze-go/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIAlgorithmFavoriteRepository is an autogenerated mock type for the IAlgorithmFavoriteRepository type
type MockIAlgorithmFavoriteRepository struct {
	mock.Mock
}

type MockIAlgorithmFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAlgorithmFavoriteRepository) EXPECT() *MockIAlgorithmFavoriteRepository_Expecter {
	return &MockIAlgorithmFavoriteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, favorite
func (_m *MockIAlgorithmFavoriteRepository) Create(ctx context.Context, favorite *model.SysAlgorithmFavorite) error {
	ret := _m.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysAlgorithmFavorite) error); ok {
		r0 = rf(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmFavoriteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAlgorithmFavoriteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *model.SysAlgorithmFavorite
func (_e *MockIAlgorithmFavoriteRepository_Expecter) Create(ctx interface{}, favorite interface{}) *MockIAlgorithmFavoriteRepository_Create_Call {
	return &MockIAlgorithmFavoriteRepository_Create_Call{Call: _e.mock.On("Create", ctx, favorite)}
}

func (_c *MockIAlgorithmFavoriteRepository_Create_Call) Run(run func(ctx context.Context, favorite *model.SysAlgorithmFavorite)) *MockIAlgorithmFavoriteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysAlgorithmFavorite))
	})
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_Create_Call) Return(_a0 error) *MockIAlgorithmFavoriteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysAlgorithmFavorite) error) *MockIAlgorithmFavoriteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, algorithmID
func (_m *MockIAlgorithmFavoriteRepository) Delete(ctx context.Context, userID int64, algorithmID int64) error {
	ret := _m.Called(ctx, userID, algorithmID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, algorithmID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmFavoriteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAlgorithmFavoriteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - algorithmID int64
func (_e *MockIAlgorithmFavoriteRepository_Expecter) Delete(ctx interface{}, userID interface{}, algorithmID interface{}) *MockIAlgorithmFavoriteRepository_Delete_Call {
	return &MockIAlgorithmFavoriteRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, algorithmID)}
}

func (_c *MockIAlgorithmFavoriteRepository_Delete_Call) Run(run func(ctx context.Context, userID int64, algorithmID int64)) *MockIAlgorithmFavoriteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_Delete_Call) Return(_a0 error) *MockIAlgorithmFavoriteRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_Delete_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockIAlgorithmFavoriteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndAlgorithm provides a mock function with given fields: ctx, userID, algorithmID
func (_m *MockIAlgorithmFavoriteRepository) FindByUserAndAlgorithm(ctx context.Context, userID int64, algorithmID int64) (*model.SysAlgorithmFavorite, error) {
	ret := _m.Called(ctx, userID, algorithmID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndAlgorithm")
	}

	var r0 *model.SysAlgorithmFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*model.SysAlgorithmFavorite, error)); ok {
		return rf(ctx, userID, algorithmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *model.SysAlgorithmFavorite); ok {
		r0 = rf(ctx, userID, algorithmID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysAlgorithmFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, algorithmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndAlgorithm'
type MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call struct {
	*mock.Call
}

// FindByUserAndAlgorithm is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - algorithmID int64
func (_e *MockIAlgorithmFavoriteRepository_Expecter) FindByUserAndAlgorithm(ctx interface{}, userID interface{}, algorithmID interface{}) *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call {
	return &MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call{Call: _e.mock.On("FindByUserAndAlgorithm", ctx, userID, algorithmID)}
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call) Run(run func(ctx context.Context, userID int64, algorithmID int64)) *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call) Return(_a0 *model.SysAlgorithmFavorite, _a1 error) *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call) RunAndReturn(run func(context.Context, int64, int64) (*model.SysAlgorithmFavorite, error)) *MockIAlgorithmFavoriteRepository_FindByUserAndAlgorithm_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIAlgorithmFavoriteRepository) FindByUserID(ctx context.Context, userID int64) ([]model.SysAlgorithmFavorite, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.SysAlgorithmFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.SysAlgorithmFavorite, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.SysAlgorithmFavorite); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysAlgorithmFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmFavoriteRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockIAlgorithmFavoriteRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIAlgorithmFavoriteRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockIAlgorithmFavoriteRepository_FindByUserID_Call {
	return &MockIAlgorithmFavoriteRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockIAlgorithmFavoriteRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserID_Call) Return(_a0 []model.SysAlgorithmFavorite, _a1 error) *MockIAlgorithmFavoriteRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]model.SysAlgorithmFavorite, error)) *MockIAlgorithmFavoriteRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorited provides a mock function with given fields: ctx, userID, algorithmID
func (_m *MockIAlgorithmFavoriteRepository) IsFavorited(ctx context.Context, userID int64, algorithmID int64) (bool, error) {
	ret := _m.Called(ctx, userID, algorithmID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorited")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, userID, algorithmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, userID, algorithmID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, algorithmID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmFavoriteRepository_IsFavorited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorited'
type MockIAlgorithmFavoriteRepository_IsFavorited_Call struct {
	*mock.Call
}

// IsFavorited is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - algorithmID int64
func (_e *MockIAlgorithmFavoriteRepository_Expecter) IsFavorited(ctx interface{}, userID interface{}, algorithmID interface{}) *MockIAlgorithmFavoriteRepository_IsFavorited_Call {
	return &MockIAlgorithmFavoriteRepository_IsFavorited_Call{Call: _e.mock.On("IsFavorited", ctx, userID, algorithmID)}
}

func (_c *MockIAlgorithmFavoriteRepository_IsFavorited_Call) Run(run func(ctx context.Context, userID int64, algorithmID int64)) *MockIAlgorithmFavoriteRepository_IsFavorited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_IsFavorited_Call) Return(_a0 bool, _a1 error) *MockIAlgorithmFavoriteRepository_IsFavorited_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmFavoriteRepository_IsFavorited_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *MockIAlgorithmFavoriteRepository_IsFavorited_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAlgorithmFavoriteRepository creates a new instance of MockIAlgorithmFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAlgorithmFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAlgorithmFavoriteRepository {
	mock := &MockIAlgorithmFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
