// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/earthyzinc/dehaze-go/internal/model"
	mock "github.com/stretchr/testify/mock"

	order "github.com/earthyzinc/dehaze-go/internal/repository/order"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"
)

// MockIRefundRecordRepository is an autogenerated mock type for the IRefundRecordRepository type
type MockIRefundRecordRepository struct {
	mock.Mock
}

type MockIRefundRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefundRecordRepository) EXPECT() *MockIRefundRecordRepository_Expecter {
	return &MockIRefundRecordRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rr
func (_m *MockIRefundRecordRepository) Create(ctx context.Context, rr *model.SysRefundRecord) error {
	ret := _m.Called(ctx, rr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysRefundRecord) error); ok {
		r0 = rf(ctx, rr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRefundRecordRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRefundRecordRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rr *model.SysRefundRecord
func (_e *MockIRefundRecordRepository_Expecter) Create(ctx interface{}, rr interface{}) *MockIRefundRecordRepository_Create_Call {
	return &MockIRefundRecordRepository_Create_Call{Call: _e.mock.On("Create", ctx, rr)}
}

func (_c *MockIRefundRecordRepository_Create_Call) Run(run func(ctx context.Context, rr *model.SysRefundRecord)) *MockIRefundRecordRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysRefundRecord))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_Create_Call) Return(_a0 error) *MockIRefundRecordRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundRecordRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysRefundRecord) error) *MockIRefundRecordRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIRefundRecordRepository) FindByID(ctx context.Context, id int64) (*model.SysRefundRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysRefundRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysRefundRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysRefundRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysRefundRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRecordRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIRefundRecordRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIRefundRecordRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIRefundRecordRepository_FindByID_Call {
	return &MockIRefundRecordRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIRefundRecordRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIRefundRecordRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_FindByID_Call) Return(_a0 *model.SysRefundRecord, _a1 error) *MockIRefundRecordRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRecordRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysRefundRecord, error)) *MockIRefundRecordRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockIRefundRecordRepository) FindByOrderID(ctx context.Context, orderID int64) (*model.SysRefundRecord, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *model.SysRefundRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysRefundRecord, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysRefundRecord); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysRefundRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRecordRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockIRefundRecordRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID int64
func (_e *MockIRefundRecordRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockIRefundRecordRepository_FindByOrderID_Call {
	return &MockIRefundRecordRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockIRefundRecordRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID int64)) *MockIRefundRecordRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_FindByOrderID_Call) Return(_a0 *model.SysRefundRecord, _a1 error) *MockIRefundRecordRepository_FindByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRecordRepository_FindByOrderID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysRefundRecord, error)) *MockIRefundRecordRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindFailedRetryable provides a mock function with given fields: ctx, maxRetryCount
func (_m *MockIRefundRecordRepository) FindFailedRetryable(ctx context.Context, maxRetryCount int) ([]model.SysRefundRecord, error) {
	ret := _m.Called(ctx, maxRetryCount)

	if len(ret) == 0 {
		panic("no return value specified for FindFailedRetryable")
	}

	var r0 []model.SysRefundRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.SysRefundRecord, error)); ok {
		return rf(ctx, maxRetryCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.SysRefundRecord); ok {
		r0 = rf(ctx, maxRetryCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysRefundRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, maxRetryCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRecordRepository_FindFailedRetryable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFailedRetryable'
type MockIRefundRecordRepository_FindFailedRetryable_Call struct {
	*mock.Call
}

// FindFailedRetryable is a helper method to define mock.On call
//   - ctx context.Context
//   - maxRetryCount int
func (_e *MockIRefundRecordRepository_Expecter) FindFailedRetryable(ctx interface{}, maxRetryCount interface{}) *MockIRefundRecordRepository_FindFailedRetryable_Call {
	return &MockIRefundRecordRepository_FindFailedRetryable_Call{Call: _e.mock.On("FindFailedRetryable", ctx, maxRetryCount)}
}

func (_c *MockIRefundRecordRepository_FindFailedRetryable_Call) Run(run func(ctx context.Context, maxRetryCount int)) *MockIRefundRecordRepository_FindFailedRetryable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_FindFailedRetryable_Call) Return(_a0 []model.SysRefundRecord, _a1 error) *MockIRefundRecordRepository_FindFailedRetryable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRecordRepository_FindFailedRetryable_Call) RunAndReturn(run func(context.Context, int) ([]model.SysRefundRecord, error)) *MockIRefundRecordRepository_FindFailedRetryable_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIRefundRecordRepository) FindPage(ctx context.Context, q *query.RefundPageQuery) ([]order.RefundWithOrder, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []order.RefundWithOrder
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.RefundPageQuery) ([]order.RefundWithOrder, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.RefundPageQuery) []order.RefundWithOrder); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.RefundWithOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.RefundPageQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.RefundPageQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRefundRecordRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIRefundRecordRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.RefundPageQuery
func (_e *MockIRefundRecordRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIRefundRecordRepository_FindPage_Call {
	return &MockIRefundRecordRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIRefundRecordRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.RefundPageQuery)) *MockIRefundRecordRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.RefundPageQuery))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_FindPage_Call) Return(_a0 []order.RefundWithOrder, _a1 int64, _a2 error) *MockIRefundRecordRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRefundRecordRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.RefundPageQuery) ([]order.RefundWithOrder, int64, error)) *MockIRefundRecordRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updates
func (_m *MockIRefundRecordRepository) Update(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRefundRecordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRefundRecordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (_e *MockIRefundRecordRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockIRefundRecordRepository_Update_Call {
	return &MockIRefundRecordRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockIRefundRecordRepository_Update_Call) Run(run func(ctx context.Context, id int64, updates map[string]interface{})) *MockIRefundRecordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIRefundRecordRepository_Update_Call) Return(_a0 error) *MockIRefundRecordRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundRecordRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIRefundRecordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRefundRecordRepository creates a new instance of MockIRefundRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefundRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefundRecordRepository {
	mock := &MockIRefundRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
