// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bo "github.com/earthyzinc/dehaze-go/internal/model/bo"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	read "github.com/earthyzinc/dehaze-go/internal/model/read"
)

// MockIDeptRepository is an autogenerated mock type for the IDeptRepository type
type MockIDeptRepository struct {
	mock.Mock
}

type MockIDeptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDeptRepository) EXPECT() *MockIDeptRepository_Expecter {
	return &MockIDeptRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIDeptRepository) Create(ctx context.Context, _a1 *model.SysDept) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDept) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDeptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDeptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDept
func (_e *MockIDeptRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIDeptRepository_Create_Call {
	return &MockIDeptRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIDeptRepository_Create_Call) Run(run func(ctx context.Context, _a1 *model.SysDept)) *MockIDeptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDept))
	})
	return _c
}

func (_c *MockIDeptRepository_Create_Call) Return(_a0 error) *MockIDeptRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDeptRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysDept) error) *MockIDeptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDeptRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDeptRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDeptRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDeptRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDeptRepository_Delete_Call {
	return &MockIDeptRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDeptRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDeptRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDeptRepository_Delete_Call) Return(_a0 error) *MockIDeptRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDeptRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDeptRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, q
func (_m *MockIDeptRepository) FindAll(ctx context.Context, q *query.DeptQuery) ([]model.SysDept, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.SysDept
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DeptQuery) ([]model.SysDept, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DeptQuery) []model.SysDept); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDept)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DeptQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIDeptRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DeptQuery
func (_e *MockIDeptRepository_Expecter) FindAll(ctx interface{}, q interface{}) *MockIDeptRepository_FindAll_Call {
	return &MockIDeptRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, q)}
}

func (_c *MockIDeptRepository_FindAll_Call) Run(run func(ctx context.Context, q *query.DeptQuery)) *MockIDeptRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DeptQuery))
	})
	return _c
}

func (_c *MockIDeptRepository_FindAll_Call) Return(_a0 []model.SysDept, _a1 error) *MockIDeptRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_FindAll_Call) RunAndReturn(run func(context.Context, *query.DeptQuery) ([]model.SysDept, error)) *MockIDeptRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIDeptRepository) FindByID(ctx context.Context, id int64) (*model.SysDept, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysDept
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDept, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDept); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDept)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIDeptRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDeptRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIDeptRepository_FindByID_Call {
	return &MockIDeptRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIDeptRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDeptRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_FindByID_Call) Return(_a0 *model.SysDept, _a1 error) *MockIDeptRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDept, error)) *MockIDeptRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParentID provides a mock function with given fields: ctx, parentID
func (_m *MockIDeptRepository) FindByParentID(ctx context.Context, parentID int64) ([]model.SysDept, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParentID")
	}

	var r0 []model.SysDept
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.SysDept, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.SysDept); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDept)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_FindByParentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParentID'
type MockIDeptRepository_FindByParentID_Call struct {
	*mock.Call
}

// FindByParentID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *MockIDeptRepository_Expecter) FindByParentID(ctx interface{}, parentID interface{}) *MockIDeptRepository_FindByParentID_Call {
	return &MockIDeptRepository_FindByParentID_Call{Call: _e.mock.On("FindByParentID", ctx, parentID)}
}

func (_c *MockIDeptRepository_FindByParentID_Call) Run(run func(ctx context.Context, parentID int64)) *MockIDeptRepository_FindByParentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_FindByParentID_Call) Return(_a0 []model.SysDept, _a1 error) *MockIDeptRepository_FindByParentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_FindByParentID_Call) RunAndReturn(run func(context.Context, int64) ([]model.SysDept, error)) *MockIDeptRepository_FindByParentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindIDByName provides a mock function with given fields: ctx, name
func (_m *MockIDeptRepository) FindIDByName(ctx context.Context, name string) (int64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindIDByName")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_FindIDByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDByName'
type MockIDeptRepository_FindIDByName_Call struct {
	*mock.Call
}

// FindIDByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockIDeptRepository_Expecter) FindIDByName(ctx interface{}, name interface{}) *MockIDeptRepository_FindIDByName_Call {
	return &MockIDeptRepository_FindIDByName_Call{Call: _e.mock.On("FindIDByName", ctx, name)}
}

func (_c *MockIDeptRepository_FindIDByName_Call) Run(run func(ctx context.Context, name string)) *MockIDeptRepository_FindIDByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIDeptRepository_FindIDByName_Call) Return(_a0 int64, _a1 error) *MockIDeptRepository_FindIDByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_FindIDByName_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockIDeptRepository_FindIDByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindIDsByNames provides a mock function with given fields: ctx, names
func (_m *MockIDeptRepository) FindIDsByNames(ctx context.Context, names []string) (map[string]int64, error) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for FindIDsByNames")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_FindIDsByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDsByNames'
type MockIDeptRepository_FindIDsByNames_Call struct {
	*mock.Call
}

// FindIDsByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *MockIDeptRepository_Expecter) FindIDsByNames(ctx interface{}, names interface{}) *MockIDeptRepository_FindIDsByNames_Call {
	return &MockIDeptRepository_FindIDsByNames_Call{Call: _e.mock.On("FindIDsByNames", ctx, names)}
}

func (_c *MockIDeptRepository_FindIDsByNames_Call) Run(run func(ctx context.Context, names []string)) *MockIDeptRepository_FindIDsByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIDeptRepository_FindIDsByNames_Call) Return(_a0 map[string]int64, _a1 error) *MockIDeptRepository_FindIDsByNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_FindIDsByNames_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockIDeptRepository_FindIDsByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, deptID
func (_m *MockIDeptRepository) GetFormData(ctx context.Context, deptID int64) (*bo.DeptFormBO, error) {
	ret := _m.Called(ctx, deptID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *bo.DeptFormBO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*bo.DeptFormBO, error)); ok {
		return rf(ctx, deptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *bo.DeptFormBO); ok {
		r0 = rf(ctx, deptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.DeptFormBO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIDeptRepository_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - deptID int64
func (_e *MockIDeptRepository_Expecter) GetFormData(ctx interface{}, deptID interface{}) *MockIDeptRepository_GetFormData_Call {
	return &MockIDeptRepository_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, deptID)}
}

func (_c *MockIDeptRepository_GetFormData_Call) Run(run func(ctx context.Context, deptID int64)) *MockIDeptRepository_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_GetFormData_Call) Return(_a0 *bo.DeptFormBO, _a1 error) *MockIDeptRepository_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*bo.DeptFormBO, error)) *MockIDeptRepository_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// GetOptions provides a mock function with given fields: ctx
func (_m *MockIDeptRepository) GetOptions(ctx context.Context) ([]read.Option, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOptions")
	}

	var r0 []read.Option
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]read.Option, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []read.Option); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]read.Option)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_GetOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOptions'
type MockIDeptRepository_GetOptions_Call struct {
	*mock.Call
}

// GetOptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDeptRepository_Expecter) GetOptions(ctx interface{}) *MockIDeptRepository_GetOptions_Call {
	return &MockIDeptRepository_GetOptions_Call{Call: _e.mock.On("GetOptions", ctx)}
}

func (_c *MockIDeptRepository_GetOptions_Call) Run(run func(ctx context.Context)) *MockIDeptRepository_GetOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDeptRepository_GetOptions_Call) Return(_a0 []read.Option, _a1 error) *MockIDeptRepository_GetOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_GetOptions_Call) RunAndReturn(run func(context.Context) ([]read.Option, error)) *MockIDeptRepository_GetOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubDeptIDs provides a mock function with given fields: ctx, deptID
func (_m *MockIDeptRepository) GetSubDeptIDs(ctx context.Context, deptID int64) ([]int64, error) {
	ret := _m.Called(ctx, deptID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubDeptIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, deptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, deptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_GetSubDeptIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubDeptIDs'
type MockIDeptRepository_GetSubDeptIDs_Call struct {
	*mock.Call
}

// GetSubDeptIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - deptID int64
func (_e *MockIDeptRepository_Expecter) GetSubDeptIDs(ctx interface{}, deptID interface{}) *MockIDeptRepository_GetSubDeptIDs_Call {
	return &MockIDeptRepository_GetSubDeptIDs_Call{Call: _e.mock.On("GetSubDeptIDs", ctx, deptID)}
}

func (_c *MockIDeptRepository_GetSubDeptIDs_Call) Run(run func(ctx context.Context, deptID int64)) *MockIDeptRepository_GetSubDeptIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_GetSubDeptIDs_Call) Return(_a0 []int64, _a1 error) *MockIDeptRepository_GetSubDeptIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_GetSubDeptIDs_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *MockIDeptRepository_GetSubDeptIDs_Call {
	_c.Call.Return(run)
	return _c
}

// HasChildren provides a mock function with given fields: ctx, id
func (_m *MockIDeptRepository) HasChildren(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HasChildren")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_HasChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChildren'
type MockIDeptRepository_HasChildren_Call struct {
	*mock.Call
}

// HasChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDeptRepository_Expecter) HasChildren(ctx interface{}, id interface{}) *MockIDeptRepository_HasChildren_Call {
	return &MockIDeptRepository_HasChildren_Call{Call: _e.mock.On("HasChildren", ctx, id)}
}

func (_c *MockIDeptRepository_HasChildren_Call) Run(run func(ctx context.Context, id int64)) *MockIDeptRepository_HasChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_HasChildren_Call) Return(_a0 bool, _a1 error) *MockIDeptRepository_HasChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_HasChildren_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *MockIDeptRepository_HasChildren_Call {
	_c.Call.Return(run)
	return _c
}

// HasUsers provides a mock function with given fields: ctx, deptID
func (_m *MockIDeptRepository) HasUsers(ctx context.Context, deptID int64) (bool, error) {
	ret := _m.Called(ctx, deptID)

	if len(ret) == 0 {
		panic("no return value specified for HasUsers")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, deptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, deptID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, deptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_HasUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUsers'
type MockIDeptRepository_HasUsers_Call struct {
	*mock.Call
}

// HasUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - deptID int64
func (_e *MockIDeptRepository_Expecter) HasUsers(ctx interface{}, deptID interface{}) *MockIDeptRepository_HasUsers_Call {
	return &MockIDeptRepository_HasUsers_Call{Call: _e.mock.On("HasUsers", ctx, deptID)}
}

func (_c *MockIDeptRepository_HasUsers_Call) Run(run func(ctx context.Context, deptID int64)) *MockIDeptRepository_HasUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDeptRepository_HasUsers_Call) Return(_a0 bool, _a1 error) *MockIDeptRepository_HasUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_HasUsers_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *MockIDeptRepository_HasUsers_Call {
	_c.Call.Return(run)
	return _c
}

// HasUsersInBatch provides a mock function with given fields: ctx, deptIDs
func (_m *MockIDeptRepository) HasUsersInBatch(ctx context.Context, deptIDs []int64) (map[int64]bool, error) {
	ret := _m.Called(ctx, deptIDs)

	if len(ret) == 0 {
		panic("no return value specified for HasUsersInBatch")
	}

	var r0 map[int64]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]bool, error)); ok {
		return rf(ctx, deptIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]bool); ok {
		r0 = rf(ctx, deptIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, deptIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDeptRepository_HasUsersInBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUsersInBatch'
type MockIDeptRepository_HasUsersInBatch_Call struct {
	*mock.Call
}

// HasUsersInBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - deptIDs []int64
func (_e *MockIDeptRepository_Expecter) HasUsersInBatch(ctx interface{}, deptIDs interface{}) *MockIDeptRepository_HasUsersInBatch_Call {
	return &MockIDeptRepository_HasUsersInBatch_Call{Call: _e.mock.On("HasUsersInBatch", ctx, deptIDs)}
}

func (_c *MockIDeptRepository_HasUsersInBatch_Call) Run(run func(ctx context.Context, deptIDs []int64)) *MockIDeptRepository_HasUsersInBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDeptRepository_HasUsersInBatch_Call) Return(_a0 map[int64]bool, _a1 error) *MockIDeptRepository_HasUsersInBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDeptRepository_HasUsersInBatch_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]bool, error)) *MockIDeptRepository_HasUsersInBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockIDeptRepository) Update(ctx context.Context, _a1 *model.SysDept) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDept) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDeptRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDeptRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDept
func (_e *MockIDeptRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockIDeptRepository_Update_Call {
	return &MockIDeptRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockIDeptRepository_Update_Call) Run(run func(ctx context.Context, _a1 *model.SysDept)) *MockIDeptRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDept))
	})
	return _c
}

func (_c *MockIDeptRepository_Update_Call) Return(_a0 error) *MockIDeptRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDeptRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysDept) error) *MockIDeptRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDeptRepository creates a new instance of MockIDeptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDeptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDeptRepository {
	mock := &MockIDeptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
