// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/earthyzinc/dehaze-go/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIApiKeyRepository is an autogenerated mock type for the IApiKeyRepository type
type MockIApiKeyRepository struct {
	mock.Mock
}

type MockIApiKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIApiKeyRepository) EXPECT() *MockIApiKeyRepository_Expecter {
	return &MockIApiKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, key
func (_m *MockIApiKeyRepository) Create(ctx context.Context, key *model.SysApiKey) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysApiKey) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIApiKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIApiKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key *model.SysApiKey
func (_e *MockIApiKeyRepository_Expecter) Create(ctx interface{}, key interface{}) *MockIApiKeyRepository_Create_Call {
	return &MockIApiKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, key)}
}

func (_c *MockIApiKeyRepository_Create_Call) Run(run func(ctx context.Context, key *model.SysApiKey)) *MockIApiKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysApiKey))
	})
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) Return(_a0 error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysApiKey) error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function with given fields: ctx, keyHash
func (_m *MockIApiKeyRepository) FindByHash(ctx context.Context, keyHash string) (*model.SysApiKey, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *model.SysApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysApiKey, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysApiKey); ok {
		r0 = rf(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIApiKeyRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockIApiKeyRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockIApiKeyRepository_Expecter) FindByHash(ctx interface{}, keyHash interface{}) *MockIApiKeyRepository_FindByHash_Call {
	return &MockIApiKeyRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, keyHash)}
}

func (_c *MockIApiKeyRepository_FindByHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockIApiKeyRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIApiKeyRepository_FindByHash_Call) Return(_a0 *model.SysApiKey, _a1 error) *MockIApiKeyRepository_FindByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIApiKeyRepository_FindByHash_Call) RunAndReturn(run func(context.Context, string) (*model.SysApiKey, error)) *MockIApiKeyRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIApiKeyRepository) FindByUserID(ctx context.Context, userID int64) ([]model.SysApiKey, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.SysApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.SysApiKey, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.SysApiKey); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIApiKeyRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockIApiKeyRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIApiKeyRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockIApiKeyRepository_FindByUserID_Call {
	return &MockIApiKeyRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockIApiKeyRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockIApiKeyRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIApiKeyRepository_FindByUserID_Call) Return(_a0 []model.SysApiKey, _a1 error) *MockIApiKeyRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIApiKeyRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]model.SysApiKey, error)) *MockIApiKeyRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id, userID
func (_m *MockIApiKeyRepository) RevokeByID(ctx context.Context, id int64, userID int64) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIApiKeyRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockIApiKeyRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockIApiKeyRepository_Expecter) RevokeByID(ctx interface{}, id interface{}, userID interface{}) *MockIApiKeyRepository_RevokeByID_Call {
	return &MockIApiKeyRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id, userID)}
}

func (_c *MockIApiKeyRepository_RevokeByID_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockIApiKeyRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIApiKeyRepository_RevokeByID_Call) Return(_a0 error) *MockIApiKeyRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIApiKeyRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockIApiKeyRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUsed provides a mock function with given fields: ctx, id
func (_m *MockIApiKeyRepository) UpdateLastUsed(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIApiKeyRepository_UpdateLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUsed'
type MockIApiKeyRepository_UpdateLastUsed_Call struct {
	*mock.Call
}

// UpdateLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIApiKeyRepository_Expecter) UpdateLastUsed(ctx interface{}, id interface{}) *MockIApiKeyRepository_UpdateLastUsed_Call {
	return &MockIApiKeyRepository_UpdateLastUsed_Call{Call: _e.mock.On("UpdateLastUsed", ctx, id)}
}

func (_c *MockIApiKeyRepository_UpdateLastUsed_Call) Run(run func(ctx context.Context, id int64)) *MockIApiKeyRepository_UpdateLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIApiKeyRepository_UpdateLastUsed_Call) Return(_a0 error) *MockIApiKeyRepository_UpdateLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIApiKeyRepository_UpdateLastUsed_Call) RunAndReturn(run func(context.Context, int64) error) *MockIApiKeyRepository_UpdateLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIApiKeyRepository creates a new instance of MockIApiKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIApiKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIApiKeyRepository {
	mock := &MockIApiKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
