// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"
)

// MockIMemberGrowthLogRepository is an autogenerated mock type for the IMemberGrowthLogRepository type
type MockIMemberGrowthLogRepository struct {
	mock.Mock
}

type MockIMemberGrowthLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMemberGrowthLogRepository) EXPECT() *MockIMemberGrowthLogRepository_Expecter {
	return &MockIMemberGrowthLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockIMemberGrowthLogRepository) Create(ctx context.Context, log *model.SysMemberGrowthLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysMemberGrowthLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMemberGrowthLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIMemberGrowthLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *model.SysMemberGrowthLog
func (_e *MockIMemberGrowthLogRepository_Expecter) Create(ctx interface{}, log interface{}) *MockIMemberGrowthLogRepository_Create_Call {
	return &MockIMemberGrowthLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockIMemberGrowthLogRepository_Create_Call) Run(run func(ctx context.Context, log *model.SysMemberGrowthLog)) *MockIMemberGrowthLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysMemberGrowthLog))
	})
	return _c
}

func (_c *MockIMemberGrowthLogRepository_Create_Call) Return(_a0 error) *MockIMemberGrowthLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMemberGrowthLogRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysMemberGrowthLog) error) *MockIMemberGrowthLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindPageByUserID provides a mock function with given fields: ctx, userID, q
func (_m *MockIMemberGrowthLogRepository) FindPageByUserID(ctx context.Context, userID int64, q *query.GrowthLogQuery) ([]model.SysMemberGrowthLog, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPageByUserID")
	}

	var r0 []model.SysMemberGrowthLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.GrowthLogQuery) ([]model.SysMemberGrowthLog, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.GrowthLogQuery) []model.SysMemberGrowthLog); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMemberGrowthLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *query.GrowthLogQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *query.GrowthLogQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMemberGrowthLogRepository_FindPageByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPageByUserID'
type MockIMemberGrowthLogRepository_FindPageByUserID_Call struct {
	*mock.Call
}

// FindPageByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - q *query.GrowthLogQuery
func (_e *MockIMemberGrowthLogRepository_Expecter) FindPageByUserID(ctx interface{}, userID interface{}, q interface{}) *MockIMemberGrowthLogRepository_FindPageByUserID_Call {
	return &MockIMemberGrowthLogRepository_FindPageByUserID_Call{Call: _e.mock.On("FindPageByUserID", ctx, userID, q)}
}

func (_c *MockIMemberGrowthLogRepository_FindPageByUserID_Call) Run(run func(ctx context.Context, userID int64, q *query.GrowthLogQuery)) *MockIMemberGrowthLogRepository_FindPageByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*query.GrowthLogQuery))
	})
	return _c
}

func (_c *MockIMemberGrowthLogRepository_FindPageByUserID_Call) Return(_a0 []model.SysMemberGrowthLog, _a1 int64, _a2 error) *MockIMemberGrowthLogRepository_FindPageByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMemberGrowthLogRepository_FindPageByUserID_Call) RunAndReturn(run func(context.Context, int64, *query.GrowthLogQuery) ([]model.SysMemberGrowthLog, int64, error)) *MockIMemberGrowthLogRepository_FindPageByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMemberGrowthLogRepository creates a new instance of MockIMemberGrowthLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMemberGrowthLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMemberGrowthLogRepository {
	mock := &MockIMemberGrowthLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
