// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/earthyzinc/dehaze-go/internal/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	read "github.com/earthyzinc/dehaze-go/internal/model/read"
)

// MockIAlgorithmRepository is an autogenerated mock type for the IAlgorithmRepository type
type MockIAlgorithmRepository struct {
	mock.Mock
}

type MockIAlgorithmRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAlgorithmRepository) EXPECT() *MockIAlgorithmRepository_Expecter {
	return &MockIAlgorithmRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIAlgorithmRepository) Create(ctx context.Context, _a1 *model.SysAlgorithm) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysAlgorithm) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAlgorithmRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysAlgorithm
func (_e *MockIAlgorithmRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIAlgorithmRepository_Create_Call {
	return &MockIAlgorithmRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIAlgorithmRepository_Create_Call) Run(run func(ctx context.Context, _a1 *model.SysAlgorithm)) *MockIAlgorithmRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysAlgorithm))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_Create_Call) Return(_a0 error) *MockIAlgorithmRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysAlgorithm) error) *MockIAlgorithmRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIAlgorithmRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAlgorithmRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIAlgorithmRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIAlgorithmRepository_Delete_Call {
	return &MockIAlgorithmRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIAlgorithmRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIAlgorithmRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_Delete_Call) Return(_a0 error) *MockIAlgorithmRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIAlgorithmRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIAlgorithmRepository) FindByID(ctx context.Context, id int64) (*model.SysAlgorithm, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysAlgorithm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysAlgorithm, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysAlgorithm); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysAlgorithm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAlgorithmRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIAlgorithmRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIAlgorithmRepository_FindByID_Call {
	return &MockIAlgorithmRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAlgorithmRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIAlgorithmRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_FindByID_Call) Return(_a0 *model.SysAlgorithm, _a1 error) *MockIAlgorithmRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysAlgorithm, error)) *MockIAlgorithmRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOptions provides a mock function with given fields: ctx
func (_m *MockIAlgorithmRepository) FindOptions(ctx context.Context) ([]read.Option, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindOptions")
	}

	var r0 []read.Option
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]read.Option, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []read.Option); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]read.Option)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmRepository_FindOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOptions'
type MockIAlgorithmRepository_FindOptions_Call struct {
	*mock.Call
}

// FindOptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAlgorithmRepository_Expecter) FindOptions(ctx interface{}) *MockIAlgorithmRepository_FindOptions_Call {
	return &MockIAlgorithmRepository_FindOptions_Call{Call: _e.mock.On("FindOptions", ctx)}
}

func (_c *MockIAlgorithmRepository_FindOptions_Call) Run(run func(ctx context.Context)) *MockIAlgorithmRepository_FindOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_FindOptions_Call) Return(_a0 []read.Option, _a1 error) *MockIAlgorithmRepository_FindOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmRepository_FindOptions_Call) RunAndReturn(run func(context.Context) ([]read.Option, error)) *MockIAlgorithmRepository_FindOptions_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIAlgorithmRepository) FindPage(ctx context.Context, q *query.AlgorithmQuery) (*read.PageResult[read.Algorithm], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 *read.PageResult[read.Algorithm]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.AlgorithmQuery) (*read.PageResult[read.Algorithm], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.AlgorithmQuery) *read.PageResult[read.Algorithm]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*read.PageResult[read.Algorithm])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.AlgorithmQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIAlgorithmRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.AlgorithmQuery
func (_e *MockIAlgorithmRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIAlgorithmRepository_FindPage_Call {
	return &MockIAlgorithmRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIAlgorithmRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.AlgorithmQuery)) *MockIAlgorithmRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.AlgorithmQuery))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_FindPage_Call) Return(_a0 *read.PageResult[read.Algorithm], _a1 error) *MockIAlgorithmRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.AlgorithmQuery) (*read.PageResult[read.Algorithm], error)) *MockIAlgorithmRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// HasChildrenByParentIDs provides a mock function with given fields: ctx, parentIDs
func (_m *MockIAlgorithmRepository) HasChildrenByParentIDs(ctx context.Context, parentIDs []int64) (bool, error) {
	ret := _m.Called(ctx, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for HasChildrenByParentIDs")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (bool, error)); ok {
		return rf(ctx, parentIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) bool); ok {
		r0 = rf(ctx, parentIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, parentIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAlgorithmRepository_HasChildrenByParentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChildrenByParentIDs'
type MockIAlgorithmRepository_HasChildrenByParentIDs_Call struct {
	*mock.Call
}

// HasChildrenByParentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - parentIDs []int64
func (_e *MockIAlgorithmRepository_Expecter) HasChildrenByParentIDs(ctx interface{}, parentIDs interface{}) *MockIAlgorithmRepository_HasChildrenByParentIDs_Call {
	return &MockIAlgorithmRepository_HasChildrenByParentIDs_Call{Call: _e.mock.On("HasChildrenByParentIDs", ctx, parentIDs)}
}

func (_c *MockIAlgorithmRepository_HasChildrenByParentIDs_Call) Run(run func(ctx context.Context, parentIDs []int64)) *MockIAlgorithmRepository_HasChildrenByParentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_HasChildrenByParentIDs_Call) Return(_a0 bool, _a1 error) *MockIAlgorithmRepository_HasChildrenByParentIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAlgorithmRepository_HasChildrenByParentIDs_Call) RunAndReturn(run func(context.Context, []int64) (bool, error)) *MockIAlgorithmRepository_HasChildrenByParentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockIAlgorithmRepository) Update(ctx context.Context, _a1 *model.SysAlgorithm) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysAlgorithm) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAlgorithmRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysAlgorithm
func (_e *MockIAlgorithmRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockIAlgorithmRepository_Update_Call {
	return &MockIAlgorithmRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockIAlgorithmRepository_Update_Call) Run(run func(ctx context.Context, _a1 *model.SysAlgorithm)) *MockIAlgorithmRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysAlgorithm))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_Update_Call) Return(_a0 error) *MockIAlgorithmRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysAlgorithm) error) *MockIAlgorithmRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockIAlgorithmRepository) UpdateStatus(ctx context.Context, id int64, status int8) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int8) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAlgorithmRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIAlgorithmRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status int8
func (_e *MockIAlgorithmRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockIAlgorithmRepository_UpdateStatus_Call {
	return &MockIAlgorithmRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockIAlgorithmRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status int8)) *MockIAlgorithmRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int8))
	})
	return _c
}

func (_c *MockIAlgorithmRepository_UpdateStatus_Call) Return(_a0 error) *MockIAlgorithmRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAlgorithmRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, int8) error) *MockIAlgorithmRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAlgorithmRepository creates a new instance of MockIAlgorithmRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAlgorithmRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAlgorithmRepository {
	mock := &MockIAlgorithmRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
