// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"
)

// MockIDatasetItemRepository is an autogenerated mock type for the IDatasetItemRepository type
type MockIDatasetItemRepository struct {
	mock.Mock
}

type MockIDatasetItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatasetItemRepository) EXPECT() *MockIDatasetItemRepository_Expecter {
	return &MockIDatasetItemRepository_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function with given fields: ctx, items
func (_m *MockIDatasetItemRepository) BatchCreate(ctx context.Context, items []model.SysDatasetItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.SysDatasetItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type MockIDatasetItemRepository_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - items []model.SysDatasetItem
func (_e *MockIDatasetItemRepository_Expecter) BatchCreate(ctx interface{}, items interface{}) *MockIDatasetItemRepository_BatchCreate_Call {
	return &MockIDatasetItemRepository_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, items)}
}

func (_c *MockIDatasetItemRepository_BatchCreate_Call) Run(run func(ctx context.Context, items []model.SysDatasetItem)) *MockIDatasetItemRepository_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.SysDatasetItem))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_BatchCreate_Call) Return(_a0 error) *MockIDatasetItemRepository_BatchCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_BatchCreate_Call) RunAndReturn(run func(context.Context, []model.SysDatasetItem) error) *MockIDatasetItemRepository_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CountByDatasetIDs provides a mock function with given fields: ctx, datasetIDs
func (_m *MockIDatasetItemRepository) CountByDatasetIDs(ctx context.Context, datasetIDs []int64) (int64, error) {
	ret := _m.Called(ctx, datasetIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountByDatasetIDs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (int64, error)); ok {
		return rf(ctx, datasetIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) int64); ok {
		r0 = rf(ctx, datasetIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, datasetIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetItemRepository_CountByDatasetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByDatasetIDs'
type MockIDatasetItemRepository_CountByDatasetIDs_Call struct {
	*mock.Call
}

// CountByDatasetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetIDs []int64
func (_e *MockIDatasetItemRepository_Expecter) CountByDatasetIDs(ctx interface{}, datasetIDs interface{}) *MockIDatasetItemRepository_CountByDatasetIDs_Call {
	return &MockIDatasetItemRepository_CountByDatasetIDs_Call{Call: _e.mock.On("CountByDatasetIDs", ctx, datasetIDs)}
}

func (_c *MockIDatasetItemRepository_CountByDatasetIDs_Call) Run(run func(ctx context.Context, datasetIDs []int64)) *MockIDatasetItemRepository_CountByDatasetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_CountByDatasetIDs_Call) Return(_a0 int64, _a1 error) *MockIDatasetItemRepository_CountByDatasetIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetItemRepository_CountByDatasetIDs_Call) RunAndReturn(run func(context.Context, []int64) (int64, error)) *MockIDatasetItemRepository_CountByDatasetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockIDatasetItemRepository) Create(ctx context.Context, item *model.SysDatasetItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDatasetItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDatasetItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.SysDatasetItem
func (_e *MockIDatasetItemRepository_Expecter) Create(ctx interface{}, item interface{}) *MockIDatasetItemRepository_Create_Call {
	return &MockIDatasetItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockIDatasetItemRepository_Create_Call) Run(run func(ctx context.Context, item *model.SysDatasetItem)) *MockIDatasetItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDatasetItem))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_Create_Call) Return(_a0 error) *MockIDatasetItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysDatasetItem) error) *MockIDatasetItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDatasetItemRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDatasetItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDatasetItemRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDatasetItemRepository_Delete_Call {
	return &MockIDatasetItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDatasetItemRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDatasetItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_Delete_Call) Return(_a0 error) *MockIDatasetItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDatasetItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByDatasetID provides a mock function with given fields: ctx, datasetID
func (_m *MockIDatasetItemRepository) DeleteByDatasetID(ctx context.Context, datasetID int64) error {
	ret := _m.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDatasetID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, datasetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_DeleteByDatasetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByDatasetID'
type MockIDatasetItemRepository_DeleteByDatasetID_Call struct {
	*mock.Call
}

// DeleteByDatasetID is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID int64
func (_e *MockIDatasetItemRepository_Expecter) DeleteByDatasetID(ctx interface{}, datasetID interface{}) *MockIDatasetItemRepository_DeleteByDatasetID_Call {
	return &MockIDatasetItemRepository_DeleteByDatasetID_Call{Call: _e.mock.On("DeleteByDatasetID", ctx, datasetID)}
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetID_Call) Run(run func(ctx context.Context, datasetID int64)) *MockIDatasetItemRepository_DeleteByDatasetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetID_Call) Return(_a0 error) *MockIDatasetItemRepository_DeleteByDatasetID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetID_Call) RunAndReturn(run func(context.Context, int64) error) *MockIDatasetItemRepository_DeleteByDatasetID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByDatasetIDs provides a mock function with given fields: ctx, datasetIDs
func (_m *MockIDatasetItemRepository) DeleteByDatasetIDs(ctx context.Context, datasetIDs []int64) error {
	ret := _m.Called(ctx, datasetIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDatasetIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, datasetIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_DeleteByDatasetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByDatasetIDs'
type MockIDatasetItemRepository_DeleteByDatasetIDs_Call struct {
	*mock.Call
}

// DeleteByDatasetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetIDs []int64
func (_e *MockIDatasetItemRepository_Expecter) DeleteByDatasetIDs(ctx interface{}, datasetIDs interface{}) *MockIDatasetItemRepository_DeleteByDatasetIDs_Call {
	return &MockIDatasetItemRepository_DeleteByDatasetIDs_Call{Call: _e.mock.On("DeleteByDatasetIDs", ctx, datasetIDs)}
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetIDs_Call) Run(run func(ctx context.Context, datasetIDs []int64)) *MockIDatasetItemRepository_DeleteByDatasetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetIDs_Call) Return(_a0 error) *MockIDatasetItemRepository_DeleteByDatasetIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_DeleteByDatasetIDs_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDatasetItemRepository_DeleteByDatasetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDatasetID provides a mock function with given fields: ctx, datasetID
func (_m *MockIDatasetItemRepository) FindByDatasetID(ctx context.Context, datasetID int64) ([]model.SysDatasetItem, error) {
	ret := _m.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for FindByDatasetID")
	}

	var r0 []model.SysDatasetItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.SysDatasetItem, error)); ok {
		return rf(ctx, datasetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.SysDatasetItem); ok {
		r0 = rf(ctx, datasetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDatasetItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, datasetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetItemRepository_FindByDatasetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDatasetID'
type MockIDatasetItemRepository_FindByDatasetID_Call struct {
	*mock.Call
}

// FindByDatasetID is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID int64
func (_e *MockIDatasetItemRepository_Expecter) FindByDatasetID(ctx interface{}, datasetID interface{}) *MockIDatasetItemRepository_FindByDatasetID_Call {
	return &MockIDatasetItemRepository_FindByDatasetID_Call{Call: _e.mock.On("FindByDatasetID", ctx, datasetID)}
}

func (_c *MockIDatasetItemRepository_FindByDatasetID_Call) Run(run func(ctx context.Context, datasetID int64)) *MockIDatasetItemRepository_FindByDatasetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_FindByDatasetID_Call) Return(_a0 []model.SysDatasetItem, _a1 error) *MockIDatasetItemRepository_FindByDatasetID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetItemRepository_FindByDatasetID_Call) RunAndReturn(run func(context.Context, int64) ([]model.SysDatasetItem, error)) *MockIDatasetItemRepository_FindByDatasetID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDatasetIDs provides a mock function with given fields: ctx, datasetIDs
func (_m *MockIDatasetItemRepository) FindByDatasetIDs(ctx context.Context, datasetIDs []int64) ([]model.SysDatasetItem, error) {
	ret := _m.Called(ctx, datasetIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByDatasetIDs")
	}

	var r0 []model.SysDatasetItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]model.SysDatasetItem, error)); ok {
		return rf(ctx, datasetIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []model.SysDatasetItem); ok {
		r0 = rf(ctx, datasetIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDatasetItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, datasetIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetItemRepository_FindByDatasetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDatasetIDs'
type MockIDatasetItemRepository_FindByDatasetIDs_Call struct {
	*mock.Call
}

// FindByDatasetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetIDs []int64
func (_e *MockIDatasetItemRepository_Expecter) FindByDatasetIDs(ctx interface{}, datasetIDs interface{}) *MockIDatasetItemRepository_FindByDatasetIDs_Call {
	return &MockIDatasetItemRepository_FindByDatasetIDs_Call{Call: _e.mock.On("FindByDatasetIDs", ctx, datasetIDs)}
}

func (_c *MockIDatasetItemRepository_FindByDatasetIDs_Call) Run(run func(ctx context.Context, datasetIDs []int64)) *MockIDatasetItemRepository_FindByDatasetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_FindByDatasetIDs_Call) Return(_a0 []model.SysDatasetItem, _a1 error) *MockIDatasetItemRepository_FindByDatasetIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetItemRepository_FindByDatasetIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]model.SysDatasetItem, error)) *MockIDatasetItemRepository_FindByDatasetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIDatasetItemRepository) FindByID(ctx context.Context, id int64) (*model.SysDatasetItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysDatasetItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDatasetItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDatasetItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDatasetItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetItemRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIDatasetItemRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDatasetItemRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIDatasetItemRepository_FindByID_Call {
	return &MockIDatasetItemRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIDatasetItemRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDatasetItemRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_FindByID_Call) Return(_a0 *model.SysDatasetItem, _a1 error) *MockIDatasetItemRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetItemRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDatasetItem, error)) *MockIDatasetItemRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindIDsByDatasetIDs provides a mock function with given fields: ctx, datasetIDs
func (_m *MockIDatasetItemRepository) FindIDsByDatasetIDs(ctx context.Context, datasetIDs []int64) ([]int64, error) {
	ret := _m.Called(ctx, datasetIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindIDsByDatasetIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]int64, error)); ok {
		return rf(ctx, datasetIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []int64); ok {
		r0 = rf(ctx, datasetIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, datasetIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetItemRepository_FindIDsByDatasetIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDsByDatasetIDs'
type MockIDatasetItemRepository_FindIDsByDatasetIDs_Call struct {
	*mock.Call
}

// FindIDsByDatasetIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetIDs []int64
func (_e *MockIDatasetItemRepository_Expecter) FindIDsByDatasetIDs(ctx interface{}, datasetIDs interface{}) *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call {
	return &MockIDatasetItemRepository_FindIDsByDatasetIDs_Call{Call: _e.mock.On("FindIDsByDatasetIDs", ctx, datasetIDs)}
}

func (_c *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call) Run(run func(ctx context.Context, datasetIDs []int64)) *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call) Return(_a0 []int64, _a1 error) *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]int64, error)) *MockIDatasetItemRepository_FindIDsByDatasetIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, datasetID, pageNum, pageSize
func (_m *MockIDatasetItemRepository) FindPage(ctx context.Context, datasetID int64, pageNum int, pageSize int) ([]model.SysDatasetItem, int64, error) {
	ret := _m.Called(ctx, datasetID, pageNum, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []model.SysDatasetItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]model.SysDatasetItem, int64, error)); ok {
		return rf(ctx, datasetID, pageNum, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []model.SysDatasetItem); ok {
		r0 = rf(ctx, datasetID, pageNum, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDatasetItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int64); ok {
		r1 = rf(ctx, datasetID, pageNum, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, datasetID, pageNum, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIDatasetItemRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIDatasetItemRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID int64
//   - pageNum int
//   - pageSize int
func (_e *MockIDatasetItemRepository_Expecter) FindPage(ctx interface{}, datasetID interface{}, pageNum interface{}, pageSize interface{}) *MockIDatasetItemRepository_FindPage_Call {
	return &MockIDatasetItemRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, datasetID, pageNum, pageSize)}
}

func (_c *MockIDatasetItemRepository_FindPage_Call) Run(run func(ctx context.Context, datasetID int64, pageNum int, pageSize int)) *MockIDatasetItemRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_FindPage_Call) Return(_a0 []model.SysDatasetItem, _a1 int64, _a2 error) *MockIDatasetItemRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIDatasetItemRepository_FindPage_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]model.SysDatasetItem, int64, error)) *MockIDatasetItemRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, item
func (_m *MockIDatasetItemRepository) Update(ctx context.Context, item *model.SysDatasetItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDatasetItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDatasetItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.SysDatasetItem
func (_e *MockIDatasetItemRepository_Expecter) Update(ctx interface{}, item interface{}) *MockIDatasetItemRepository_Update_Call {
	return &MockIDatasetItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockIDatasetItemRepository_Update_Call) Run(run func(ctx context.Context, item *model.SysDatasetItem)) *MockIDatasetItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDatasetItem))
	})
	return _c
}

func (_c *MockIDatasetItemRepository_Update_Call) Return(_a0 error) *MockIDatasetItemRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetItemRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysDatasetItem) error) *MockIDatasetItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatasetItemRepository creates a new instance of MockIDatasetItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatasetItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatasetItemRepository {
	mock := &MockIDatasetItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
