// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"
)

// MockIMemberBenefitRepository is an autogenerated mock type for the IMemberBenefitRepository type
type MockIMemberBenefitRepository struct {
	mock.Mock
}

type MockIMemberBenefitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMemberBenefitRepository) EXPECT() *MockIMemberBenefitRepository_Expecter {
	return &MockIMemberBenefitRepository_Expecter{mock: &_m.Mock}
}

// ExistsByLevelCode provides a mock function with given fields: ctx, levelCode, excludeID
func (_m *MockIMemberBenefitRepository) ExistsByLevelCode(ctx context.Context, levelCode string, excludeID ...int64) (bool, error) {
	_va := make([]interface{}, len(excludeID))
	for _i := range excludeID {
		_va[_i] = excludeID[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, levelCode)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByLevelCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) (bool, error)); ok {
		return rf(ctx, levelCode, excludeID...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) bool); ok {
		r0 = rf(ctx, levelCode, excludeID...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...int64) error); ok {
		r1 = rf(ctx, levelCode, excludeID...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMemberBenefitRepository_ExistsByLevelCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByLevelCode'
type MockIMemberBenefitRepository_ExistsByLevelCode_Call struct {
	*mock.Call
}

// ExistsByLevelCode is a helper method to define mock.On call
//   - ctx context.Context
//   - levelCode string
//   - excludeID ...int64
func (_e *MockIMemberBenefitRepository_Expecter) ExistsByLevelCode(ctx interface{}, levelCode interface{}, excludeID ...interface{}) *MockIMemberBenefitRepository_ExistsByLevelCode_Call {
	return &MockIMemberBenefitRepository_ExistsByLevelCode_Call{Call: _e.mock.On("ExistsByLevelCode",
		append([]interface{}{ctx, levelCode}, excludeID...)...)}
}

func (_c *MockIMemberBenefitRepository_ExistsByLevelCode_Call) Run(run func(ctx context.Context, levelCode string, excludeID ...int64)) *MockIMemberBenefitRepository_ExistsByLevelCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIMemberBenefitRepository_ExistsByLevelCode_Call) Return(_a0 bool, _a1 error) *MockIMemberBenefitRepository_ExistsByLevelCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMemberBenefitRepository_ExistsByLevelCode_Call) RunAndReturn(run func(context.Context, string, ...int64) (bool, error)) *MockIMemberBenefitRepository_ExistsByLevelCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockIMemberBenefitRepository) FindAll(ctx context.Context) ([]model.SysMemberBenefit, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.SysMemberBenefit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SysMemberBenefit, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SysMemberBenefit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMemberBenefit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMemberBenefitRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIMemberBenefitRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIMemberBenefitRepository_Expecter) FindAll(ctx interface{}) *MockIMemberBenefitRepository_FindAll_Call {
	return &MockIMemberBenefitRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIMemberBenefitRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockIMemberBenefitRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIMemberBenefitRepository_FindAll_Call) Return(_a0 []model.SysMemberBenefit, _a1 error) *MockIMemberBenefitRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMemberBenefitRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]model.SysMemberBenefit, error)) *MockIMemberBenefitRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLevelCode provides a mock function with given fields: ctx, levelCode
func (_m *MockIMemberBenefitRepository) FindByLevelCode(ctx context.Context, levelCode string) (*model.SysMemberBenefit, error) {
	ret := _m.Called(ctx, levelCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByLevelCode")
	}

	var r0 *model.SysMemberBenefit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysMemberBenefit, error)); ok {
		return rf(ctx, levelCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysMemberBenefit); ok {
		r0 = rf(ctx, levelCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysMemberBenefit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, levelCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMemberBenefitRepository_FindByLevelCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLevelCode'
type MockIMemberBenefitRepository_FindByLevelCode_Call struct {
	*mock.Call
}

// FindByLevelCode is a helper method to define mock.On call
//   - ctx context.Context
//   - levelCode string
func (_e *MockIMemberBenefitRepository_Expecter) FindByLevelCode(ctx interface{}, levelCode interface{}) *MockIMemberBenefitRepository_FindByLevelCode_Call {
	return &MockIMemberBenefitRepository_FindByLevelCode_Call{Call: _e.mock.On("FindByLevelCode", ctx, levelCode)}
}

func (_c *MockIMemberBenefitRepository_FindByLevelCode_Call) Run(run func(ctx context.Context, levelCode string)) *MockIMemberBenefitRepository_FindByLevelCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIMemberBenefitRepository_FindByLevelCode_Call) Return(_a0 *model.SysMemberBenefit, _a1 error) *MockIMemberBenefitRepository_FindByLevelCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMemberBenefitRepository_FindByLevelCode_Call) RunAndReturn(run func(context.Context, string) (*model.SysMemberBenefit, error)) *MockIMemberBenefitRepository_FindByLevelCode_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, levelCode, updates
func (_m *MockIMemberBenefitRepository) Update(ctx context.Context, levelCode string, updates map[string]interface{}) error {
	ret := _m.Called(ctx, levelCode, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, levelCode, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMemberBenefitRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIMemberBenefitRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - levelCode string
//   - updates map[string]interface{}
func (_e *MockIMemberBenefitRepository_Expecter) Update(ctx interface{}, levelCode interface{}, updates interface{}) *MockIMemberBenefitRepository_Update_Call {
	return &MockIMemberBenefitRepository_Update_Call{Call: _e.mock.On("Update", ctx, levelCode, updates)}
}

func (_c *MockIMemberBenefitRepository_Update_Call) Run(run func(ctx context.Context, levelCode string, updates map[string]interface{})) *MockIMemberBenefitRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIMemberBenefitRepository_Update_Call) Return(_a0 error) *MockIMemberBenefitRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMemberBenefitRepository_Update_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockIMemberBenefitRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMemberBenefitRepository creates a new instance of MockIMemberBenefitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMemberBenefitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMemberBenefitRepository {
	mock := &MockIMemberBenefitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
