// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	time "time"
)

// MockIAnnouncementRepository is an autogenerated mock type for the IAnnouncementRepository type
type MockIAnnouncementRepository struct {
	mock.Mock
}

type MockIAnnouncementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnnouncementRepository) EXPECT() *MockIAnnouncementRepository_Expecter {
	return &MockIAnnouncementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ann
func (_m *MockIAnnouncementRepository) Create(ctx context.Context, ann *model.SysAnnouncement) (int64, error) {
	ret := _m.Called(ctx, ann)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysAnnouncement) (int64, error)); ok {
		return rf(ctx, ann)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysAnnouncement) int64); ok {
		r0 = rf(ctx, ann)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.SysAnnouncement) error); ok {
		r1 = rf(ctx, ann)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnnouncementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAnnouncementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ann *model.SysAnnouncement
func (_e *MockIAnnouncementRepository_Expecter) Create(ctx interface{}, ann interface{}) *MockIAnnouncementRepository_Create_Call {
	return &MockIAnnouncementRepository_Create_Call{Call: _e.mock.On("Create", ctx, ann)}
}

func (_c *MockIAnnouncementRepository_Create_Call) Run(run func(ctx context.Context, ann *model.SysAnnouncement)) *MockIAnnouncementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysAnnouncement))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_Create_Call) Return(_a0 int64, _a1 error) *MockIAnnouncementRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnnouncementRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysAnnouncement) (int64, error)) *MockIAnnouncementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIAnnouncementRepository) FindByID(ctx context.Context, id int64) (*model.SysAnnouncement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysAnnouncement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysAnnouncement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysAnnouncement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysAnnouncement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnnouncementRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAnnouncementRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIAnnouncementRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIAnnouncementRepository_FindByID_Call {
	return &MockIAnnouncementRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAnnouncementRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIAnnouncementRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_FindByID_Call) Return(_a0 *model.SysAnnouncement, _a1 error) *MockIAnnouncementRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnnouncementRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysAnnouncement, error)) *MockIAnnouncementRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIAnnouncementRepository) FindPage(ctx context.Context, q *query.AnnouncementQuery) ([]model.SysAnnouncement, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []model.SysAnnouncement
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.AnnouncementQuery) ([]model.SysAnnouncement, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.AnnouncementQuery) []model.SysAnnouncement); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysAnnouncement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.AnnouncementQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.AnnouncementQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAnnouncementRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIAnnouncementRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.AnnouncementQuery
func (_e *MockIAnnouncementRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIAnnouncementRepository_FindPage_Call {
	return &MockIAnnouncementRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIAnnouncementRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.AnnouncementQuery)) *MockIAnnouncementRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.AnnouncementQuery))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_FindPage_Call) Return(_a0 []model.SysAnnouncement, _a1 int64, _a2 error) *MockIAnnouncementRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAnnouncementRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.AnnouncementQuery) ([]model.SysAnnouncement, int64, error)) *MockIAnnouncementRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingScheduled provides a mock function with given fields: ctx, before
func (_m *MockIAnnouncementRepository) FindPendingScheduled(ctx context.Context, before time.Time) ([]model.SysAnnouncement, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingScheduled")
	}

	var r0 []model.SysAnnouncement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.SysAnnouncement, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []model.SysAnnouncement); ok {
		r0 = rf(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysAnnouncement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnnouncementRepository_FindPendingScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingScheduled'
type MockIAnnouncementRepository_FindPendingScheduled_Call struct {
	*mock.Call
}

// FindPendingScheduled is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockIAnnouncementRepository_Expecter) FindPendingScheduled(ctx interface{}, before interface{}) *MockIAnnouncementRepository_FindPendingScheduled_Call {
	return &MockIAnnouncementRepository_FindPendingScheduled_Call{Call: _e.mock.On("FindPendingScheduled", ctx, before)}
}

func (_c *MockIAnnouncementRepository_FindPendingScheduled_Call) Run(run func(ctx context.Context, before time.Time)) *MockIAnnouncementRepository_FindPendingScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_FindPendingScheduled_Call) Return(_a0 []model.SysAnnouncement, _a1 error) *MockIAnnouncementRepository_FindPendingScheduled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnnouncementRepository_FindPendingScheduled_Call) RunAndReturn(run func(context.Context, time.Time) ([]model.SysAnnouncement, error)) *MockIAnnouncementRepository_FindPendingScheduled_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockIAnnouncementRepository) SoftDelete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAnnouncementRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockIAnnouncementRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIAnnouncementRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockIAnnouncementRepository_SoftDelete_Call {
	return &MockIAnnouncementRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockIAnnouncementRepository_SoftDelete_Call) Run(run func(ctx context.Context, id int64)) *MockIAnnouncementRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_SoftDelete_Call) Return(_a0 error) *MockIAnnouncementRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnnouncementRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, int64) error) *MockIAnnouncementRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updates
func (_m *MockIAnnouncementRepository) Update(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAnnouncementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAnnouncementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (_e *MockIAnnouncementRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockIAnnouncementRepository_Update_Call {
	return &MockIAnnouncementRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockIAnnouncementRepository_Update_Call) Run(run func(ctx context.Context, id int64, updates map[string]interface{})) *MockIAnnouncementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIAnnouncementRepository_Update_Call) Return(_a0 error) *MockIAnnouncementRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnnouncementRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIAnnouncementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAnnouncementRepository creates a new instance of MockIAnnouncementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnnouncementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnnouncementRepository {
	mock := &MockIAnnouncementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
