// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/earthyzinc/dehaze-go/internal/model"
	mock "github.com/stretchr/testify/mock"

	order "github.com/earthyzinc/dehaze-go/internal/repository/order"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	time "time"
)

// MockIOrderRepository is an autogenerated mock type for the IOrderRepository type
type MockIOrderRepository struct {
	mock.Mock
}

type MockIOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrderRepository) EXPECT() *MockIOrderRepository_Expecter {
	return &MockIOrderRepository_Expecter{mock: &_m.Mock}
}

// CountByPayMethod provides a mock function with given fields: ctx, payMethod, startTime, endTime
func (_m *MockIOrderRepository) CountByPayMethod(ctx context.Context, payMethod string, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, payMethod, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CountByPayMethod")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return rf(ctx, payMethod, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = rf(ctx, payMethod, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, payMethod, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_CountByPayMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByPayMethod'
type MockIOrderRepository_CountByPayMethod_Call struct {
	*mock.Call
}

// CountByPayMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - payMethod string
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) CountByPayMethod(ctx interface{}, payMethod interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_CountByPayMethod_Call {
	return &MockIOrderRepository_CountByPayMethod_Call{Call: _e.mock.On("CountByPayMethod", ctx, payMethod, startTime, endTime)}
}

func (_c *MockIOrderRepository_CountByPayMethod_Call) Run(run func(ctx context.Context, payMethod string, startTime string, endTime string)) *MockIOrderRepository_CountByPayMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_CountByPayMethod_Call) Return(_a0 int64, _a1 error) *MockIOrderRepository_CountByPayMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_CountByPayMethod_Call) RunAndReturn(run func(context.Context, string, string, string) (int64, error)) *MockIOrderRepository_CountByPayMethod_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function with given fields: ctx, status, startTime, endTime
func (_m *MockIOrderRepository) CountByStatus(ctx context.Context, status int8, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, status, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int8, string, string) (int64, error)); ok {
		return rf(ctx, status, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int8, string, string) int64); ok {
		r0 = rf(ctx, status, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int8, string, string) error); ok {
		r1 = rf(ctx, status, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockIOrderRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status int8
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) CountByStatus(ctx interface{}, status interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_CountByStatus_Call {
	return &MockIOrderRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status, startTime, endTime)}
}

func (_c *MockIOrderRepository_CountByStatus_Call) Run(run func(ctx context.Context, status int8, startTime string, endTime string)) *MockIOrderRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int8), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_CountByStatus_Call) Return(_a0 int64, _a1 error) *MockIOrderRepository_CountByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_CountByStatus_Call) RunAndReturn(run func(context.Context, int8, string, string) (int64, error)) *MockIOrderRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CountTotalOrders provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIOrderRepository) CountTotalOrders(ctx context.Context, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CountTotalOrders")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_CountTotalOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTotalOrders'
type MockIOrderRepository_CountTotalOrders_Call struct {
	*mock.Call
}

// CountTotalOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) CountTotalOrders(ctx interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_CountTotalOrders_Call {
	return &MockIOrderRepository_CountTotalOrders_Call{Call: _e.mock.On("CountTotalOrders", ctx, startTime, endTime)}
}

func (_c *MockIOrderRepository_CountTotalOrders_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIOrderRepository_CountTotalOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_CountTotalOrders_Call) Return(_a0 int64, _a1 error) *MockIOrderRepository_CountTotalOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_CountTotalOrders_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *MockIOrderRepository_CountTotalOrders_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, o
func (_m *MockIOrderRepository) Create(ctx context.Context, o *model.SysOrder) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysOrder) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o *model.SysOrder
func (_e *MockIOrderRepository_Expecter) Create(ctx interface{}, o interface{}) *MockIOrderRepository_Create_Call {
	return &MockIOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockIOrderRepository_Create_Call) Run(run func(ctx context.Context, o *model.SysOrder)) *MockIOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysOrder))
	})
	return _c
}

func (_c *MockIOrderRepository_Create_Call) Return(_a0 error) *MockIOrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrderRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysOrder) error) *MockIOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIOrderRepository) FindByID(ctx context.Context, id int64) (*model.SysOrder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysOrder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysOrder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIOrderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIOrderRepository_FindByID_Call {
	return &MockIOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIOrderRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIOrderRepository_FindByID_Call) Return(_a0 *model.SysOrder, _a1 error) *MockIOrderRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysOrder, error)) *MockIOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockIOrderRepository) FindByIDs(ctx context.Context, ids []int64) ([]model.SysOrder, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []model.SysOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]model.SysOrder, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []model.SysOrder); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockIOrderRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIOrderRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockIOrderRepository_FindByIDs_Call {
	return &MockIOrderRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockIOrderRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockIOrderRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIOrderRepository_FindByIDs_Call) Return(_a0 []model.SysOrder, _a1 error) *MockIOrderRepository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_FindByIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]model.SysOrder, error)) *MockIOrderRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderNo provides a mock function with given fields: ctx, orderNo
func (_m *MockIOrderRepository) FindByOrderNo(ctx context.Context, orderNo string) (*model.SysOrder, error) {
	ret := _m.Called(ctx, orderNo)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderNo")
	}

	var r0 *model.SysOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysOrder, error)); ok {
		return rf(ctx, orderNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysOrder); ok {
		r0 = rf(ctx, orderNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_FindByOrderNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderNo'
type MockIOrderRepository_FindByOrderNo_Call struct {
	*mock.Call
}

// FindByOrderNo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNo string
func (_e *MockIOrderRepository_Expecter) FindByOrderNo(ctx interface{}, orderNo interface{}) *MockIOrderRepository_FindByOrderNo_Call {
	return &MockIOrderRepository_FindByOrderNo_Call{Call: _e.mock.On("FindByOrderNo", ctx, orderNo)}
}

func (_c *MockIOrderRepository_FindByOrderNo_Call) Run(run func(ctx context.Context, orderNo string)) *MockIOrderRepository_FindByOrderNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_FindByOrderNo_Call) Return(_a0 *model.SysOrder, _a1 error) *MockIOrderRepository_FindByOrderNo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_FindByOrderNo_Call) RunAndReturn(run func(context.Context, string) (*model.SysOrder, error)) *MockIOrderRepository_FindByOrderNo_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIOrderRepository) FindPage(ctx context.Context, q *query.OrderPageQuery) ([]order.OrderWithUser, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []order.OrderWithUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.OrderPageQuery) ([]order.OrderWithUser, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.OrderPageQuery) []order.OrderWithUser); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.OrderWithUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.OrderPageQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.OrderPageQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIOrderRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIOrderRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.OrderPageQuery
func (_e *MockIOrderRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIOrderRepository_FindPage_Call {
	return &MockIOrderRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIOrderRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.OrderPageQuery)) *MockIOrderRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.OrderPageQuery))
	})
	return _c
}

func (_c *MockIOrderRepository_FindPage_Call) Return(_a0 []order.OrderWithUser, _a1 int64, _a2 error) *MockIOrderRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIOrderRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.OrderPageQuery) ([]order.OrderWithUser, int64, error)) *MockIOrderRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// FindPageMyOrders provides a mock function with given fields: ctx, userID, q
func (_m *MockIOrderRepository) FindPageMyOrders(ctx context.Context, userID int64, q *query.MyOrderQuery) ([]order.OrderWithUser, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPageMyOrders")
	}

	var r0 []order.OrderWithUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MyOrderQuery) ([]order.OrderWithUser, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MyOrderQuery) []order.OrderWithUser); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.OrderWithUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *query.MyOrderQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *query.MyOrderQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIOrderRepository_FindPageMyOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPageMyOrders'
type MockIOrderRepository_FindPageMyOrders_Call struct {
	*mock.Call
}

// FindPageMyOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - q *query.MyOrderQuery
func (_e *MockIOrderRepository_Expecter) FindPageMyOrders(ctx interface{}, userID interface{}, q interface{}) *MockIOrderRepository_FindPageMyOrders_Call {
	return &MockIOrderRepository_FindPageMyOrders_Call{Call: _e.mock.On("FindPageMyOrders", ctx, userID, q)}
}

func (_c *MockIOrderRepository_FindPageMyOrders_Call) Run(run func(ctx context.Context, userID int64, q *query.MyOrderQuery)) *MockIOrderRepository_FindPageMyOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*query.MyOrderQuery))
	})
	return _c
}

func (_c *MockIOrderRepository_FindPageMyOrders_Call) Return(_a0 []order.OrderWithUser, _a1 int64, _a2 error) *MockIOrderRepository_FindPageMyOrders_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIOrderRepository_FindPageMyOrders_Call) RunAndReturn(run func(context.Context, int64, *query.MyOrderQuery) ([]order.OrderWithUser, int64, error)) *MockIOrderRepository_FindPageMyOrders_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaidExpired provides a mock function with given fields: ctx, before
func (_m *MockIOrderRepository) FindPaidExpired(ctx context.Context, before time.Time) ([]model.SysOrder, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindPaidExpired")
	}

	var r0 []model.SysOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.SysOrder, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []model.SysOrder); ok {
		r0 = rf(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_FindPaidExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaidExpired'
type MockIOrderRepository_FindPaidExpired_Call struct {
	*mock.Call
}

// FindPaidExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockIOrderRepository_Expecter) FindPaidExpired(ctx interface{}, before interface{}) *MockIOrderRepository_FindPaidExpired_Call {
	return &MockIOrderRepository_FindPaidExpired_Call{Call: _e.mock.On("FindPaidExpired", ctx, before)}
}

func (_c *MockIOrderRepository_FindPaidExpired_Call) Run(run func(ctx context.Context, before time.Time)) *MockIOrderRepository_FindPaidExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIOrderRepository_FindPaidExpired_Call) Return(_a0 []model.SysOrder, _a1 error) *MockIOrderRepository_FindPaidExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_FindPaidExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]model.SysOrder, error)) *MockIOrderRepository_FindPaidExpired_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingExpired provides a mock function with given fields: ctx, before
func (_m *MockIOrderRepository) FindPendingExpired(ctx context.Context, before time.Time) ([]model.SysOrder, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingExpired")
	}

	var r0 []model.SysOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.SysOrder, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []model.SysOrder); ok {
		r0 = rf(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_FindPendingExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingExpired'
type MockIOrderRepository_FindPendingExpired_Call struct {
	*mock.Call
}

// FindPendingExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockIOrderRepository_Expecter) FindPendingExpired(ctx interface{}, before interface{}) *MockIOrderRepository_FindPendingExpired_Call {
	return &MockIOrderRepository_FindPendingExpired_Call{Call: _e.mock.On("FindPendingExpired", ctx, before)}
}

func (_c *MockIOrderRepository_FindPendingExpired_Call) Run(run func(ctx context.Context, before time.Time)) *MockIOrderRepository_FindPendingExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIOrderRepository_FindPendingExpired_Call) Return(_a0 []model.SysOrder, _a1 error) *MockIOrderRepository_FindPendingExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_FindPendingExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]model.SysOrder, error)) *MockIOrderRepository_FindPendingExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyStats provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIOrderRepository) GetDailyStats(ctx context.Context, startTime string, endTime string) ([]order.DailyStatRow, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyStats")
	}

	var r0 []order.DailyStatRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]order.DailyStatRow, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []order.DailyStatRow); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.DailyStatRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_GetDailyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyStats'
type MockIOrderRepository_GetDailyStats_Call struct {
	*mock.Call
}

// GetDailyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) GetDailyStats(ctx interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_GetDailyStats_Call {
	return &MockIOrderRepository_GetDailyStats_Call{Call: _e.mock.On("GetDailyStats", ctx, startTime, endTime)}
}

func (_c *MockIOrderRepository_GetDailyStats_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIOrderRepository_GetDailyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_GetDailyStats_Call) Return(_a0 []order.DailyStatRow, _a1 error) *MockIOrderRepository_GetDailyStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_GetDailyStats_Call) RunAndReturn(run func(context.Context, string, string) ([]order.DailyStatRow, error)) *MockIOrderRepository_GetDailyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageDistribution provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIOrderRepository) GetPackageDistribution(ctx context.Context, startTime string, endTime string) ([]order.PackageStatRow, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageDistribution")
	}

	var r0 []order.PackageStatRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]order.PackageStatRow, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []order.PackageStatRow); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.PackageStatRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_GetPackageDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageDistribution'
type MockIOrderRepository_GetPackageDistribution_Call struct {
	*mock.Call
}

// GetPackageDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) GetPackageDistribution(ctx interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_GetPackageDistribution_Call {
	return &MockIOrderRepository_GetPackageDistribution_Call{Call: _e.mock.On("GetPackageDistribution", ctx, startTime, endTime)}
}

func (_c *MockIOrderRepository_GetPackageDistribution_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIOrderRepository_GetPackageDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_GetPackageDistribution_Call) Return(_a0 []order.PackageStatRow, _a1 error) *MockIOrderRepository_GetPackageDistribution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_GetPackageDistribution_Call) RunAndReturn(run func(context.Context, string, string) ([]order.PackageStatRow, error)) *MockIOrderRepository_GetPackageDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// SumRefund provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIOrderRepository) SumRefund(ctx context.Context, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for SumRefund")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_SumRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumRefund'
type MockIOrderRepository_SumRefund_Call struct {
	*mock.Call
}

// SumRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) SumRefund(ctx interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_SumRefund_Call {
	return &MockIOrderRepository_SumRefund_Call{Call: _e.mock.On("SumRefund", ctx, startTime, endTime)}
}

func (_c *MockIOrderRepository_SumRefund_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIOrderRepository_SumRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_SumRefund_Call) Return(_a0 int64, _a1 error) *MockIOrderRepository_SumRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_SumRefund_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *MockIOrderRepository_SumRefund_Call {
	_c.Call.Return(run)
	return _c
}

// SumRevenue provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIOrderRepository) SumRevenue(ctx context.Context, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for SumRevenue")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrderRepository_SumRevenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumRevenue'
type MockIOrderRepository_SumRevenue_Call struct {
	*mock.Call
}

// SumRevenue is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIOrderRepository_Expecter) SumRevenue(ctx interface{}, startTime interface{}, endTime interface{}) *MockIOrderRepository_SumRevenue_Call {
	return &MockIOrderRepository_SumRevenue_Call{Call: _e.mock.On("SumRevenue", ctx, startTime, endTime)}
}

func (_c *MockIOrderRepository_SumRevenue_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIOrderRepository_SumRevenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrderRepository_SumRevenue_Call) Return(_a0 int64, _a1 error) *MockIOrderRepository_SumRevenue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrderRepository_SumRevenue_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *MockIOrderRepository_SumRevenue_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updates
func (_m *MockIOrderRepository) Update(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (_e *MockIOrderRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockIOrderRepository_Update_Call {
	return &MockIOrderRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockIOrderRepository_Update_Call) Run(run func(ctx context.Context, id int64, updates map[string]interface{})) *MockIOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIOrderRepository_Update_Call) Return(_a0 error) *MockIOrderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrderRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByOrderNo provides a mock function with given fields: ctx, orderNo, updates
func (_m *MockIOrderRepository) UpdateByOrderNo(ctx context.Context, orderNo string, updates map[string]interface{}) error {
	ret := _m.Called(ctx, orderNo, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByOrderNo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, orderNo, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrderRepository_UpdateByOrderNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByOrderNo'
type MockIOrderRepository_UpdateByOrderNo_Call struct {
	*mock.Call
}

// UpdateByOrderNo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNo string
//   - updates map[string]interface{}
func (_e *MockIOrderRepository_Expecter) UpdateByOrderNo(ctx interface{}, orderNo interface{}, updates interface{}) *MockIOrderRepository_UpdateByOrderNo_Call {
	return &MockIOrderRepository_UpdateByOrderNo_Call{Call: _e.mock.On("UpdateByOrderNo", ctx, orderNo, updates)}
}

func (_c *MockIOrderRepository_UpdateByOrderNo_Call) Run(run func(ctx context.Context, orderNo string, updates map[string]interface{})) *MockIOrderRepository_UpdateByOrderNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIOrderRepository_UpdateByOrderNo_Call) Return(_a0 error) *MockIOrderRepository_UpdateByOrderNo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrderRepository_UpdateByOrderNo_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockIOrderRepository_UpdateByOrderNo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOrderRepository creates a new instance of MockIOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrderRepository {
	mock := &MockIOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
