// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	feedback "github.com/earthyzinc/dehaze-go/internal/repository/feedback"
	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	time "time"
)

// MockIRatingRepository is an autogenerated mock type for the IRatingRepository type
type MockIRatingRepository struct {
	mock.Mock
}

type MockIRatingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRatingRepository) EXPECT() *MockIRatingRepository_Expecter {
	return &MockIRatingRepository_Expecter{mock: &_m.Mock}
}

// CountLowRatingsByAlgorithmSince provides a mock function with given fields: ctx, algorithmID, since
func (_m *MockIRatingRepository) CountLowRatingsByAlgorithmSince(ctx context.Context, algorithmID int64, since time.Time) (int64, error) {
	ret := _m.Called(ctx, algorithmID, since)

	if len(ret) == 0 {
		panic("no return value specified for CountLowRatingsByAlgorithmSince")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) (int64, error)); ok {
		return rf(ctx, algorithmID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) int64); ok {
		r0 = rf(ctx, algorithmID, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = rf(ctx, algorithmID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLowRatingsByAlgorithmSince'
type MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call struct {
	*mock.Call
}

// CountLowRatingsByAlgorithmSince is a helper method to define mock.On call
//   - ctx context.Context
//   - algorithmID int64
//   - since time.Time
func (_e *MockIRatingRepository_Expecter) CountLowRatingsByAlgorithmSince(ctx interface{}, algorithmID interface{}, since interface{}) *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call {
	return &MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call{Call: _e.mock.On("CountLowRatingsByAlgorithmSince", ctx, algorithmID, since)}
}

func (_c *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call) Run(run func(ctx context.Context, algorithmID int64, since time.Time)) *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call) Return(_a0 int64, _a1 error) *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call) RunAndReturn(run func(context.Context, int64, time.Time) (int64, error)) *MockIRatingRepository_CountLowRatingsByAlgorithmSince_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, r
func (_m *MockIRatingRepository) Create(ctx context.Context, r *model.SysRating) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysRating) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRatingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRatingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *model.SysRating
func (_e *MockIRatingRepository_Expecter) Create(ctx interface{}, r interface{}) *MockIRatingRepository_Create_Call {
	return &MockIRatingRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockIRatingRepository_Create_Call) Run(run func(ctx context.Context, r *model.SysRating)) *MockIRatingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysRating))
	})
	return _c
}

func (_c *MockIRatingRepository_Create_Call) Return(_a0 error) *MockIRatingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRatingRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysRating) error) *MockIRatingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIRatingRepository) FindByID(ctx context.Context, id int64) (*model.SysRating, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysRating, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysRating); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIRatingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIRatingRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIRatingRepository_FindByID_Call {
	return &MockIRatingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIRatingRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIRatingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIRatingRepository_FindByID_Call) Return(_a0 *model.SysRating, _a1 error) *MockIRatingRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysRating, error)) *MockIRatingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPredLogID provides a mock function with given fields: ctx, predLogID
func (_m *MockIRatingRepository) FindByPredLogID(ctx context.Context, predLogID int64) (*model.SysRating, error) {
	ret := _m.Called(ctx, predLogID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPredLogID")
	}

	var r0 *model.SysRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysRating, error)); ok {
		return rf(ctx, predLogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysRating); ok {
		r0 = rf(ctx, predLogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, predLogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_FindByPredLogID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPredLogID'
type MockIRatingRepository_FindByPredLogID_Call struct {
	*mock.Call
}

// FindByPredLogID is a helper method to define mock.On call
//   - ctx context.Context
//   - predLogID int64
func (_e *MockIRatingRepository_Expecter) FindByPredLogID(ctx interface{}, predLogID interface{}) *MockIRatingRepository_FindByPredLogID_Call {
	return &MockIRatingRepository_FindByPredLogID_Call{Call: _e.mock.On("FindByPredLogID", ctx, predLogID)}
}

func (_c *MockIRatingRepository_FindByPredLogID_Call) Run(run func(ctx context.Context, predLogID int64)) *MockIRatingRepository_FindByPredLogID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIRatingRepository_FindByPredLogID_Call) Return(_a0 *model.SysRating, _a1 error) *MockIRatingRepository_FindByPredLogID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_FindByPredLogID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysRating, error)) *MockIRatingRepository_FindByPredLogID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIRatingRepository) FindPage(ctx context.Context, q *query.RatingPageQuery) ([]feedback.RatingWithUserAndAlgorithm, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []feedback.RatingWithUserAndAlgorithm
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.RatingPageQuery) ([]feedback.RatingWithUserAndAlgorithm, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.RatingPageQuery) []feedback.RatingWithUserAndAlgorithm); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.RatingWithUserAndAlgorithm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.RatingPageQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.RatingPageQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRatingRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIRatingRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.RatingPageQuery
func (_e *MockIRatingRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIRatingRepository_FindPage_Call {
	return &MockIRatingRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIRatingRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.RatingPageQuery)) *MockIRatingRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.RatingPageQuery))
	})
	return _c
}

func (_c *MockIRatingRepository_FindPage_Call) Return(_a0 []feedback.RatingWithUserAndAlgorithm, _a1 int64, _a2 error) *MockIRatingRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRatingRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.RatingPageQuery) ([]feedback.RatingWithUserAndAlgorithm, int64, error)) *MockIRatingRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// FindPageMy provides a mock function with given fields: ctx, userID, pageNum, pageSize
func (_m *MockIRatingRepository) FindPageMy(ctx context.Context, userID int64, pageNum int, pageSize int) ([]feedback.RatingWithAlgorithm, int64, error) {
	ret := _m.Called(ctx, userID, pageNum, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindPageMy")
	}

	var r0 []feedback.RatingWithAlgorithm
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]feedback.RatingWithAlgorithm, int64, error)); ok {
		return rf(ctx, userID, pageNum, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []feedback.RatingWithAlgorithm); ok {
		r0 = rf(ctx, userID, pageNum, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.RatingWithAlgorithm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int64); ok {
		r1 = rf(ctx, userID, pageNum, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, userID, pageNum, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRatingRepository_FindPageMy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPageMy'
type MockIRatingRepository_FindPageMy_Call struct {
	*mock.Call
}

// FindPageMy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - pageNum int
//   - pageSize int
func (_e *MockIRatingRepository_Expecter) FindPageMy(ctx interface{}, userID interface{}, pageNum interface{}, pageSize interface{}) *MockIRatingRepository_FindPageMy_Call {
	return &MockIRatingRepository_FindPageMy_Call{Call: _e.mock.On("FindPageMy", ctx, userID, pageNum, pageSize)}
}

func (_c *MockIRatingRepository_FindPageMy_Call) Run(run func(ctx context.Context, userID int64, pageNum int, pageSize int)) *MockIRatingRepository_FindPageMy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIRatingRepository_FindPageMy_Call) Return(_a0 []feedback.RatingWithAlgorithm, _a1 int64, _a2 error) *MockIRatingRepository_FindPageMy_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRatingRepository_FindPageMy_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]feedback.RatingWithAlgorithm, int64, error)) *MockIRatingRepository_FindPageMy_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlgorithmStats provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIRatingRepository) GetAlgorithmStats(ctx context.Context, startTime string, endTime string) ([]feedback.AlgorithmRatingStatRow, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetAlgorithmStats")
	}

	var r0 []feedback.AlgorithmRatingStatRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]feedback.AlgorithmRatingStatRow, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []feedback.AlgorithmRatingStatRow); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.AlgorithmRatingStatRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_GetAlgorithmStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlgorithmStats'
type MockIRatingRepository_GetAlgorithmStats_Call struct {
	*mock.Call
}

// GetAlgorithmStats is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIRatingRepository_Expecter) GetAlgorithmStats(ctx interface{}, startTime interface{}, endTime interface{}) *MockIRatingRepository_GetAlgorithmStats_Call {
	return &MockIRatingRepository_GetAlgorithmStats_Call{Call: _e.mock.On("GetAlgorithmStats", ctx, startTime, endTime)}
}

func (_c *MockIRatingRepository_GetAlgorithmStats_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIRatingRepository_GetAlgorithmStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRatingRepository_GetAlgorithmStats_Call) Return(_a0 []feedback.AlgorithmRatingStatRow, _a1 error) *MockIRatingRepository_GetAlgorithmStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_GetAlgorithmStats_Call) RunAndReturn(run func(context.Context, string, string) ([]feedback.AlgorithmRatingStatRow, error)) *MockIRatingRepository_GetAlgorithmStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetRatingCountByValue provides a mock function with given fields: ctx, rating, startTime, endTime
func (_m *MockIRatingRepository) GetRatingCountByValue(ctx context.Context, rating int, startTime string, endTime string) (int64, error) {
	ret := _m.Called(ctx, rating, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetRatingCountByValue")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) (int64, error)); ok {
		return rf(ctx, rating, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) int64); ok {
		r0 = rf(ctx, rating, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, rating, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_GetRatingCountByValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRatingCountByValue'
type MockIRatingRepository_GetRatingCountByValue_Call struct {
	*mock.Call
}

// GetRatingCountByValue is a helper method to define mock.On call
//   - ctx context.Context
//   - rating int
//   - startTime string
//   - endTime string
func (_e *MockIRatingRepository_Expecter) GetRatingCountByValue(ctx interface{}, rating interface{}, startTime interface{}, endTime interface{}) *MockIRatingRepository_GetRatingCountByValue_Call {
	return &MockIRatingRepository_GetRatingCountByValue_Call{Call: _e.mock.On("GetRatingCountByValue", ctx, rating, startTime, endTime)}
}

func (_c *MockIRatingRepository_GetRatingCountByValue_Call) Run(run func(ctx context.Context, rating int, startTime string, endTime string)) *MockIRatingRepository_GetRatingCountByValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIRatingRepository_GetRatingCountByValue_Call) Return(_a0 int64, _a1 error) *MockIRatingRepository_GetRatingCountByValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_GetRatingCountByValue_Call) RunAndReturn(run func(context.Context, int, string, string) (int64, error)) *MockIRatingRepository_GetRatingCountByValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIRatingRepository) GetStats(ctx context.Context, startTime string, endTime string) (int64, float64, map[int]int64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int64
	var r1 float64
	var r2 map[int]int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, float64, map[int]int64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) float64); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) map[int]int64); ok {
		r2 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(map[int]int64)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, startTime, endTime)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockIRatingRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockIRatingRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIRatingRepository_Expecter) GetStats(ctx interface{}, startTime interface{}, endTime interface{}) *MockIRatingRepository_GetStats_Call {
	return &MockIRatingRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, startTime, endTime)}
}

func (_c *MockIRatingRepository_GetStats_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIRatingRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRatingRepository_GetStats_Call) Return(total int64, avgRating float64, distribution map[int]int64, err error) *MockIRatingRepository_GetStats_Call {
	_c.Call.Return(total, avgRating, distribution, err)
	return _c
}

func (_c *MockIRatingRepository_GetStats_Call) RunAndReturn(run func(context.Context, string, string) (int64, float64, map[int]int64, error)) *MockIRatingRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsByAlgorithmID provides a mock function with given fields: ctx, algorithmID
func (_m *MockIRatingRepository) GetStatsByAlgorithmID(ctx context.Context, algorithmID int64) (int64, float64, map[int8]int64, error) {
	ret := _m.Called(ctx, algorithmID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByAlgorithmID")
	}

	var r0 int64
	var r1 float64
	var r2 map[int8]int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, float64, map[int8]int64, error)); ok {
		return rf(ctx, algorithmID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, algorithmID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) float64); ok {
		r1 = rf(ctx, algorithmID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) map[int8]int64); ok {
		r2 = rf(ctx, algorithmID)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(map[int8]int64)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, int64) error); ok {
		r3 = rf(ctx, algorithmID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockIRatingRepository_GetStatsByAlgorithmID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsByAlgorithmID'
type MockIRatingRepository_GetStatsByAlgorithmID_Call struct {
	*mock.Call
}

// GetStatsByAlgorithmID is a helper method to define mock.On call
//   - ctx context.Context
//   - algorithmID int64
func (_e *MockIRatingRepository_Expecter) GetStatsByAlgorithmID(ctx interface{}, algorithmID interface{}) *MockIRatingRepository_GetStatsByAlgorithmID_Call {
	return &MockIRatingRepository_GetStatsByAlgorithmID_Call{Call: _e.mock.On("GetStatsByAlgorithmID", ctx, algorithmID)}
}

func (_c *MockIRatingRepository_GetStatsByAlgorithmID_Call) Run(run func(ctx context.Context, algorithmID int64)) *MockIRatingRepository_GetStatsByAlgorithmID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIRatingRepository_GetStatsByAlgorithmID_Call) Return(totalCount int64, avgRating float64, distribution map[int8]int64, err error) *MockIRatingRepository_GetStatsByAlgorithmID_Call {
	_c.Call.Return(totalCount, avgRating, distribution, err)
	return _c
}

func (_c *MockIRatingRepository_GetStatsByAlgorithmID_Call) RunAndReturn(run func(context.Context, int64) (int64, float64, map[int8]int64, error)) *MockIRatingRepository_GetStatsByAlgorithmID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagRanking provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockIRatingRepository) GetTagRanking(ctx context.Context, startTime string, endTime string) ([]feedback.TagCountRow, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetTagRanking")
	}

	var r0 []feedback.TagCountRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]feedback.TagCountRow, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []feedback.TagCountRow); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.TagCountRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRatingRepository_GetTagRanking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagRanking'
type MockIRatingRepository_GetTagRanking_Call struct {
	*mock.Call
}

// GetTagRanking is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime string
//   - endTime string
func (_e *MockIRatingRepository_Expecter) GetTagRanking(ctx interface{}, startTime interface{}, endTime interface{}) *MockIRatingRepository_GetTagRanking_Call {
	return &MockIRatingRepository_GetTagRanking_Call{Call: _e.mock.On("GetTagRanking", ctx, startTime, endTime)}
}

func (_c *MockIRatingRepository_GetTagRanking_Call) Run(run func(ctx context.Context, startTime string, endTime string)) *MockIRatingRepository_GetTagRanking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRatingRepository_GetTagRanking_Call) Return(_a0 []feedback.TagCountRow, _a1 error) *MockIRatingRepository_GetTagRanking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRatingRepository_GetTagRanking_Call) RunAndReturn(run func(context.Context, string, string) ([]feedback.TagCountRow, error)) *MockIRatingRepository_GetTagRanking_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodayLowRatingCounts provides a mock function with given fields: ctx
func (_m *MockIRatingRepository) GetTodayLowRatingCounts(ctx context.Context) (int64, int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayLowRatingCounts")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRatingRepository_GetTodayLowRatingCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayLowRatingCounts'
type MockIRatingRepository_GetTodayLowRatingCounts_Call struct {
	*mock.Call
}

// GetTodayLowRatingCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRatingRepository_Expecter) GetTodayLowRatingCounts(ctx interface{}) *MockIRatingRepository_GetTodayLowRatingCounts_Call {
	return &MockIRatingRepository_GetTodayLowRatingCounts_Call{Call: _e.mock.On("GetTodayLowRatingCounts", ctx)}
}

func (_c *MockIRatingRepository_GetTodayLowRatingCounts_Call) Run(run func(ctx context.Context)) *MockIRatingRepository_GetTodayLowRatingCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRatingRepository_GetTodayLowRatingCounts_Call) Return(lowCount int64, totalCount int64, err error) *MockIRatingRepository_GetTodayLowRatingCounts_Call {
	_c.Call.Return(lowCount, totalCount, err)
	return _c
}

func (_c *MockIRatingRepository_GetTodayLowRatingCounts_Call) RunAndReturn(run func(context.Context) (int64, int64, error)) *MockIRatingRepository_GetTodayLowRatingCounts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updates
func (_m *MockIRatingRepository) Update(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRatingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRatingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (_e *MockIRatingRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockIRatingRepository_Update_Call {
	return &MockIRatingRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockIRatingRepository_Update_Call) Run(run func(ctx context.Context, id int64, updates map[string]interface{})) *MockIRatingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIRatingRepository_Update_Call) Return(_a0 error) *MockIRatingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRatingRepository_Update_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIRatingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRatingRepository creates a new instance of MockIRatingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRatingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRatingRepository {
	mock := &MockIRatingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
