// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"
)

// MockIInputHistoryRepository is an autogenerated mock type for the IInputHistoryRepository type
type MockIInputHistoryRepository struct {
	mock.Mock
}

type MockIInputHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInputHistoryRepository) EXPECT() *MockIInputHistoryRepository_Expecter {
	return &MockIInputHistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, history
func (_m *MockIInputHistoryRepository) Create(ctx context.Context, history *model.SysInputHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysInputHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIInputHistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIInputHistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *model.SysInputHistory
func (_e *MockIInputHistoryRepository_Expecter) Create(ctx interface{}, history interface{}) *MockIInputHistoryRepository_Create_Call {
	return &MockIInputHistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *MockIInputHistoryRepository_Create_Call) Run(run func(ctx context.Context, history *model.SysInputHistory)) *MockIInputHistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysInputHistory))
	})
	return _c
}

func (_c *MockIInputHistoryRepository_Create_Call) Return(_a0 error) *MockIInputHistoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIInputHistoryRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysInputHistory) error) *MockIInputHistoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserAndIDs provides a mock function with given fields: ctx, userID, ids
func (_m *MockIInputHistoryRepository) DeleteByUserAndIDs(ctx context.Context, userID int64, ids []int64) (int64, error) {
	ret := _m.Called(ctx, userID, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserAndIDs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) (int64, error)); ok {
		return rf(ctx, userID, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) int64); ok {
		r0 = rf(ctx, userID, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []int64) error); ok {
		r1 = rf(ctx, userID, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInputHistoryRepository_DeleteByUserAndIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserAndIDs'
type MockIInputHistoryRepository_DeleteByUserAndIDs_Call struct {
	*mock.Call
}

// DeleteByUserAndIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - ids []int64
func (_e *MockIInputHistoryRepository_Expecter) DeleteByUserAndIDs(ctx interface{}, userID interface{}, ids interface{}) *MockIInputHistoryRepository_DeleteByUserAndIDs_Call {
	return &MockIInputHistoryRepository_DeleteByUserAndIDs_Call{Call: _e.mock.On("DeleteByUserAndIDs", ctx, userID, ids)}
}

func (_c *MockIInputHistoryRepository_DeleteByUserAndIDs_Call) Run(run func(ctx context.Context, userID int64, ids []int64)) *MockIInputHistoryRepository_DeleteByUserAndIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockIInputHistoryRepository_DeleteByUserAndIDs_Call) Return(_a0 int64, _a1 error) *MockIInputHistoryRepository_DeleteByUserAndIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInputHistoryRepository_DeleteByUserAndIDs_Call) RunAndReturn(run func(context.Context, int64, []int64) (int64, error)) *MockIInputHistoryRepository_DeleteByUserAndIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIInputHistoryRepository) DeleteByUserID(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInputHistoryRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockIInputHistoryRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIInputHistoryRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockIInputHistoryRepository_DeleteByUserID_Call {
	return &MockIInputHistoryRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockIInputHistoryRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockIInputHistoryRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIInputHistoryRepository_DeleteByUserID_Call) Return(_a0 int64, _a1 error) *MockIInputHistoryRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInputHistoryRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockIInputHistoryRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIInputHistoryRepository) FindByID(ctx context.Context, id int64) (*model.SysInputHistory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysInputHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysInputHistory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysInputHistory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysInputHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIInputHistoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIInputHistoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIInputHistoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIInputHistoryRepository_FindByID_Call {
	return &MockIInputHistoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIInputHistoryRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIInputHistoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIInputHistoryRepository_FindByID_Call) Return(_a0 *model.SysInputHistory, _a1 error) *MockIInputHistoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIInputHistoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysInputHistory, error)) *MockIInputHistoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, userID, pageNum, pageSize, inputSource, keyword, status
func (_m *MockIInputHistoryRepository) FindPage(ctx context.Context, userID int64, pageNum int, pageSize int, inputSource string, keyword string, status int) ([]model.SysInputHistory, int64, error) {
	ret := _m.Called(ctx, userID, pageNum, pageSize, inputSource, keyword, status)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []model.SysInputHistory
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int, string, string, int) ([]model.SysInputHistory, int64, error)); ok {
		return rf(ctx, userID, pageNum, pageSize, inputSource, keyword, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int, string, string, int) []model.SysInputHistory); ok {
		r0 = rf(ctx, userID, pageNum, pageSize, inputSource, keyword, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysInputHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int, string, string, int) int64); ok {
		r1 = rf(ctx, userID, pageNum, pageSize, inputSource, keyword, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int, string, string, int) error); ok {
		r2 = rf(ctx, userID, pageNum, pageSize, inputSource, keyword, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIInputHistoryRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIInputHistoryRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - pageNum int
//   - pageSize int
//   - inputSource string
//   - keyword string
//   - status int
func (_e *MockIInputHistoryRepository_Expecter) FindPage(ctx interface{}, userID interface{}, pageNum interface{}, pageSize interface{}, inputSource interface{}, keyword interface{}, status interface{}) *MockIInputHistoryRepository_FindPage_Call {
	return &MockIInputHistoryRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, userID, pageNum, pageSize, inputSource, keyword, status)}
}

func (_c *MockIInputHistoryRepository_FindPage_Call) Run(run func(ctx context.Context, userID int64, pageNum int, pageSize int, inputSource string, keyword string, status int)) *MockIInputHistoryRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int), args[4].(string), args[5].(string), args[6].(int))
	})
	return _c
}

func (_c *MockIInputHistoryRepository_FindPage_Call) Return(_a0 []model.SysInputHistory, _a1 int64, _a2 error) *MockIInputHistoryRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIInputHistoryRepository_FindPage_Call) RunAndReturn(run func(context.Context, int64, int, int, string, string, int) ([]model.SysInputHistory, int64, error)) *MockIInputHistoryRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIInputHistoryRepository creates a new instance of MockIInputHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInputHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInputHistoryRepository {
	mock := &MockIInputHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
