// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dataset "github.com/earthyzinc/dehaze-go/internal/repository/dataset"
	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	read "github.com/earthyzinc/dehaze-go/internal/model/read"
)

// MockIDatasetRepository is an autogenerated mock type for the IDatasetRepository type
type MockIDatasetRepository struct {
	mock.Mock
}

type MockIDatasetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatasetRepository) EXPECT() *MockIDatasetRepository_Expecter {
	return &MockIDatasetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasetRepository) Create(ctx context.Context, _a1 *model.SysDataset) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDataset) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDatasetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDataset
func (_e *MockIDatasetRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIDatasetRepository_Create_Call {
	return &MockIDatasetRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIDatasetRepository_Create_Call) Run(run func(ctx context.Context, _a1 *model.SysDataset)) *MockIDatasetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDataset))
	})
	return _c
}

func (_c *MockIDatasetRepository_Create_Call) Return(_a0 error) *MockIDatasetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysDataset) error) *MockIDatasetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDatasetRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDatasetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDatasetRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDatasetRepository_Delete_Call {
	return &MockIDatasetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDatasetRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDatasetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_Delete_Call) Return(_a0 error) *MockIDatasetRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDatasetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockIDatasetRepository) FindAll(ctx context.Context) ([]model.SysDataset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SysDataset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SysDataset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIDatasetRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDatasetRepository_Expecter) FindAll(ctx interface{}) *MockIDatasetRepository_FindAll_Call {
	return &MockIDatasetRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIDatasetRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindAll_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]model.SysDataset, error)) *MockIDatasetRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function with given fields: ctx
func (_m *MockIDatasetRepository) FindAllActive(ctx context.Context) ([]model.SysDataset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SysDataset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SysDataset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockIDatasetRepository_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDatasetRepository_Expecter) FindAllActive(ctx interface{}) *MockIDatasetRepository_FindAllActive_Call {
	return &MockIDatasetRepository_FindAllActive_Call{Call: _e.mock.On("FindAllActive", ctx)}
}

func (_c *MockIDatasetRepository_FindAllActive_Call) Run(run func(ctx context.Context)) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindAllActive_Call) Return(_a0 []model.SysDataset, _a1 error) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindAllActive_Call) RunAndReturn(run func(context.Context) ([]model.SysDataset, error)) *MockIDatasetRepository_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIDatasetRepository) FindByID(ctx context.Context, id int64) (*model.SysDataset, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysDataset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDataset, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDataset); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDataset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIDatasetRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDatasetRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIDatasetRepository_FindByID_Call {
	return &MockIDatasetRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIDatasetRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindByID_Call) Return(_a0 *model.SysDataset, _a1 error) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDataset, error)) *MockIDatasetRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIDatasetRepository) FindPage(ctx context.Context, q *query.DatasetQuery) (*read.PageResult[read.Dataset], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 *read.PageResult[read.Dataset]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DatasetQuery) (*read.PageResult[read.Dataset], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DatasetQuery) *read.PageResult[read.Dataset]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*read.PageResult[read.Dataset])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DatasetQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIDatasetRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DatasetQuery
func (_e *MockIDatasetRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIDatasetRepository_FindPage_Call {
	return &MockIDatasetRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIDatasetRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.DatasetQuery)) *MockIDatasetRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DatasetQuery))
	})
	return _c
}

func (_c *MockIDatasetRepository_FindPage_Call) Return(_a0 *read.PageResult[read.Dataset], _a1 error) *MockIDatasetRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.DatasetQuery) (*read.PageResult[read.Dataset], error)) *MockIDatasetRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, datasetID
func (_m *MockIDatasetRepository) GetFormData(ctx context.Context, datasetID int64) (*read.DatasetForm, error) {
	ret := _m.Called(ctx, datasetID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *read.DatasetForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*read.DatasetForm, error)); ok {
		return rf(ctx, datasetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *read.DatasetForm); ok {
		r0 = rf(ctx, datasetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*read.DatasetForm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, datasetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDatasetRepository_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIDatasetRepository_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - datasetID int64
func (_e *MockIDatasetRepository_Expecter) GetFormData(ctx interface{}, datasetID interface{}) *MockIDatasetRepository_GetFormData_Call {
	return &MockIDatasetRepository_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, datasetID)}
}

func (_c *MockIDatasetRepository_GetFormData_Call) Run(run func(ctx context.Context, datasetID int64)) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_GetFormData_Call) Return(_a0 *read.DatasetForm, _a1 error) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDatasetRepository_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*read.DatasetForm, error)) *MockIDatasetRepository_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByIDs provides a mock function with given fields: ctx, ids, updateBy
func (_m *MockIDatasetRepository) SoftDeleteByIDs(ctx context.Context, ids []int64, updateBy int64) error {
	ret := _m.Called(ctx, ids, updateBy)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, int64) error); ok {
		r0 = rf(ctx, ids, updateBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_SoftDeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByIDs'
type MockIDatasetRepository_SoftDeleteByIDs_Call struct {
	*mock.Call
}

// SoftDeleteByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - updateBy int64
func (_e *MockIDatasetRepository_Expecter) SoftDeleteByIDs(ctx interface{}, ids interface{}, updateBy interface{}) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	return &MockIDatasetRepository_SoftDeleteByIDs_Call{Call: _e.mock.On("SoftDeleteByIDs", ctx, ids, updateBy)}
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) Run(run func(ctx context.Context, ids []int64, updateBy int64)) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) Return(_a0 error) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_SoftDeleteByIDs_Call) RunAndReturn(run func(context.Context, []int64, int64) error) *MockIDatasetRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockIDatasetRepository) Transaction(ctx context.Context, fn func(dataset.IDatasetRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(dataset.IDatasetRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockIDatasetRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(dataset.IDatasetRepository) error
func (_e *MockIDatasetRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockIDatasetRepository_Transaction_Call {
	return &MockIDatasetRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockIDatasetRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(dataset.IDatasetRepository) error)) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(dataset.IDatasetRepository) error))
	})
	return _c
}

func (_c *MockIDatasetRepository_Transaction_Call) Return(_a0 error) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(dataset.IDatasetRepository) error) error) *MockIDatasetRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockIDatasetRepository) Update(ctx context.Context, _a1 *model.SysDataset) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDataset) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDatasetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDatasetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysDataset
func (_e *MockIDatasetRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockIDatasetRepository_Update_Call {
	return &MockIDatasetRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockIDatasetRepository_Update_Call) Run(run func(ctx context.Context, _a1 *model.SysDataset)) *MockIDatasetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDataset))
	})
	return _c
}

func (_c *MockIDatasetRepository_Update_Call) Return(_a0 error) *MockIDatasetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatasetRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysDataset) error) *MockIDatasetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatasetRepository creates a new instance of MockIDatasetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatasetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatasetRepository {
	mock := &MockIDatasetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
