// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	time "time"
)

// MockIEvalLogRepository is an autogenerated mock type for the IEvalLogRepository type
type MockIEvalLogRepository struct {
	mock.Mock
}

type MockIEvalLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEvalLogRepository) EXPECT() *MockIEvalLogRepository_Expecter {
	return &MockIEvalLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockIEvalLogRepository) Create(ctx context.Context, log *model.SysEvalLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysEvalLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEvalLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIEvalLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *model.SysEvalLog
func (_e *MockIEvalLogRepository_Expecter) Create(ctx interface{}, log interface{}) *MockIEvalLogRepository_Create_Call {
	return &MockIEvalLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockIEvalLogRepository_Create_Call) Run(run func(ctx context.Context, log *model.SysEvalLog)) *MockIEvalLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysEvalLog))
	})
	return _c
}

func (_c *MockIEvalLogRepository_Create_Call) Return(_a0 error) *MockIEvalLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEvalLogRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysEvalLog) error) *MockIEvalLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIEvalLogRepository) FindByID(ctx context.Context, id int64) (*model.SysEvalLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysEvalLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysEvalLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysEvalLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysEvalLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEvalLogRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIEvalLogRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIEvalLogRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIEvalLogRepository_FindByID_Call {
	return &MockIEvalLogRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIEvalLogRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIEvalLogRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIEvalLogRepository_FindByID_Call) Return(_a0 *model.SysEvalLog, _a1 error) *MockIEvalLogRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEvalLogRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysEvalLog, error)) *MockIEvalLogRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, algorithmID, pageNum, pageSize
func (_m *MockIEvalLogRepository) FindPage(ctx context.Context, algorithmID int64, pageNum int, pageSize int) ([]model.SysEvalLog, int64, error) {
	ret := _m.Called(ctx, algorithmID, pageNum, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []model.SysEvalLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]model.SysEvalLog, int64, error)); ok {
		return rf(ctx, algorithmID, pageNum, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []model.SysEvalLog); ok {
		r0 = rf(ctx, algorithmID, pageNum, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysEvalLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int64); ok {
		r1 = rf(ctx, algorithmID, pageNum, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, algorithmID, pageNum, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIEvalLogRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIEvalLogRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - algorithmID int64
//   - pageNum int
//   - pageSize int
func (_e *MockIEvalLogRepository_Expecter) FindPage(ctx interface{}, algorithmID interface{}, pageNum interface{}, pageSize interface{}) *MockIEvalLogRepository_FindPage_Call {
	return &MockIEvalLogRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, algorithmID, pageNum, pageSize)}
}

func (_c *MockIEvalLogRepository_FindPage_Call) Run(run func(ctx context.Context, algorithmID int64, pageNum int, pageSize int)) *MockIEvalLogRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIEvalLogRepository_FindPage_Call) Return(_a0 []model.SysEvalLog, _a1 int64, _a2 error) *MockIEvalLogRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIEvalLogRepository_FindPage_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]model.SysEvalLog, int64, error)) *MockIEvalLogRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// FindPageByUser provides a mock function with given fields: ctx, userID, algorithmID, pageNum, pageSize
func (_m *MockIEvalLogRepository) FindPageByUser(ctx context.Context, userID int64, algorithmID int64, pageNum int, pageSize int) ([]model.SysEvalLog, int64, error) {
	ret := _m.Called(ctx, userID, algorithmID, pageNum, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindPageByUser")
	}

	var r0 []model.SysEvalLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int, int) ([]model.SysEvalLog, int64, error)); ok {
		return rf(ctx, userID, algorithmID, pageNum, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int, int) []model.SysEvalLog); ok {
		r0 = rf(ctx, userID, algorithmID, pageNum, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysEvalLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int, int) int64); ok {
		r1 = rf(ctx, userID, algorithmID, pageNum, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, int, int) error); ok {
		r2 = rf(ctx, userID, algorithmID, pageNum, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIEvalLogRepository_FindPageByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPageByUser'
type MockIEvalLogRepository_FindPageByUser_Call struct {
	*mock.Call
}

// FindPageByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - algorithmID int64
//   - pageNum int
//   - pageSize int
func (_e *MockIEvalLogRepository_Expecter) FindPageByUser(ctx interface{}, userID interface{}, algorithmID interface{}, pageNum interface{}, pageSize interface{}) *MockIEvalLogRepository_FindPageByUser_Call {
	return &MockIEvalLogRepository_FindPageByUser_Call{Call: _e.mock.On("FindPageByUser", ctx, userID, algorithmID, pageNum, pageSize)}
}

func (_c *MockIEvalLogRepository_FindPageByUser_Call) Run(run func(ctx context.Context, userID int64, algorithmID int64, pageNum int, pageSize int)) *MockIEvalLogRepository_FindPageByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockIEvalLogRepository_FindPageByUser_Call) Return(_a0 []model.SysEvalLog, _a1 int64, _a2 error) *MockIEvalLogRepository_FindPageByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIEvalLogRepository_FindPageByUser_Call) RunAndReturn(run func(context.Context, int64, int64, int, int) ([]model.SysEvalLog, int64, error)) *MockIEvalLogRepository_FindPageByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkStuckAsFailed provides a mock function with given fields: ctx, threshold
func (_m *MockIEvalLogRepository) MarkStuckAsFailed(ctx context.Context, threshold time.Time) (int, error) {
	ret := _m.Called(ctx, threshold)

	if len(ret) == 0 {
		panic("no return value specified for MarkStuckAsFailed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return rf(ctx, threshold)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = rf(ctx, threshold)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, threshold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEvalLogRepository_MarkStuckAsFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkStuckAsFailed'
type MockIEvalLogRepository_MarkStuckAsFailed_Call struct {
	*mock.Call
}

// MarkStuckAsFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - threshold time.Time
func (_e *MockIEvalLogRepository_Expecter) MarkStuckAsFailed(ctx interface{}, threshold interface{}) *MockIEvalLogRepository_MarkStuckAsFailed_Call {
	return &MockIEvalLogRepository_MarkStuckAsFailed_Call{Call: _e.mock.On("MarkStuckAsFailed", ctx, threshold)}
}

func (_c *MockIEvalLogRepository_MarkStuckAsFailed_Call) Run(run func(ctx context.Context, threshold time.Time)) *MockIEvalLogRepository_MarkStuckAsFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIEvalLogRepository_MarkStuckAsFailed_Call) Return(_a0 int, _a1 error) *MockIEvalLogRepository_MarkStuckAsFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEvalLogRepository_MarkStuckAsFailed_Call) RunAndReturn(run func(context.Context, time.Time) (int, error)) *MockIEvalLogRepository_MarkStuckAsFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResult provides a mock function with given fields: ctx, id, status, result, _a4
func (_m *MockIEvalLogRepository) UpdateResult(ctx context.Context, id int64, status model.LogStatus, result string, _a4 int) error {
	ret := _m.Called(ctx, id, status, result, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.LogStatus, string, int) error); ok {
		r0 = rf(ctx, id, status, result, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEvalLogRepository_UpdateResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResult'
type MockIEvalLogRepository_UpdateResult_Call struct {
	*mock.Call
}

// UpdateResult is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status model.LogStatus
//   - result string
//   - _a4 int
func (_e *MockIEvalLogRepository_Expecter) UpdateResult(ctx interface{}, id interface{}, status interface{}, result interface{}, _a4 interface{}) *MockIEvalLogRepository_UpdateResult_Call {
	return &MockIEvalLogRepository_UpdateResult_Call{Call: _e.mock.On("UpdateResult", ctx, id, status, result, _a4)}
}

func (_c *MockIEvalLogRepository_UpdateResult_Call) Run(run func(ctx context.Context, id int64, status model.LogStatus, result string, _a4 int)) *MockIEvalLogRepository_UpdateResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(model.LogStatus), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockIEvalLogRepository_UpdateResult_Call) Return(_a0 error) *MockIEvalLogRepository_UpdateResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEvalLogRepository_UpdateResult_Call) RunAndReturn(run func(context.Context, int64, model.LogStatus, string, int) error) *MockIEvalLogRepository_UpdateResult_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, errorMessage, _a4
func (_m *MockIEvalLogRepository) UpdateStatus(ctx context.Context, id int64, status model.LogStatus, errorMessage string, _a4 int) error {
	ret := _m.Called(ctx, id, status, errorMessage, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.LogStatus, string, int) error); ok {
		r0 = rf(ctx, id, status, errorMessage, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEvalLogRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIEvalLogRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status model.LogStatus
//   - errorMessage string
//   - _a4 int
func (_e *MockIEvalLogRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, errorMessage interface{}, _a4 interface{}) *MockIEvalLogRepository_UpdateStatus_Call {
	return &MockIEvalLogRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, errorMessage, _a4)}
}

func (_c *MockIEvalLogRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status model.LogStatus, errorMessage string, _a4 int)) *MockIEvalLogRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(model.LogStatus), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockIEvalLogRepository_UpdateStatus_Call) Return(_a0 error) *MockIEvalLogRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEvalLogRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, model.LogStatus, string, int) error) *MockIEvalLogRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIEvalLogRepository creates a new instance of MockIEvalLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEvalLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEvalLogRepository {
	mock := &MockIEvalLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
