// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	read "github.com/earthyzinc/dehaze-go/internal/model/read"
)

// MockIDictTypeRepository is an autogenerated mock type for the IDictTypeRepository type
type MockIDictTypeRepository struct {
	mock.Mock
}

type MockIDictTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDictTypeRepository) EXPECT() *MockIDictTypeRepository_Expecter {
	return &MockIDictTypeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dictType
func (_m *MockIDictTypeRepository) Create(ctx context.Context, dictType *model.SysDictType) error {
	ret := _m.Called(ctx, dictType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDictType) error); ok {
		r0 = rf(ctx, dictType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIDictTypeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dictType *model.SysDictType
func (_e *MockIDictTypeRepository_Expecter) Create(ctx interface{}, dictType interface{}) *MockIDictTypeRepository_Create_Call {
	return &MockIDictTypeRepository_Create_Call{Call: _e.mock.On("Create", ctx, dictType)}
}

func (_c *MockIDictTypeRepository_Create_Call) Run(run func(ctx context.Context, dictType *model.SysDictType)) *MockIDictTypeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDictType))
	})
	return _c
}

func (_c *MockIDictTypeRepository_Create_Call) Return(_a0 error) *MockIDictTypeRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysDictType) error) *MockIDictTypeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIDictTypeRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIDictTypeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDictTypeRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIDictTypeRepository_Delete_Call {
	return &MockIDictTypeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIDictTypeRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDictTypeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDictTypeRepository_Delete_Call) Return(_a0 error) *MockIDictTypeRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIDictTypeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByCode provides a mock function with given fields: ctx, code, excludeID
func (_m *MockIDictTypeRepository) ExistsByCode(ctx context.Context, code string, excludeID ...int64) (bool, error) {
	_va := make([]interface{}, len(excludeID))
	for _i := range excludeID {
		_va[_i] = excludeID[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, code)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) (bool, error)); ok {
		return rf(ctx, code, excludeID...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) bool); ok {
		r0 = rf(ctx, code, excludeID...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...int64) error); ok {
		r1 = rf(ctx, code, excludeID...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeRepository_ExistsByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByCode'
type MockIDictTypeRepository_ExistsByCode_Call struct {
	*mock.Call
}

// ExistsByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - excludeID ...int64
func (_e *MockIDictTypeRepository_Expecter) ExistsByCode(ctx interface{}, code interface{}, excludeID ...interface{}) *MockIDictTypeRepository_ExistsByCode_Call {
	return &MockIDictTypeRepository_ExistsByCode_Call{Call: _e.mock.On("ExistsByCode",
		append([]interface{}{ctx, code}, excludeID...)...)}
}

func (_c *MockIDictTypeRepository_ExistsByCode_Call) Run(run func(ctx context.Context, code string, excludeID ...int64)) *MockIDictTypeRepository_ExistsByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDictTypeRepository_ExistsByCode_Call) Return(_a0 bool, _a1 error) *MockIDictTypeRepository_ExistsByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeRepository_ExistsByCode_Call) RunAndReturn(run func(context.Context, string, ...int64) (bool, error)) *MockIDictTypeRepository_ExistsByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *MockIDictTypeRepository) FindByCode(ctx context.Context, code string) (*model.SysDictType, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *model.SysDictType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysDictType, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysDictType); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDictType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIDictTypeRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockIDictTypeRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockIDictTypeRepository_FindByCode_Call {
	return &MockIDictTypeRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockIDictTypeRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockIDictTypeRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIDictTypeRepository_FindByCode_Call) Return(_a0 *model.SysDictType, _a1 error) *MockIDictTypeRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeRepository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (*model.SysDictType, error)) *MockIDictTypeRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIDictTypeRepository) FindByID(ctx context.Context, id int64) (*model.SysDictType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysDictType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysDictType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysDictType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysDictType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIDictTypeRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIDictTypeRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIDictTypeRepository_FindByID_Call {
	return &MockIDictTypeRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIDictTypeRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIDictTypeRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIDictTypeRepository_FindByID_Call) Return(_a0 *model.SysDictType, _a1 error) *MockIDictTypeRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysDictType, error)) *MockIDictTypeRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindCodesByIDs provides a mock function with given fields: ctx, ids
func (_m *MockIDictTypeRepository) FindCodesByIDs(ctx context.Context, ids []int64) ([]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindCodesByIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeRepository_FindCodesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCodesByIDs'
type MockIDictTypeRepository_FindCodesByIDs_Call struct {
	*mock.Call
}

// FindCodesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIDictTypeRepository_Expecter) FindCodesByIDs(ctx interface{}, ids interface{}) *MockIDictTypeRepository_FindCodesByIDs_Call {
	return &MockIDictTypeRepository_FindCodesByIDs_Call{Call: _e.mock.On("FindCodesByIDs", ctx, ids)}
}

func (_c *MockIDictTypeRepository_FindCodesByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockIDictTypeRepository_FindCodesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIDictTypeRepository_FindCodesByIDs_Call) Return(_a0 []string, _a1 error) *MockIDictTypeRepository_FindCodesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeRepository_FindCodesByIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]string, error)) *MockIDictTypeRepository_FindCodesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIDictTypeRepository) FindPage(ctx context.Context, q *query.DictTypePageQuery) (*read.PageResult[read.DictTypePage], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 *read.PageResult[read.DictTypePage]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictTypePageQuery) (*read.PageResult[read.DictTypePage], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.DictTypePageQuery) *read.PageResult[read.DictTypePage]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*read.PageResult[read.DictTypePage])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.DictTypePageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDictTypeRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIDictTypeRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.DictTypePageQuery
func (_e *MockIDictTypeRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIDictTypeRepository_FindPage_Call {
	return &MockIDictTypeRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIDictTypeRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.DictTypePageQuery)) *MockIDictTypeRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.DictTypePageQuery))
	})
	return _c
}

func (_c *MockIDictTypeRepository_FindPage_Call) Return(_a0 *read.PageResult[read.DictTypePage], _a1 error) *MockIDictTypeRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDictTypeRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.DictTypePageQuery) (*read.PageResult[read.DictTypePage], error)) *MockIDictTypeRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, dictType
func (_m *MockIDictTypeRepository) Update(ctx context.Context, dictType *model.SysDictType) error {
	ret := _m.Called(ctx, dictType)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysDictType) error); ok {
		r0 = rf(ctx, dictType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDictTypeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIDictTypeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dictType *model.SysDictType
func (_e *MockIDictTypeRepository_Expecter) Update(ctx interface{}, dictType interface{}) *MockIDictTypeRepository_Update_Call {
	return &MockIDictTypeRepository_Update_Call{Call: _e.mock.On("Update", ctx, dictType)}
}

func (_c *MockIDictTypeRepository_Update_Call) Run(run func(ctx context.Context, dictType *model.SysDictType)) *MockIDictTypeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysDictType))
	})
	return _c
}

func (_c *MockIDictTypeRepository_Update_Call) Return(_a0 error) *MockIDictTypeRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDictTypeRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysDictType) error) *MockIDictTypeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDictTypeRepository creates a new instance of MockIDictTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDictTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDictTypeRepository {
	mock := &MockIDictTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
