// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	time "time"
)

// MockIMessageRepository is an autogenerated mock type for the IMessageRepository type
type MockIMessageRepository struct {
	mock.Mock
}

type MockIMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMessageRepository) EXPECT() *MockIMessageRepository_Expecter {
	return &MockIMessageRepository_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function with given fields: ctx, userID
func (_m *MockIMessageRepository) CountUnread(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockIMessageRepository_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIMessageRepository_Expecter) CountUnread(ctx interface{}, userID interface{}) *MockIMessageRepository_CountUnread_Call {
	return &MockIMessageRepository_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockIMessageRepository_CountUnread_Call) Run(run func(ctx context.Context, userID int64)) *MockIMessageRepository_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIMessageRepository_CountUnread_Call) Return(_a0 int64, _a1 error) *MockIMessageRepository_CountUnread_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_CountUnread_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockIMessageRepository_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, msg
func (_m *MockIMessageRepository) Create(ctx context.Context, msg *model.SysMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *model.SysMessage
func (_e *MockIMessageRepository_Expecter) Create(ctx interface{}, msg interface{}) *MockIMessageRepository_Create_Call {
	return &MockIMessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, msg)}
}

func (_c *MockIMessageRepository_Create_Call) Run(run func(ctx context.Context, msg *model.SysMessage)) *MockIMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysMessage))
	})
	return _c
}

func (_c *MockIMessageRepository_Create_Call) Return(_a0 error) *MockIMessageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMessageRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysMessage) error) *MockIMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, msgs
func (_m *MockIMessageRepository) CreateBatch(ctx context.Context, msgs []model.SysMessage) ([]int64, error) {
	ret := _m.Called(ctx, msgs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.SysMessage) ([]int64, error)); ok {
		return rf(ctx, msgs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.SysMessage) []int64); ok {
		r0 = rf(ctx, msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.SysMessage) error); ok {
		r1 = rf(ctx, msgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockIMessageRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []model.SysMessage
func (_e *MockIMessageRepository_Expecter) CreateBatch(ctx interface{}, msgs interface{}) *MockIMessageRepository_CreateBatch_Call {
	return &MockIMessageRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, msgs)}
}

func (_c *MockIMessageRepository_CreateBatch_Call) Run(run func(ctx context.Context, msgs []model.SysMessage)) *MockIMessageRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.SysMessage))
	})
	return _c
}

func (_c *MockIMessageRepository_CreateBatch_Call) Return(_a0 []int64, _a1 error) *MockIMessageRepository_CreateBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []model.SysMessage) ([]int64, error)) *MockIMessageRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredBatch provides a mock function with given fields: ctx, before, batchSize
func (_m *MockIMessageRepository) DeleteExpiredBatch(ctx context.Context, before time.Time, batchSize int) (int64, error) {
	ret := _m.Called(ctx, before, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredBatch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return rf(ctx, before, batchSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = rf(ctx, before, batchSize)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, before, batchSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_DeleteExpiredBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredBatch'
type MockIMessageRepository_DeleteExpiredBatch_Call struct {
	*mock.Call
}

// DeleteExpiredBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
//   - batchSize int
func (_e *MockIMessageRepository_Expecter) DeleteExpiredBatch(ctx interface{}, before interface{}, batchSize interface{}) *MockIMessageRepository_DeleteExpiredBatch_Call {
	return &MockIMessageRepository_DeleteExpiredBatch_Call{Call: _e.mock.On("DeleteExpiredBatch", ctx, before, batchSize)}
}

func (_c *MockIMessageRepository_DeleteExpiredBatch_Call) Run(run func(ctx context.Context, before time.Time, batchSize int)) *MockIMessageRepository_DeleteExpiredBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockIMessageRepository_DeleteExpiredBatch_Call) Return(_a0 int64, _a1 error) *MockIMessageRepository_DeleteExpiredBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_DeleteExpiredBatch_Call) RunAndReturn(run func(context.Context, time.Time, int) (int64, error)) *MockIMessageRepository_DeleteExpiredBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBizModuleAndBizID provides a mock function with given fields: ctx, bizModule, bizID
func (_m *MockIMessageRepository) FindByBizModuleAndBizID(ctx context.Context, bizModule string, bizID string) ([]model.SysMessage, error) {
	ret := _m.Called(ctx, bizModule, bizID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBizModuleAndBizID")
	}

	var r0 []model.SysMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.SysMessage, error)); ok {
		return rf(ctx, bizModule, bizID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.SysMessage); ok {
		r0 = rf(ctx, bizModule, bizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bizModule, bizID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_FindByBizModuleAndBizID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBizModuleAndBizID'
type MockIMessageRepository_FindByBizModuleAndBizID_Call struct {
	*mock.Call
}

// FindByBizModuleAndBizID is a helper method to define mock.On call
//   - ctx context.Context
//   - bizModule string
//   - bizID string
func (_e *MockIMessageRepository_Expecter) FindByBizModuleAndBizID(ctx interface{}, bizModule interface{}, bizID interface{}) *MockIMessageRepository_FindByBizModuleAndBizID_Call {
	return &MockIMessageRepository_FindByBizModuleAndBizID_Call{Call: _e.mock.On("FindByBizModuleAndBizID", ctx, bizModule, bizID)}
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizID_Call) Run(run func(ctx context.Context, bizModule string, bizID string)) *MockIMessageRepository_FindByBizModuleAndBizID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizID_Call) Return(_a0 []model.SysMessage, _a1 error) *MockIMessageRepository_FindByBizModuleAndBizID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizID_Call) RunAndReturn(run func(context.Context, string, string) ([]model.SysMessage, error)) *MockIMessageRepository_FindByBizModuleAndBizID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBizModuleAndBizIDAndRecipientIDs provides a mock function with given fields: ctx, bizModule, bizID, recipientIDs
func (_m *MockIMessageRepository) FindByBizModuleAndBizIDAndRecipientIDs(ctx context.Context, bizModule string, bizID string, recipientIDs []int64) ([]model.SysMessage, error) {
	ret := _m.Called(ctx, bizModule, bizID, recipientIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByBizModuleAndBizIDAndRecipientIDs")
	}

	var r0 []model.SysMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []int64) ([]model.SysMessage, error)); ok {
		return rf(ctx, bizModule, bizID, recipientIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []int64) []model.SysMessage); ok {
		r0 = rf(ctx, bizModule, bizID, recipientIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []int64) error); ok {
		r1 = rf(ctx, bizModule, bizID, recipientIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBizModuleAndBizIDAndRecipientIDs'
type MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call struct {
	*mock.Call
}

// FindByBizModuleAndBizIDAndRecipientIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - bizModule string
//   - bizID string
//   - recipientIDs []int64
func (_e *MockIMessageRepository_Expecter) FindByBizModuleAndBizIDAndRecipientIDs(ctx interface{}, bizModule interface{}, bizID interface{}, recipientIDs interface{}) *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call {
	return &MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call{Call: _e.mock.On("FindByBizModuleAndBizIDAndRecipientIDs", ctx, bizModule, bizID, recipientIDs)}
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call) Run(run func(ctx context.Context, bizModule string, bizID string, recipientIDs []int64)) *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]int64))
	})
	return _c
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call) Return(_a0 []model.SysMessage, _a1 error) *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call) RunAndReturn(run func(context.Context, string, string, []int64) ([]model.SysMessage, error)) *MockIMessageRepository_FindByBizModuleAndBizIDAndRecipientIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIMessageRepository) FindByID(ctx context.Context, id int64) (*model.SysMessage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysMessage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysMessage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIMessageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIMessageRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIMessageRepository_FindByID_Call {
	return &MockIMessageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIMessageRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIMessageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIMessageRepository_FindByID_Call) Return(_a0 *model.SysMessage, _a1 error) *MockIMessageRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysMessage, error)) *MockIMessageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, userID, q
func (_m *MockIMessageRepository) FindPage(ctx context.Context, userID int64, q *query.MessageQuery) ([]model.SysMessage, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []model.SysMessage
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MessageQuery) ([]model.SysMessage, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MessageQuery) []model.SysMessage); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *query.MessageQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *query.MessageQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMessageRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIMessageRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - q *query.MessageQuery
func (_e *MockIMessageRepository_Expecter) FindPage(ctx interface{}, userID interface{}, q interface{}) *MockIMessageRepository_FindPage_Call {
	return &MockIMessageRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, userID, q)}
}

func (_c *MockIMessageRepository_FindPage_Call) Run(run func(ctx context.Context, userID int64, q *query.MessageQuery)) *MockIMessageRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*query.MessageQuery))
	})
	return _c
}

func (_c *MockIMessageRepository_FindPage_Call) Return(_a0 []model.SysMessage, _a1 int64, _a2 error) *MockIMessageRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMessageRepository_FindPage_Call) RunAndReturn(run func(context.Context, int64, *query.MessageQuery) ([]model.SysMessage, int64, error)) *MockIMessageRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID, msgType
func (_m *MockIMessageRepository) MarkAllRead(ctx context.Context, userID int64, msgType string) (int64, error) {
	ret := _m.Called(ctx, userID, msgType)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (int64, error)); ok {
		return rf(ctx, userID, msgType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = rf(ctx, userID, msgType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, msgType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockIMessageRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - msgType string
func (_e *MockIMessageRepository_Expecter) MarkAllRead(ctx interface{}, userID interface{}, msgType interface{}) *MockIMessageRepository_MarkAllRead_Call {
	return &MockIMessageRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID, msgType)}
}

func (_c *MockIMessageRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID int64, msgType string)) *MockIMessageRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockIMessageRepository_MarkAllRead_Call) Return(_a0 int64, _a1 error) *MockIMessageRepository_MarkAllRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_MarkAllRead_Call) RunAndReturn(run func(context.Context, int64, string) (int64, error)) *MockIMessageRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *MockIMessageRepository) MarkRead(ctx context.Context, id int64, userID int64) (int64, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMessageRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockIMessageRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID int64
func (_e *MockIMessageRepository_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}) *MockIMessageRepository_MarkRead_Call {
	return &MockIMessageRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID)}
}

func (_c *MockIMessageRepository_MarkRead_Call) Run(run func(ctx context.Context, id int64, userID int64)) *MockIMessageRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIMessageRepository_MarkRead_Call) Return(_a0 int64, _a1 error) *MockIMessageRepository_MarkRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMessageRepository_MarkRead_Call) RunAndReturn(run func(context.Context, int64, int64) (int64, error)) *MockIMessageRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPage provides a mock function with given fields: ctx, userID, q
func (_m *MockIMessageRepository) SearchPage(ctx context.Context, userID int64, q *query.MessageSearchQuery) ([]model.SysMessage, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for SearchPage")
	}

	var r0 []model.SysMessage
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MessageSearchQuery) ([]model.SysMessage, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.MessageSearchQuery) []model.SysMessage); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SysMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *query.MessageSearchQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *query.MessageSearchQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMessageRepository_SearchPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPage'
type MockIMessageRepository_SearchPage_Call struct {
	*mock.Call
}

// SearchPage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - q *query.MessageSearchQuery
func (_e *MockIMessageRepository_Expecter) SearchPage(ctx interface{}, userID interface{}, q interface{}) *MockIMessageRepository_SearchPage_Call {
	return &MockIMessageRepository_SearchPage_Call{Call: _e.mock.On("SearchPage", ctx, userID, q)}
}

func (_c *MockIMessageRepository_SearchPage_Call) Run(run func(ctx context.Context, userID int64, q *query.MessageSearchQuery)) *MockIMessageRepository_SearchPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*query.MessageSearchQuery))
	})
	return _c
}

func (_c *MockIMessageRepository_SearchPage_Call) Return(_a0 []model.SysMessage, _a1 int64, _a2 error) *MockIMessageRepository_SearchPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMessageRepository_SearchPage_Call) RunAndReturn(run func(context.Context, int64, *query.MessageSearchQuery) ([]model.SysMessage, int64, error)) *MockIMessageRepository_SearchPage_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, ids, userID
func (_m *MockIMessageRepository) SoftDelete(ctx context.Context, ids []int64, userID int64) error {
	ret := _m.Called(ctx, ids, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, int64) error); ok {
		r0 = rf(ctx, ids, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMessageRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockIMessageRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - userID int64
func (_e *MockIMessageRepository_Expecter) SoftDelete(ctx interface{}, ids interface{}, userID interface{}) *MockIMessageRepository_SoftDelete_Call {
	return &MockIMessageRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, ids, userID)}
}

func (_c *MockIMessageRepository_SoftDelete_Call) Run(run func(ctx context.Context, ids []int64, userID int64)) *MockIMessageRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(int64))
	})
	return _c
}

func (_c *MockIMessageRepository_SoftDelete_Call) Return(_a0 error) *MockIMessageRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMessageRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, []int64, int64) error) *MockIMessageRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMessageRepository creates a new instance of MockIMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMessageRepository {
	mock := &MockIMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
