// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	favorite "github.com/earthyzinc/dehaze-go/internal/repository/favorite"
	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"
)

// MockIFavoriteRepository is an autogenerated mock type for the IFavoriteRepository type
type MockIFavoriteRepository struct {
	mock.Mock
}

type MockIFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFavoriteRepository) EXPECT() *MockIFavoriteRepository_Expecter {
	return &MockIFavoriteRepository_Expecter{mock: &_m.Mock}
}

// CountByUserAndType provides a mock function with given fields: ctx, userID, targetType
func (_m *MockIFavoriteRepository) CountByUserAndType(ctx context.Context, userID int64, targetType string) (int64, error) {
	ret := _m.Called(ctx, userID, targetType)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserAndType")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (int64, error)); ok {
		return rf(ctx, userID, targetType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = rf(ctx, userID, targetType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, targetType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFavoriteRepository_CountByUserAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserAndType'
type MockIFavoriteRepository_CountByUserAndType_Call struct {
	*mock.Call
}

// CountByUserAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetType string
func (_e *MockIFavoriteRepository_Expecter) CountByUserAndType(ctx interface{}, userID interface{}, targetType interface{}) *MockIFavoriteRepository_CountByUserAndType_Call {
	return &MockIFavoriteRepository_CountByUserAndType_Call{Call: _e.mock.On("CountByUserAndType", ctx, userID, targetType)}
}

func (_c *MockIFavoriteRepository_CountByUserAndType_Call) Run(run func(ctx context.Context, userID int64, targetType string)) *MockIFavoriteRepository_CountByUserAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockIFavoriteRepository_CountByUserAndType_Call) Return(_a0 int64, _a1 error) *MockIFavoriteRepository_CountByUserAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFavoriteRepository_CountByUserAndType_Call) RunAndReturn(run func(context.Context, int64, string) (int64, error)) *MockIFavoriteRepository_CountByUserAndType_Call {
	_c.Call.Return(run)
	return _c
}

// CountByUserID provides a mock function with given fields: ctx, userID
func (_m *MockIFavoriteRepository) CountByUserID(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFavoriteRepository_CountByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByUserID'
type MockIFavoriteRepository_CountByUserID_Call struct {
	*mock.Call
}

// CountByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIFavoriteRepository_Expecter) CountByUserID(ctx interface{}, userID interface{}) *MockIFavoriteRepository_CountByUserID_Call {
	return &MockIFavoriteRepository_CountByUserID_Call{Call: _e.mock.On("CountByUserID", ctx, userID)}
}

func (_c *MockIFavoriteRepository_CountByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockIFavoriteRepository_CountByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIFavoriteRepository_CountByUserID_Call) Return(_a0 int64, _a1 error) *MockIFavoriteRepository_CountByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFavoriteRepository_CountByUserID_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockIFavoriteRepository_CountByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CountGroupByType provides a mock function with given fields: ctx, userID, targetType
func (_m *MockIFavoriteRepository) CountGroupByType(ctx context.Context, userID int64, targetType string) ([]favorite.CountByTypeRow, error) {
	ret := _m.Called(ctx, userID, targetType)

	if len(ret) == 0 {
		panic("no return value specified for CountGroupByType")
	}

	var r0 []favorite.CountByTypeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) ([]favorite.CountByTypeRow, error)); ok {
		return rf(ctx, userID, targetType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) []favorite.CountByTypeRow); ok {
		r0 = rf(ctx, userID, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]favorite.CountByTypeRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, targetType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFavoriteRepository_CountGroupByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountGroupByType'
type MockIFavoriteRepository_CountGroupByType_Call struct {
	*mock.Call
}

// CountGroupByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetType string
func (_e *MockIFavoriteRepository_Expecter) CountGroupByType(ctx interface{}, userID interface{}, targetType interface{}) *MockIFavoriteRepository_CountGroupByType_Call {
	return &MockIFavoriteRepository_CountGroupByType_Call{Call: _e.mock.On("CountGroupByType", ctx, userID, targetType)}
}

func (_c *MockIFavoriteRepository_CountGroupByType_Call) Run(run func(ctx context.Context, userID int64, targetType string)) *MockIFavoriteRepository_CountGroupByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockIFavoriteRepository_CountGroupByType_Call) Return(_a0 []favorite.CountByTypeRow, _a1 error) *MockIFavoriteRepository_CountGroupByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFavoriteRepository_CountGroupByType_Call) RunAndReturn(run func(context.Context, int64, string) ([]favorite.CountByTypeRow, error)) *MockIFavoriteRepository_CountGroupByType_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, f
func (_m *MockIFavoriteRepository) Create(ctx context.Context, f *model.SysFavorite) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysFavorite) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFavoriteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIFavoriteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - f *model.SysFavorite
func (_e *MockIFavoriteRepository_Expecter) Create(ctx interface{}, f interface{}) *MockIFavoriteRepository_Create_Call {
	return &MockIFavoriteRepository_Create_Call{Call: _e.mock.On("Create", ctx, f)}
}

func (_c *MockIFavoriteRepository_Create_Call) Run(run func(ctx context.Context, f *model.SysFavorite)) *MockIFavoriteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysFavorite))
	})
	return _c
}

func (_c *MockIFavoriteRepository_Create_Call) Return(_a0 error) *MockIFavoriteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFavoriteRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysFavorite) error) *MockIFavoriteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDs provides a mock function with given fields: ctx, userID, ids
func (_m *MockIFavoriteRepository) DeleteByIDs(ctx context.Context, userID int64, ids []int64) error {
	ret := _m.Called(ctx, userID, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) error); ok {
		r0 = rf(ctx, userID, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFavoriteRepository_DeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDs'
type MockIFavoriteRepository_DeleteByIDs_Call struct {
	*mock.Call
}

// DeleteByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - ids []int64
func (_e *MockIFavoriteRepository_Expecter) DeleteByIDs(ctx interface{}, userID interface{}, ids interface{}) *MockIFavoriteRepository_DeleteByIDs_Call {
	return &MockIFavoriteRepository_DeleteByIDs_Call{Call: _e.mock.On("DeleteByIDs", ctx, userID, ids)}
}

func (_c *MockIFavoriteRepository_DeleteByIDs_Call) Run(run func(ctx context.Context, userID int64, ids []int64)) *MockIFavoriteRepository_DeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockIFavoriteRepository_DeleteByIDs_Call) Return(_a0 error) *MockIFavoriteRepository_DeleteByIDs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFavoriteRepository_DeleteByIDs_Call) RunAndReturn(run func(context.Context, int64, []int64) error) *MockIFavoriteRepository_DeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndTarget provides a mock function with given fields: ctx, userID, targetType, targetID
func (_m *MockIFavoriteRepository) FindByUserAndTarget(ctx context.Context, userID int64, targetType string, targetID int64) (*model.SysFavorite, error) {
	ret := _m.Called(ctx, userID, targetType, targetID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndTarget")
	}

	var r0 *model.SysFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (*model.SysFavorite, error)); ok {
		return rf(ctx, userID, targetType, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) *model.SysFavorite); ok {
		r0 = rf(ctx, userID, targetType, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysFavorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, userID, targetType, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFavoriteRepository_FindByUserAndTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndTarget'
type MockIFavoriteRepository_FindByUserAndTarget_Call struct {
	*mock.Call
}

// FindByUserAndTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetType string
//   - targetID int64
func (_e *MockIFavoriteRepository_Expecter) FindByUserAndTarget(ctx interface{}, userID interface{}, targetType interface{}, targetID interface{}) *MockIFavoriteRepository_FindByUserAndTarget_Call {
	return &MockIFavoriteRepository_FindByUserAndTarget_Call{Call: _e.mock.On("FindByUserAndTarget", ctx, userID, targetType, targetID)}
}

func (_c *MockIFavoriteRepository_FindByUserAndTarget_Call) Run(run func(ctx context.Context, userID int64, targetType string, targetID int64)) *MockIFavoriteRepository_FindByUserAndTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockIFavoriteRepository_FindByUserAndTarget_Call) Return(_a0 *model.SysFavorite, _a1 error) *MockIFavoriteRepository_FindByUserAndTarget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFavoriteRepository_FindByUserAndTarget_Call) RunAndReturn(run func(context.Context, int64, string, int64) (*model.SysFavorite, error)) *MockIFavoriteRepository_FindByUserAndTarget_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, userID, q
func (_m *MockIFavoriteRepository) FindPage(ctx context.Context, userID int64, q *query.FavoritePageQuery) ([]favorite.FavoriteWithAlgorithm, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 []favorite.FavoriteWithAlgorithm
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.FavoritePageQuery) ([]favorite.FavoriteWithAlgorithm, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *query.FavoritePageQuery) []favorite.FavoriteWithAlgorithm); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]favorite.FavoriteWithAlgorithm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *query.FavoritePageQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *query.FavoritePageQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIFavoriteRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIFavoriteRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - q *query.FavoritePageQuery
func (_e *MockIFavoriteRepository_Expecter) FindPage(ctx interface{}, userID interface{}, q interface{}) *MockIFavoriteRepository_FindPage_Call {
	return &MockIFavoriteRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, userID, q)}
}

func (_c *MockIFavoriteRepository_FindPage_Call) Run(run func(ctx context.Context, userID int64, q *query.FavoritePageQuery)) *MockIFavoriteRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*query.FavoritePageQuery))
	})
	return _c
}

func (_c *MockIFavoriteRepository_FindPage_Call) Return(_a0 []favorite.FavoriteWithAlgorithm, _a1 int64, _a2 error) *MockIFavoriteRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIFavoriteRepository_FindPage_Call) RunAndReturn(run func(context.Context, int64, *query.FavoritePageQuery) ([]favorite.FavoriteWithAlgorithm, int64, error)) *MockIFavoriteRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInvalid provides a mock function with given fields: ctx, targetType, targetIDs
func (_m *MockIFavoriteRepository) MarkInvalid(ctx context.Context, targetType string, targetIDs []int64) error {
	ret := _m.Called(ctx, targetType, targetIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkInvalid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []int64) error); ok {
		r0 = rf(ctx, targetType, targetIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFavoriteRepository_MarkInvalid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInvalid'
type MockIFavoriteRepository_MarkInvalid_Call struct {
	*mock.Call
}

// MarkInvalid is a helper method to define mock.On call
//   - ctx context.Context
//   - targetType string
//   - targetIDs []int64
func (_e *MockIFavoriteRepository_Expecter) MarkInvalid(ctx interface{}, targetType interface{}, targetIDs interface{}) *MockIFavoriteRepository_MarkInvalid_Call {
	return &MockIFavoriteRepository_MarkInvalid_Call{Call: _e.mock.On("MarkInvalid", ctx, targetType, targetIDs)}
}

func (_c *MockIFavoriteRepository_MarkInvalid_Call) Run(run func(ctx context.Context, targetType string, targetIDs []int64)) *MockIFavoriteRepository_MarkInvalid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]int64))
	})
	return _c
}

func (_c *MockIFavoriteRepository_MarkInvalid_Call) Return(_a0 error) *MockIFavoriteRepository_MarkInvalid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFavoriteRepository_MarkInvalid_Call) RunAndReturn(run func(context.Context, string, []int64) error) *MockIFavoriteRepository_MarkInvalid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, id, updates
func (_m *MockIFavoriteRepository) UpdateByID(ctx context.Context, id int64, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFavoriteRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIFavoriteRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updates map[string]interface{}
func (_e *MockIFavoriteRepository_Expecter) UpdateByID(ctx interface{}, id interface{}, updates interface{}) *MockIFavoriteRepository_UpdateByID_Call {
	return &MockIFavoriteRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, updates)}
}

func (_c *MockIFavoriteRepository_UpdateByID_Call) Run(run func(ctx context.Context, id int64, updates map[string]interface{})) *MockIFavoriteRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIFavoriteRepository_UpdateByID_Call) Return(_a0 error) *MockIFavoriteRepository_UpdateByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFavoriteRepository_UpdateByID_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *MockIFavoriteRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, f
func (_m *MockIFavoriteRepository) Upsert(ctx context.Context, f *model.SysFavorite) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysFavorite) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFavoriteRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockIFavoriteRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - f *model.SysFavorite
func (_e *MockIFavoriteRepository_Expecter) Upsert(ctx interface{}, f interface{}) *MockIFavoriteRepository_Upsert_Call {
	return &MockIFavoriteRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, f)}
}

func (_c *MockIFavoriteRepository_Upsert_Call) Run(run func(ctx context.Context, f *model.SysFavorite)) *MockIFavoriteRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysFavorite))
	})
	return _c
}

func (_c *MockIFavoriteRepository_Upsert_Call) Return(_a0 error) *MockIFavoriteRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFavoriteRepository_Upsert_Call) RunAndReturn(run func(context.Context, *model.SysFavorite) error) *MockIFavoriteRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFavoriteRepository creates a new instance of MockIFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFavoriteRepository {
	mock := &MockIFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
