// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bo "github.com/earthyzinc/dehaze-go/internal/model/bo"

	mock "github.com/stretchr/testify/mock"

	model "github.com/earthyzinc/dehaze-go/internal/model"

	query "github.com/earthyzinc/dehaze-go/internal/model/query"

	read "github.com/earthyzinc/dehaze-go/internal/model/read"

	time "time"

	user "github.com/earthyzinc/dehaze-go/internal/repository/user"
)

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// AssignRoles provides a mock function with given fields: ctx, userID, roleIDs
func (_m *MockIUserRepository) AssignRoles(ctx context.Context, userID int64, roleIDs []int64) error {
	ret := _m.Called(ctx, userID, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) error); ok {
		r0 = rf(ctx, userID, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_AssignRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoles'
type MockIUserRepository_AssignRoles_Call struct {
	*mock.Call
}

// AssignRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - roleIDs []int64
func (_e *MockIUserRepository_Expecter) AssignRoles(ctx interface{}, userID interface{}, roleIDs interface{}) *MockIUserRepository_AssignRoles_Call {
	return &MockIUserRepository_AssignRoles_Call{Call: _e.mock.On("AssignRoles", ctx, userID, roleIDs)}
}

func (_c *MockIUserRepository_AssignRoles_Call) Run(run func(ctx context.Context, userID int64, roleIDs []int64)) *MockIUserRepository_AssignRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_AssignRoles_Call) Return(_a0 error) *MockIUserRepository_AssignRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_AssignRoles_Call) RunAndReturn(run func(context.Context, int64, []int64) error) *MockIUserRepository_AssignRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIUserRepository) Create(ctx context.Context, _a1 *model.SysUser) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysUser
func (_e *MockIUserRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(ctx context.Context, _a1 *model.SysUser)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysUser))
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(_a0 error) *MockIUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SysUser) error) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithRoles provides a mock function with given fields: ctx, _a1, roleIDs
func (_m *MockIUserRepository) CreateWithRoles(ctx context.Context, _a1 *model.SysUser, roleIDs []int64) error {
	ret := _m.Called(ctx, _a1, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser, []int64) error); ok {
		r0 = rf(ctx, _a1, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_CreateWithRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithRoles'
type MockIUserRepository_CreateWithRoles_Call struct {
	*mock.Call
}

// CreateWithRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysUser
//   - roleIDs []int64
func (_e *MockIUserRepository_Expecter) CreateWithRoles(ctx interface{}, _a1 interface{}, roleIDs interface{}) *MockIUserRepository_CreateWithRoles_Call {
	return &MockIUserRepository_CreateWithRoles_Call{Call: _e.mock.On("CreateWithRoles", ctx, _a1, roleIDs)}
}

func (_c *MockIUserRepository_CreateWithRoles_Call) Run(run func(ctx context.Context, _a1 *model.SysUser, roleIDs []int64)) *MockIUserRepository_CreateWithRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysUser), args[2].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_CreateWithRoles_Call) Return(_a0 error) *MockIUserRepository_CreateWithRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_CreateWithRoles_Call) RunAndReturn(run func(context.Context, *model.SysUser, []int64) error) *MockIUserRepository_CreateWithRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockIUserRepository) Delete(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIUserRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockIUserRepository_Delete_Call {
	return &MockIUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockIUserRepository_Delete_Call) Run(run func(ctx context.Context, ids []int64)) *MockIUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_Delete_Call) Return(_a0 error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Delete_Call) RunAndReturn(run func(context.Context, []int64) error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function with given fields: ctx, username, excludeID
func (_m *MockIUserRepository) ExistsByUsername(ctx context.Context, username string, excludeID ...int64) (bool, error) {
	_va := make([]interface{}, len(excludeID))
	for _i := range excludeID {
		_va[_i] = excludeID[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, username)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) (bool, error)); ok {
		return rf(ctx, username, excludeID...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...int64) bool); ok {
		r0 = rf(ctx, username, excludeID...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...int64) error); ok {
		r1 = rf(ctx, username, excludeID...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockIUserRepository_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - excludeID ...int64
func (_e *MockIUserRepository_Expecter) ExistsByUsername(ctx interface{}, username interface{}, excludeID ...interface{}) *MockIUserRepository_ExistsByUsername_Call {
	return &MockIUserRepository_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername",
		append([]interface{}{ctx, username}, excludeID...)...)}
}

func (_c *MockIUserRepository_ExistsByUsername_Call) Run(run func(ctx context.Context, username string, excludeID ...int64)) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]int64, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(int64)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUserRepository_ExistsByUsername_Call) Return(_a0 bool, _a1 error) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_ExistsByUsername_Call) RunAndReturn(run func(context.Context, string, ...int64) (bool, error)) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsernameInTx provides a mock function with given fields: ctx, username
func (_m *MockIUserRepository) ExistsByUsernameInTx(ctx context.Context, username string) (bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsernameInTx")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_ExistsByUsernameInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsernameInTx'
type MockIUserRepository_ExistsByUsernameInTx_Call struct {
	*mock.Call
}

// ExistsByUsernameInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) ExistsByUsernameInTx(ctx interface{}, username interface{}) *MockIUserRepository_ExistsByUsernameInTx_Call {
	return &MockIUserRepository_ExistsByUsernameInTx_Call{Call: _e.mock.On("ExistsByUsernameInTx", ctx, username)}
}

func (_c *MockIUserRepository_ExistsByUsernameInTx_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_ExistsByUsernameInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_ExistsByUsernameInTx_Call) Return(_a0 bool, _a1 error) *MockIUserRepository_ExistsByUsernameInTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_ExistsByUsernameInTx_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIUserRepository_ExistsByUsernameInTx_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsRootInIDs provides a mock function with given fields: ctx, ids
func (_m *MockIUserRepository) ExistsRootInIDs(ctx context.Context, ids []int64) (bool, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ExistsRootInIDs")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (bool, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) bool); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_ExistsRootInIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsRootInIDs'
type MockIUserRepository_ExistsRootInIDs_Call struct {
	*mock.Call
}

// ExistsRootInIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockIUserRepository_Expecter) ExistsRootInIDs(ctx interface{}, ids interface{}) *MockIUserRepository_ExistsRootInIDs_Call {
	return &MockIUserRepository_ExistsRootInIDs_Call{Call: _e.mock.On("ExistsRootInIDs", ctx, ids)}
}

func (_c *MockIUserRepository_ExistsRootInIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockIUserRepository_ExistsRootInIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_ExistsRootInIDs_Call) Return(_a0 bool, _a1 error) *MockIUserRepository_ExistsRootInIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_ExistsRootInIDs_Call) RunAndReturn(run func(context.Context, []int64) (bool, error)) *MockIUserRepository_ExistsRootInIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) FindByID(ctx context.Context, id int64) (*model.SysUser, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.SysUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.SysUser, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.SysUser); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockIUserRepository_FindByID_Call {
	return &MockIUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIUserRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockIUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserRepository_FindByID_Call) Return(_a0 *model.SysUser, _a1 error) *MockIUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*model.SysUser, error)) *MockIUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *MockIUserRepository) FindByUsername(ctx context.Context, username string) (*model.SysUser, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.SysUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.SysUser, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.SysUser); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SysUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockIUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockIUserRepository_FindByUsername_Call {
	return &MockIUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockIUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) Return(_a0 *model.SysUser, _a1 error) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*model.SysUser, error)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindExportUsers provides a mock function with given fields: ctx, q
func (_m *MockIUserRepository) FindExportUsers(ctx context.Context, q *query.UserPageQuery) ([]read.UserExport, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindExportUsers")
	}

	var r0 []read.UserExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) ([]read.UserExport, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) []read.UserExport); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]read.UserExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.UserPageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindExportUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExportUsers'
type MockIUserRepository_FindExportUsers_Call struct {
	*mock.Call
}

// FindExportUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.UserPageQuery
func (_e *MockIUserRepository_Expecter) FindExportUsers(ctx interface{}, q interface{}) *MockIUserRepository_FindExportUsers_Call {
	return &MockIUserRepository_FindExportUsers_Call{Call: _e.mock.On("FindExportUsers", ctx, q)}
}

func (_c *MockIUserRepository_FindExportUsers_Call) Run(run func(ctx context.Context, q *query.UserPageQuery)) *MockIUserRepository_FindExportUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.UserPageQuery))
	})
	return _c
}

func (_c *MockIUserRepository_FindExportUsers_Call) Return(_a0 []read.UserExport, _a1 error) *MockIUserRepository_FindExportUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindExportUsers_Call) RunAndReturn(run func(context.Context, *query.UserPageQuery) ([]read.UserExport, error)) *MockIUserRepository_FindExportUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindPage provides a mock function with given fields: ctx, q
func (_m *MockIUserRepository) FindPage(ctx context.Context, q *query.UserPageQuery) (*read.PageResult[read.UserPage], error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FindPage")
	}

	var r0 *read.PageResult[read.UserPage]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) (*read.PageResult[read.UserPage], error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery) *read.PageResult[read.UserPage]); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*read.PageResult[read.UserPage])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.UserPageQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPage'
type MockIUserRepository_FindPage_Call struct {
	*mock.Call
}

// FindPage is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.UserPageQuery
func (_e *MockIUserRepository_Expecter) FindPage(ctx interface{}, q interface{}) *MockIUserRepository_FindPage_Call {
	return &MockIUserRepository_FindPage_Call{Call: _e.mock.On("FindPage", ctx, q)}
}

func (_c *MockIUserRepository_FindPage_Call) Run(run func(ctx context.Context, q *query.UserPageQuery)) *MockIUserRepository_FindPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.UserPageQuery))
	})
	return _c
}

func (_c *MockIUserRepository_FindPage_Call) Return(_a0 *read.PageResult[read.UserPage], _a1 error) *MockIUserRepository_FindPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindPage_Call) RunAndReturn(run func(context.Context, *query.UserPageQuery) (*read.PageResult[read.UserPage], error)) *MockIUserRepository_FindPage_Call {
	_c.Call.Return(run)
	return _c
}

// FindPageWithRoles provides a mock function with given fields: ctx, q, deptIDs
func (_m *MockIUserRepository) FindPageWithRoles(ctx context.Context, q *query.UserPageQuery, deptIDs []int64) ([]read.UserPageWithRoles, int64, error) {
	ret := _m.Called(ctx, q, deptIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindPageWithRoles")
	}

	var r0 []read.UserPageWithRoles
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery, []int64) ([]read.UserPageWithRoles, int64, error)); ok {
		return rf(ctx, q, deptIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.UserPageQuery, []int64) []read.UserPageWithRoles); ok {
		r0 = rf(ctx, q, deptIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]read.UserPageWithRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.UserPageQuery, []int64) int64); ok {
		r1 = rf(ctx, q, deptIDs)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *query.UserPageQuery, []int64) error); ok {
		r2 = rf(ctx, q, deptIDs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIUserRepository_FindPageWithRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPageWithRoles'
type MockIUserRepository_FindPageWithRoles_Call struct {
	*mock.Call
}

// FindPageWithRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.UserPageQuery
//   - deptIDs []int64
func (_e *MockIUserRepository_Expecter) FindPageWithRoles(ctx interface{}, q interface{}, deptIDs interface{}) *MockIUserRepository_FindPageWithRoles_Call {
	return &MockIUserRepository_FindPageWithRoles_Call{Call: _e.mock.On("FindPageWithRoles", ctx, q, deptIDs)}
}

func (_c *MockIUserRepository_FindPageWithRoles_Call) Run(run func(ctx context.Context, q *query.UserPageQuery, deptIDs []int64)) *MockIUserRepository_FindPageWithRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*query.UserPageQuery), args[2].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_FindPageWithRoles_Call) Return(_a0 []read.UserPageWithRoles, _a1 int64, _a2 error) *MockIUserRepository_FindPageWithRoles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIUserRepository_FindPageWithRoles_Call) RunAndReturn(run func(context.Context, *query.UserPageQuery, []int64) ([]read.UserPageWithRoles, int64, error)) *MockIUserRepository_FindPageWithRoles_Call {
	_c.Call.Return(run)
	return _c
}

// FindRoleCodesByUsername provides a mock function with given fields: ctx, username
func (_m *MockIUserRepository) FindRoleCodesByUsername(ctx context.Context, username string) ([]string, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindRoleCodesByUsername")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindRoleCodesByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoleCodesByUsername'
type MockIUserRepository_FindRoleCodesByUsername_Call struct {
	*mock.Call
}

// FindRoleCodesByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) FindRoleCodesByUsername(ctx interface{}, username interface{}) *MockIUserRepository_FindRoleCodesByUsername_Call {
	return &MockIUserRepository_FindRoleCodesByUsername_Call{Call: _e.mock.On("FindRoleCodesByUsername", ctx, username)}
}

func (_c *MockIUserRepository_FindRoleCodesByUsername_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_FindRoleCodesByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindRoleCodesByUsername_Call) Return(_a0 []string, _a1 error) *MockIUserRepository_FindRoleCodesByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindRoleCodesByUsername_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockIUserRepository_FindRoleCodesByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserAuthInfo provides a mock function with given fields: ctx, username
func (_m *MockIUserRepository) FindUserAuthInfo(ctx context.Context, username string) (*model.UserAuthInfo, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserAuthInfo")
	}

	var r0 *model.UserAuthInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserAuthInfo, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserAuthInfo); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAuthInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_FindUserAuthInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserAuthInfo'
type MockIUserRepository_FindUserAuthInfo_Call struct {
	*mock.Call
}

// FindUserAuthInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) FindUserAuthInfo(ctx interface{}, username interface{}) *MockIUserRepository_FindUserAuthInfo_Call {
	return &MockIUserRepository_FindUserAuthInfo_Call{Call: _e.mock.On("FindUserAuthInfo", ctx, username)}
}

func (_c *MockIUserRepository_FindUserAuthInfo_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_FindUserAuthInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_FindUserAuthInfo_Call) Return(_a0 *model.UserAuthInfo, _a1 error) *MockIUserRepository_FindUserAuthInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_FindUserAuthInfo_Call) RunAndReturn(run func(context.Context, string) (*model.UserAuthInfo, error)) *MockIUserRepository_FindUserAuthInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, userID
func (_m *MockIUserRepository) GetFormData(ctx context.Context, userID int64) (*bo.UserFormBO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 *bo.UserFormBO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*bo.UserFormBO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *bo.UserFormBO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.UserFormBO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type MockIUserRepository_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIUserRepository_Expecter) GetFormData(ctx interface{}, userID interface{}) *MockIUserRepository_GetFormData_Call {
	return &MockIUserRepository_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, userID)}
}

func (_c *MockIUserRepository_GetFormData_Call) Run(run func(ctx context.Context, userID int64)) *MockIUserRepository_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserRepository_GetFormData_Call) Return(_a0 *bo.UserFormBO, _a1 error) *MockIUserRepository_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_GetFormData_Call) RunAndReturn(run func(context.Context, int64) (*bo.UserFormBO, error)) *MockIUserRepository_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoleIDs provides a mock function with given fields: ctx, userID
func (_m *MockIUserRepository) GetUserRoleIDs(ctx context.Context, userID int64) ([]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoleIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_GetUserRoleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoleIDs'
type MockIUserRepository_GetUserRoleIDs_Call struct {
	*mock.Call
}

// GetUserRoleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIUserRepository_Expecter) GetUserRoleIDs(ctx interface{}, userID interface{}) *MockIUserRepository_GetUserRoleIDs_Call {
	return &MockIUserRepository_GetUserRoleIDs_Call{Call: _e.mock.On("GetUserRoleIDs", ctx, userID)}
}

func (_c *MockIUserRepository_GetUserRoleIDs_Call) Run(run func(ctx context.Context, userID int64)) *MockIUserRepository_GetUserRoleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockIUserRepository_GetUserRoleIDs_Call) Return(_a0 []int64, _a1 error) *MockIUserRepository_GetUserRoleIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_GetUserRoleIDs_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *MockIUserRepository_GetUserRoleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ImportUserInTx provides a mock function with given fields: ctx, _a1
func (_m *MockIUserRepository) ImportUserInTx(ctx context.Context, _a1 *model.SysUser) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ImportUserInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_ImportUserInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportUserInTx'
type MockIUserRepository_ImportUserInTx_Call struct {
	*mock.Call
}

// ImportUserInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysUser
func (_e *MockIUserRepository_Expecter) ImportUserInTx(ctx interface{}, _a1 interface{}) *MockIUserRepository_ImportUserInTx_Call {
	return &MockIUserRepository_ImportUserInTx_Call{Call: _e.mock.On("ImportUserInTx", ctx, _a1)}
}

func (_c *MockIUserRepository_ImportUserInTx_Call) Run(run func(ctx context.Context, _a1 *model.SysUser)) *MockIUserRepository_ImportUserInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysUser))
	})
	return _c
}

func (_c *MockIUserRepository_ImportUserInTx_Call) Return(_a0 error) *MockIUserRepository_ImportUserInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_ImportUserInTx_Call) RunAndReturn(run func(context.Context, *model.SysUser) error) *MockIUserRepository_ImportUserInTx_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteWithTime provides a mock function with given fields: ctx, ids, updateTime
func (_m *MockIUserRepository) SoftDeleteWithTime(ctx context.Context, ids []int64, updateTime time.Time) error {
	ret := _m.Called(ctx, ids, updateTime)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteWithTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, time.Time) error); ok {
		r0 = rf(ctx, ids, updateTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_SoftDeleteWithTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteWithTime'
type MockIUserRepository_SoftDeleteWithTime_Call struct {
	*mock.Call
}

// SoftDeleteWithTime is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - updateTime time.Time
func (_e *MockIUserRepository_Expecter) SoftDeleteWithTime(ctx interface{}, ids interface{}, updateTime interface{}) *MockIUserRepository_SoftDeleteWithTime_Call {
	return &MockIUserRepository_SoftDeleteWithTime_Call{Call: _e.mock.On("SoftDeleteWithTime", ctx, ids, updateTime)}
}

func (_c *MockIUserRepository_SoftDeleteWithTime_Call) Run(run func(ctx context.Context, ids []int64, updateTime time.Time)) *MockIUserRepository_SoftDeleteWithTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIUserRepository_SoftDeleteWithTime_Call) Return(_a0 error) *MockIUserRepository_SoftDeleteWithTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_SoftDeleteWithTime_Call) RunAndReturn(run func(context.Context, []int64, time.Time) error) *MockIUserRepository_SoftDeleteWithTime_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockIUserRepository) Transaction(ctx context.Context, fn func(user.IUserRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(user.IUserRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockIUserRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(user.IUserRepository) error
func (_e *MockIUserRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockIUserRepository_Transaction_Call {
	return &MockIUserRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockIUserRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(user.IUserRepository) error)) *MockIUserRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(user.IUserRepository) error))
	})
	return _c
}

func (_c *MockIUserRepository_Transaction_Call) Return(_a0 error) *MockIUserRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(user.IUserRepository) error) error) *MockIUserRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockIUserRepository) Update(ctx context.Context, _a1 *model.SysUser) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SysUser) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *model.SysUser
func (_e *MockIUserRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockIUserRepository_Update_Call {
	return &MockIUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockIUserRepository_Update_Call) Run(run func(ctx context.Context, _a1 *model.SysUser)) *MockIUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SysUser))
	})
	return _c
}

func (_c *MockIUserRepository_Update_Call) Return(_a0 error) *MockIUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SysUser) error) *MockIUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, password
func (_m *MockIUserRepository) UpdatePassword(ctx context.Context, id int64, password string) error {
	ret := _m.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockIUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - password string
func (_e *MockIUserRepository_Expecter) UpdatePassword(ctx interface{}, id interface{}, password interface{}) *MockIUserRepository_UpdatePassword_Call {
	return &MockIUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, password)}
}

func (_c *MockIUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, id int64, password string)) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) Return(_a0 error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordWithTime provides a mock function with given fields: ctx, id, password, updateTime
func (_m *MockIUserRepository) UpdatePasswordWithTime(ctx context.Context, id int64, password string, updateTime time.Time) error {
	ret := _m.Called(ctx, id, password, updateTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordWithTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) error); ok {
		r0 = rf(ctx, id, password, updateTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdatePasswordWithTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordWithTime'
type MockIUserRepository_UpdatePasswordWithTime_Call struct {
	*mock.Call
}

// UpdatePasswordWithTime is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - password string
//   - updateTime time.Time
func (_e *MockIUserRepository_Expecter) UpdatePasswordWithTime(ctx interface{}, id interface{}, password interface{}, updateTime interface{}) *MockIUserRepository_UpdatePasswordWithTime_Call {
	return &MockIUserRepository_UpdatePasswordWithTime_Call{Call: _e.mock.On("UpdatePasswordWithTime", ctx, id, password, updateTime)}
}

func (_c *MockIUserRepository_UpdatePasswordWithTime_Call) Run(run func(ctx context.Context, id int64, password string, updateTime time.Time)) *MockIUserRepository_UpdatePasswordWithTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockIUserRepository_UpdatePasswordWithTime_Call) Return(_a0 error) *MockIUserRepository_UpdatePasswordWithTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdatePasswordWithTime_Call) RunAndReturn(run func(context.Context, int64, string, time.Time) error) *MockIUserRepository_UpdatePasswordWithTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockIUserRepository) UpdateStatus(ctx context.Context, id int64, status int8) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int8) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIUserRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status int8
func (_e *MockIUserRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockIUserRepository_UpdateStatus_Call {
	return &MockIUserRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockIUserRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int64, status int8)) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int8))
	})
	return _c
}

func (_c *MockIUserRepository_UpdateStatus_Call) Return(_a0 error) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int64, int8) error) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusWithTime provides a mock function with given fields: ctx, id, status, updateTime
func (_m *MockIUserRepository) UpdateStatusWithTime(ctx context.Context, id int64, status int8, updateTime time.Time) error {
	ret := _m.Called(ctx, id, status, updateTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusWithTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int8, time.Time) error); ok {
		r0 = rf(ctx, id, status, updateTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdateStatusWithTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusWithTime'
type MockIUserRepository_UpdateStatusWithTime_Call struct {
	*mock.Call
}

// UpdateStatusWithTime is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - status int8
//   - updateTime time.Time
func (_e *MockIUserRepository_Expecter) UpdateStatusWithTime(ctx interface{}, id interface{}, status interface{}, updateTime interface{}) *MockIUserRepository_UpdateStatusWithTime_Call {
	return &MockIUserRepository_UpdateStatusWithTime_Call{Call: _e.mock.On("UpdateStatusWithTime", ctx, id, status, updateTime)}
}

func (_c *MockIUserRepository_UpdateStatusWithTime_Call) Run(run func(ctx context.Context, id int64, status int8, updateTime time.Time)) *MockIUserRepository_UpdateStatusWithTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int8), args[3].(time.Time))
	})
	return _c
}

func (_c *MockIUserRepository_UpdateStatusWithTime_Call) Return(_a0 error) *MockIUserRepository_UpdateStatusWithTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdateStatusWithTime_Call) RunAndReturn(run func(context.Context, int64, int8, time.Time) error) *MockIUserRepository_UpdateStatusWithTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithRoles provides a mock function with given fields: ctx, userID, updates, roleIDs
func (_m *MockIUserRepository) UpdateWithRoles(ctx context.Context, userID int64, updates map[string]interface{}, roleIDs []int64) error {
	ret := _m.Called(ctx, userID, updates, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}, []int64) error); ok {
		r0 = rf(ctx, userID, updates, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdateWithRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithRoles'
type MockIUserRepository_UpdateWithRoles_Call struct {
	*mock.Call
}

// UpdateWithRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - updates map[string]interface{}
//   - roleIDs []int64
func (_e *MockIUserRepository_Expecter) UpdateWithRoles(ctx interface{}, userID interface{}, updates interface{}, roleIDs interface{}) *MockIUserRepository_UpdateWithRoles_Call {
	return &MockIUserRepository_UpdateWithRoles_Call{Call: _e.mock.On("UpdateWithRoles", ctx, userID, updates, roleIDs)}
}

func (_c *MockIUserRepository_UpdateWithRoles_Call) Run(run func(ctx context.Context, userID int64, updates map[string]interface{}, roleIDs []int64)) *MockIUserRepository_UpdateWithRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}), args[3].([]int64))
	})
	return _c
}

func (_c *MockIUserRepository_UpdateWithRoles_Call) Return(_a0 error) *MockIUserRepository_UpdateWithRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdateWithRoles_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}, []int64) error) *MockIUserRepository_UpdateWithRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
