# general settings
name: SCA-I-HAZE
model_type: SCAModel
num_gpu: 1 # set num_gpu: 0 for cpu mode
gpu_id: 0
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: I-HAZE-train
    type: NtireH5Dataset
    mode: train
    data_path: datasets/I-HAZE.h5
    shuffle: true

    # data loader
    use_shuffle: true
    batch_size_per_gpu: &bsz 1
    num_worker_per_gpu: *bsz
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: *bsz

  val:
    name: I-HAZE-val
    type: NtireH5Dataset
    mode: val
    data_path: datasets/I-HAZE-val.h5
    shuffle: true

  test:
    name: I-HAZE-test
    type: NtireH5Dataset
    mode: test
    data_path: datasets/I-HAZE-test.h5
    shuffle: true

# network structures
network_g:
  type: SCA

# path
path:
  pretrain_network_g: pretrained_models/compare/SCANet/SCANet.pth
  pretrain_network_d: ~
  strict_load: false
  # resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 0.0001
    betas: [0.9, 0.999]
    eps: !!float 1e-08

  total_iter: 100000

  # losses
  perceptual_opt: ture


# validation settings·
val:
  val_freq: !!float 5000
  save_img: true
  suffix: I-HAZE
  key_metric: psnr
  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: ssim
      crop_border: 4
      test_y_channel: true
    lpips:
      type: lpips
      better: lower
    niqe:
      type: niqe
      better: lower
    brisque:
      type: brisque
      better: lower
    nima:
      type: nima
      better: higher

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e3
  save_latest_freq: !!float 5e3
  show_tf_imgs_freq: !!float 5e3
  use_tb_logger: true
