export default defineAppConfig({
  pages: [
    "pages/home/index",
    "pages/dataset/index",
    "pages/login/index",
    "pages/dashboard/index",
    "pages/system/user/index",
    "pages/system/user/detail",
    "pages/system/role/index",
    "pages/system/role/detail",
    "pages/system/role/permission",
    "pages/system/dict/index",
    "pages/system/menu/index",
    "pages/system/dept/index",
    "pages/image-input/index",
    "pages/algorithm-select/index",
    "pages/processing/index",
    "pages/side-by-side/index",
    "pages/overlay/index",
    "pages/metrics/index",
    "pages/magnifier/index",
    "pages/filter/index",
    "pages/task/index",
    "pages/algorithm/index",
    "pages/profile/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#ffffff",
    navigationBarTitleText: "图像去雾系统",
    navigationBarTextStyle: "black",
    navigationStyle: "custom",
  },
});
