export default defineAppConfig({
  pages: [
    "pages/home/index",
    "pages/tools/index",
    "pages/dehaze/index",
    "pages/messages/index",
    "pages/messages/detail/index",
    "pages/dataset/index",
    "pages/login/index",
    "pages/register/index",
    "pages/dashboard/index",
    "pages/system/user/index",
    "pages/system/user/detail",
    "pages/system/role/index",
    "pages/system/role/detail",
    "pages/system/role/permission",
    "pages/system/dict/index",
    "pages/system/menu/index",
    "pages/system/dept/index",
    "pages/system/algorithm/index",
    "pages/system/dataset/index",
    "pages/system/task/index",
    "pages/system/member/index",
    "pages/system/package/index",
    "pages/system/order/index",
    "pages/system/feedback/index",
    "pages/system/message/index",
    "pages/system/recommend/index",
    "pages/image-input/index",
    "pages/algorithm-select/index",
    "pages/processing/index",
    "pages/side-by-side/index",
    "pages/overlay/index",
    "pages/metrics/index",
    "pages/magnifier/index",
    "pages/filter/index",
    "pages/task/index",
    "pages/algorithm/index",
    "pages/profile/index",
    "pages/favorite/index",
    "pages/notify/index",
    "pages/personal/files/index",
    "pages/personal/orders/index",
    "pages/personal/quota/index",
    "pages/personal/settings/index",
    "pages/personal/help/index",
    "pages/personal/about/index",
    "pages/personal/member/index",
    "pages/personal/package/index",
    "pages/personal/feedback/index",
    "pages/batch/index",
    "pages/metrics-manage/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#ffffff",
    navigationBarTitleText: "图像去雾系统",
    navigationBarTextStyle: "black",
    navigationStyle: "custom",
  },
  // 原生 tabBar：5 个 L1 Tab 根页面（与 dehaze-mobile 设计稿底部导航一致）
  tabBar: {
    color: "#9CA3AF",
    selectedColor: "#3B82F6",
    backgroundColor: "#ffffff",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/home/index",
        text: "首页",
        iconPath: "assets/tabbar/home.png",
        selectedIconPath: "assets/tabbar/home-active.png",
      },
      {
        pagePath: "pages/tools/index",
        text: "工具",
        iconPath: "assets/tabbar/tools.png",
        selectedIconPath: "assets/tabbar/tools-active.png",
      },
      {
        pagePath: "pages/dehaze/index",
        text: "去雾",
        iconPath: "assets/tabbar/dehaze.png",
        selectedIconPath: "assets/tabbar/dehaze-active.png",
      },
      {
        pagePath: "pages/messages/index",
        text: "消息",
        iconPath: "assets/tabbar/messages.png",
        selectedIconPath: "assets/tabbar/messages-active.png",
      },
      {
        pagePath: "pages/profile/index",
        text: "我的",
        iconPath: "assets/tabbar/profile.png",
        selectedIconPath: "assets/tabbar/profile-active.png",
      },
    ],
  },
});
