[versions]
junit = "4.13.2"
loggingInterceptor = "5.2.1"
lombok = "1.18.42"
mockitoCore = "5.20.0"
retrofit = "3.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
