onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - msw
  - utf-8-validate
  - vue-demi

overrides:
  dehaze-sdk-js: link:../dehaze-sdk-js
